### ISSUE TITLE
How to get cucumber report for single folder under workspace

### ISSUE THREAD

**Issue by akapoor47** [jenkinsci/cucumber-reports-plugin#103]
Using Java/cucumber - 
I have build parameter which lets user select service or UI component to test. All together there are 10 options in build parameter. Every option in build parameter translates to cucmber/jvm test suite.
Is there a way to configure cucumber-JVM reports to only display results for service which was selected.

**Comment by damianszczepanik** [comment]
I'm not sure what exactly you need but you may find useful this PR for tags https://github.com/damianszczepanik/cucumber-reporting/pull/486
