### ISSUE TITLE
[Scala|SBT|Hooks] Undesired content

### ISSUE THREAD

**Issue by lauriemhu** [jenkinsci/cucumber-reports-plugin#104]
Hi,
I have just installed this plugin and it is almost perfect ! Thanks for everything.

But ... before and after each scenario I have "Hooks" tab. It contains only this sentence

> "**After** TODO: Implement getLocation in similar fashion to ScalaStepDefinition 021ms".

I would like to hide this.

Do you know how to hide "Hooks" because I don't use it ? 
and/or
Is it easy to override the getLocation method ? (I did not succeed in implementing this solution)

Edit : here you have the JSON file 
[results.json.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/639954/results.json.txt)

**Comment by damianszczepanik** [comment]
Attach JSON file so I can take a look

**Comment by damianszczepanik** [comment]
Attach JSON file so I can take a look

**Comment by damianszczepanik** [comment]
Attach JSON file so I can take a look

**Comment by damianszczepanik** [comment]
Sorry for delay - you can expand or collapse hook section but it is not possible to hide/delete it from the report

**Comment by chaitanyakuber** [comment]
Could you consider this as a feature request please? This line does spam the report

![screenshot 2017-01-23 12 33 48](https://cloud.githubusercontent.com/assets/133762/22188327/34e37c0c-e168-11e6-8566-0f20c40b2b4f.png)

**Comment by damianszczepanik** [comment]
This request is closed

**Comment by chaitanyakuber** [comment]
yeah, i noticed after making the comment. was hoping to convince the authors to reopen the issue
