### ISSUE TITLE
README instructions are out of date

### ISSUE THREAD

**Issue by andygrove** [jenkinsci/cucumber-reports-plugin#110]
The README says to pass these parameters to Cucumber. The docs aren't clear on which flavor or version of cucumber this is for. 

```--format json -o cucumber.json```

I'm using cucumber-jvm and if I pass these arguments to `cucumber.api.cli.Main` then I get this error:

```Cucumber-JVM's --format option is deprecated. Please use --plugin instead.```

I'm  using cucumber-jvm version 1.2.5

**Comment by andygrove** [comment]
The correct args for cucumber-jvm are: 

```--plugin json:target/cucumber/cucumber.json```

**Comment by damianszczepanik** [comment]
Would you like to preapre PR for this?
