### ISSUE TITLE
Expose advanced functionality to the Jenkins reporting plugin

### ISSUE THREAD

**Issue by githubist16** [jenkinsci/cucumber-reports-plugin#112]
There are multiple use cases where extra information or metadata may be added to the report. Ex. Browser: Firefox. 

Looking at the cucumber-reporting repo, it appears that this is possible using code similar to:
`configuration.addClassifications("Browser",  "Firefox")`

Can this functionality be exposed in the Jenkins plugin?

**Comment by damianszczepanik** [comment]
It should and it will be there. Do you want to provide PR for this
