### ISSUE TITLE
How can I see/add classifications in my reports using Jenkins plugin

### ISSUE THREAD

**Issue by anandbagmar** [jenkinsci/cucumber-reports-plugin#115]
Hi,
I have created a custom report by adding classifications in the configuration object. This works great when I run the tests locally.

However, when running the tests from Jenkins, when I use the Jenkins Cucumber Reports plugin, the report is generated on-the-fly and my custom reports details (classifications) are not seen. 

I have also archived my custom reports in Jenkins (as a post-build action) - but here - the links (Previous Results, Latest Results) in the header are incorrect and also the trends cannot be seen.

So, I have 2 questions:
1. How can I add custom classifications in the cucumber-reports when using the Jenkins Cucumber Plugin? Also, how can I see these custom classifications on not just the Feature page, but also Tags, Steps and Failures page?
2. If I generate the custom reports as part of my test execution, then is there a way to update what links should be created in the reports (so that Latest Results, Previous Results and Trends) can work correctly?

Thanks.

**Comment by damianszczepanik** [comment]
1. Has been already fixed. Wait for next release. 
2. There is no such option.

**Comment by anandbagmar** [comment]
Thank you for the super fast reply! Looking forward to the release! 

Would there be a way to provide these classifications based on a file in the reports directory? That would provide a lot of flexibility in generating rich and context specific reports.

**Comment by damianszczepanik** [comment]
Rather not. You need to extract it by yourself :)

**Comment by e2etesterviu** [comment]
Sure thing. Already thought of how to do that 👍  Any approximate time when the next release would be available?
