### ISSUE TITLE
Trends for Feature/Scenario Duration

### ISSUE THREAD

**Issue by biagiolampo** [jenkinsci/cucumber-reports-plugin#130]
Hi,
it would be very useful to have on jenkins the trends for Feature/Scenario duration.
This could help on having a benchmarking for each Feature/Scenario.
The reason of having this is especially related to products where there are some Performance KPI to be secured.

Thanks
Biagio

**Comment by damianszczepanik** [comment]
Duplicate of https://github.com/damianszczepanik/cucumber-reporting/issues/609
