### ISSUE TITLE
How to use this plugin in groovy dsl script in Jenkins

### ISSUE THREAD

**Issue by murmangit** [jenkinsci/cucumber-reports-plugin#131]
I'm using Jenkins Pipeline job and I don't have option to select cucumber-reports plugin like Jenkin free style job.

Can you please help me how can I use this plugin in my Jenkins DSL Script?

Below is my sample DSL Script to run my Jenkins Pipeline job:

node(jenkinsSlave) {
stage 'Execute my Junit test'
mvn -s ../${settings}  -DskipUnitTests -Dmaven.repo.local=${workspace} -f pom.xml

}

**Comment by damianszczepanik** [comment]
Better support will be available in next release

**Comment by anandbagmar** [comment]
@murmangit - see the examples in #118 - that may help you

**Comment by yael-lorenzo-olx** [comment]
step([$class: 'CucumberReportPublisher', jsonReportDirectory: 'target', fileIncludePattern: 'cucumber.json'])
