### ISSUE TITLE
Step duration still indicating "000ms"

### ISSUE THREAD

**Issue by rcarrette** [jenkinsci/cucumber-reports-plugin#135]
Hi !

I m generating Cucumber .json report to display on Jenkins. Everything works fine, except the step duration which is always showing "000ms". Is this a known issue ?

I tried using a .json sample provided in the [documentation](https://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter), but it's the same.

Thanks in advance.

**Comment by damianszczepanik** [comment]
Chech if you have sec or ms or Ns in your report

**Comment by rcarrette** [comment]
Could you explain a little more please ? I have "ms" in the report

**Comment by damianszczepanik** [comment]
Reports takes ns as the input metrics but displays ms so count your duration and check what you put and what you got.

**Comment by rcarrette** [comment]
Ok thanks. Using nanoseconds made the trick ! :)
