### ISSUE TITLE
Try to add link to the report

### ISSUE THREAD

**Issue by FrankS77** [jenkinsci/cucumber-reports-plugin#140]
Hello,

I tried to add a link to the cucumber report in Java with "Scenario.write" and the link 
is correctly displayed in the "cucumber-html-report" but not in the Jenkins Cucumber Report.
It is because the HTML characters "<,>"are escaped to "& lt; and & gt;". So the link is displayed
as text and not clickable.
Is this somewhere configurable or a bug or a missing feature?

Thanks in advance

**Comment by mpkorstanje** [comment]
Injecting HTML into reports posed a security risk. You can use
scenario.embed to embed html safely. See:

https://github.com/damianszczepanik/cucumber-reporting/issues/610

**Comment by FrankS77** [comment]
Thanks!!!
