### ISSUE TITLE
How to update the order of scenarios as per execution as in new cucumber-jvm reports it is displaying in chronological sorting report format?

### ISSUE THREAD

**Issue by vishwasbabhare** [jenkinsci/cucumber-reports-plugin#141]
We used Cucumber Report (old i.e. 0.0.24) and now it is updated (new i.e. 2.0) .
New report format is very good.
One thing the newer reports do not replicate that the old reports did is the order of which the scenarios are run in.
This is helpful and important if comparing the scenarios with older runs, and if debugging an automation run.

Add "Timestamp Started" or "Timestamp Completed" so I wanted to use the new report format plus chronological sorting, deltas between report runs, etc..

**Comment by damianszczepanik** [comment]
The reason of that change was to improve searching scenarios. On the other hand scenarios should be independent so your need means that you probably should refactored way how you test and run it.

**Comment by lvinniel** [comment]
I agree with vishwasbabhare.  I'm in need of "Timestamp Started" column to order the table accordingly.

**Comment by damianszczepanik** [comment]
OK< so maybe I missunderstood your need: you want to be able to sort features in order they were executed, so the same as they are in JSON file. Is that correct?

**Comment by vishwasbabhare** [comment]
Absolutely correct. Please let me know if you have any additional queries for me.

New HTML reporting is also very impressive.

**Comment by damianszczepanik** [comment]
OK, so I see option for ordering:
- natural - the one which is in JSON file and the same you expect to have
- alphabetical - currently implemented as default
- failures first - failures will be displayed at the top of the list so there is no need to browse while report for failures

**Comment by mayankporwal08** [comment]
Hi Damianszczepanik, I am also using Jenkins Cucumber-report -plugin and I need to arrange my cucumber report to be order in natural order. So to achieve the same what parameter I need to set and where it need to set in jenkins? 

Please help me om this.

Thanks in advance.

**Comment by damianszczepanik** [comment]
Looks like the support has been added to cucumber but not to the plugin... Would you like to add support for this little feature so it can he released with next version

**Comment by damianszczepanik** [comment]
Should be fine with recent release

**Comment by vanatomas** [comment]
@damianszczepanik is there a way to change feature order sort via plugin? Seems like it is running in Natural rather than Alphabetical. Was alphabetical set in specific version of this plugin?

**Comment by damianszczepanik** [comment]
It does
