### ISSUE TITLE
Update README.md:  Document Changed Build Result Options

### ISSUE THREAD

**Issue by msymons** [jenkinsci/cucumber-reports-plugin#143]
Using and loving cucumber-reports-plugin v3.6.1

The "Build Result" options now allow one to specify a minimal NUMBER of failed/skipped (etc) steps that are required in order to make a build Failed or Unstable.  In earlier versions this configuration was a checkbox - eg, a just one single failed step could fail a build (or 200 failed steps could still result in a passing build).

The new functionality is much more powerful.

The version v3.6.1 README.md still documents the old behaviour & should be updated.

Separately:

Readme says "You must use a Freestyle project type in jenkins."

Has this changed?  We are using maven projects and all seems OK.

Lastly:

v3.6.1 README.CMD is failing to display images correctly on github.

**Comment by msymons** [comment]
I'll try...  although I am still learning github.  I would have to work out how to fix the broken images links, etc.

So, has there been a change to the project type (freestyle vs maven)?

Separately..  I assume that the value "0" is ignored in fields such as "Number of failed steps", right?  Otherwise, surely that would mean that "good" builds (zero failed steps, etc) would then fail?

**Comment by damianszczepanik** [comment]
I'm not sure about 'freestyle' limitation but you can try to add this step for eg maven project and chech :)

0 means 0 failure otherwise build is failed.

**Comment by damianszczepanik** [comment]
Already fixed
