### ISSUE TITLE
Output in scenario is not formatted.

### ISSUE THREAD

**Issue by pax2k** [jenkinsci/cucumber-reports-plugin#145]
Our project uses a lot of writing to the “output”. This is information that the product owner uses to manually look at the test results (`scenario.write(“some text”);`).

After updating to 3.6.0/3.6.1 the output is not formatted. All line break, tab etc is removed and the report does not look good at all.

Is there anything we can do to get proper formatting again?

Best regards
Raymond Koteng

Expected result(3.5.1):
![jenkins](https://cloud.githubusercontent.com/assets/143016/24404978/75ebf25a-13c3-11e7-9c7d-35dba3c19eb9.png)

**Comment by mpkorstanje** [comment]
Looks like some styling is missing. I'll take a look.

**Comment by pax2k** [comment]
Hi.

Thank you for the fast replay.
Hope you will be able to fix this issue as the devops team are eager to update all plugins :)

Best regards
Raymond Koteng

**Comment by mpkorstanje** [comment]
Looks like this was caused by:

https://github.com/damianszczepanik/cucumber-reporting/pull/594

**Comment by mpkorstanje** [comment]
That should fix it.
