### ISSUE TITLE
Broken formatting 

### ISSUE THREAD

**Issue by roman-grytsay** [jenkinsci/cucumber-reports-plugin#15]
Jenkins ver. 1.644
Plugin ver. 1.1.0
All pages: feature view, tag view, overview...
Please see the attachment.
![cucumber](https://cloud.githubusercontent.com/assets/8222971/12357919/03367b98-bbab-11e5-9408-f7446197d3c8.png)

**Comment by damianszczepanik** [comment]
Duplicate of jenkinsci/cucumber-reports-plugin/issues/7
