### ISSUE TITLE
cucumber pipeline method does not exist

### ISSUE THREAD

**Issue by achoimet** [jenkinsci/cucumber-reports-plugin#160]
hello,

the method for pipeline use named "cucumber" does not exist yet ?

i've got the latest version stable of jenkins (2.60.1) and the latest version  of plugin  3.8 and that throw an error ..

java.lang.NoSuchMethodError: No such DSL method 'cucumber' found among steps

**Comment by kapoorlakshya** [comment]
I think you will have to wait for the next version. The PR for that feature was merged in 7 days ago and v3.8.0 was released 24 days ago.

PR - https://github.com/jenkinsci/cucumber-reports-plugin/pull/139
Release v3.8.0 Release - https://github.com/jenkinsci/cucumber-reports-plugin/releases/tag/cucumber-reports-3.8.0

**Comment by damianszczepanik** [comment]
True, will be available with next release.

**Comment by abaird** [comment]
Do we have a timeline on the next release? I'd really like to use this plugin with Pipeline.
