### ISSUE TITLE
Error using jenkinsFile

### ISSUE THREAD

**Issue by pablonunezg** [jenkinsci/cucumber-reports-plugin#162]
When I tried to execute:

 pipeline {
     
    agent any

    stages {
        stage('Build') {
            steps {
                //run your build
                sh './gradlew clean build cucumber'
            }
            post {
                always {
                    //generate cucumber reports
                    cucumber '**/*.json'
                }
            }
        }
    }
}

I get the following error:

java.lang.NoSuchMethodError: No such DSL method 'cucumber' found among steps [archive, ..., scm]

could you please tell me if this is a bug or wrong configuration?

**Comment by damianszczepanik** [comment]
Support for pipeline has been added #139  but not released yet. Should be available shortly.
