### ISSUE TITLE
DSL problem when using it in Jenkins piple line

### ISSUE THREAD

**Issue by e2tony2000** [jenkinsci/cucumber-reports-plugin#163]
following the ReadMe, I am trying to add the cucumber report. However, I got the error java.lang.NoSuchMethodError: No such DSL method 'cucumber' found among steps. What the right way to add the report?

The way I use the plugin is
1. install the plugin
2. in my pipeline file
stages {
        stage('Build') {
            steps {
                //run your build
                sh " mvn clean install -pl testModule"
            }
            post {
                always {
                    cucumber '**/*.json'
                }
            }
        }
    }

**Comment by kapoorlakshya** [comment]
Pipeline support is not available until v3.9.0. See https://github.com/jenkinsci/cucumber-reports-plugin/issues/160

@damianszczepanik Maybe the README should be updated with this info, and possibly include a tentative release date for v3.9.0?

**Comment by e2tony2000** [comment]
may I ask when the v3.9.0 will be released please?

**Comment by damianszczepanik** [comment]
Now.

**Comment by damianszczepanik** [comment]
REademe updated requested #139
