### ISSUE TITLE
Merge/Consolidate Same Feature name Scenario results in report.

### ISSUE THREAD

**Issue by prayagvakharia** [jenkinsci/cucumber-reports-plugin#172]
I have multiple feature file with same feature name.  So When report generated it will display multiple row for same feature name.

Example:
File1: test1.feature
```
Feature: testing 
    Scenario: scenario 1
```
File2: test2.feature
```
Feature: testing 
    Scenario: scenario 2
```

Report should display one feature entry in feature table. but it display 2 features. Is there any way to consolidate same feature name data.

**Comment by damianszczepanik** [comment]
Report merges features with the same ids. If you want to keep them separately you need to make sure they have different ids

**Comment by prayagvakharia** [comment]
@damianszczepanik  
Where I can set ids in features? I want to set same id for multiple feature file so that all scenario consolidate in one feature.

**Comment by damianszczepanik** [comment]
This is not the scope of the report but rather cucumber

**Comment by prayagvakharia** [comment]
Can you give some idea about which id(JSON Key) will be use in JSON for merge same ids feature.

**Comment by damianszczepanik** [comment]
My mistake. Features are added as they are parsed and displayed one by one. I can handle this and merge them into one IF ONLY there is rule for that that works foe everyone

**Comment by prayagvakharia** [comment]
Thanks, 
Right now i just wrote one python script parser which will merge same feature name element. So now everyone is works as per expected. :)

**Comment by damianszczepanik** [comment]
Looks like duplicate of https://github.com/jenkinsci/cucumber-reports-plugin/pull/98
