### ISSUE TITLE
File exclusion pattern

### ISSUE THREAD

**Issue by JMVM** [jenkinsci/cucumber-reports-plugin#173]
Hi there,

Recently I found plugin is copying JSON files **from workspace to .cache**, getting mocked data in **JSON file format** in directories such as **src/test/resources**. So I've tried adding a file exclusion pattern in plugin configuration, but it looks like not working (for example, **cucumber/src/test/resources/**.json**, where).

Any idea? 

Do you have any example to know how works? Maybe I set a wrong pattern.

At the moment, I created a bash script to clean in automation way, but I would prefer plugin configuration.

Thanks

**Comment by damianszczepanik** [comment]
This mechanism is used also by other plugins so there is no mystery about it but his may be helpful https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java#L282
