### ISSUE TITLE
Pipeline step fails build if no test results found

### ISSUE THREAD

**Issue by aedwards-act** [jenkinsci/cucumber-reports-plugin#178]
The step does not throw an exception, but the build status gets set to failed if there are no cucumber reports available and the pipeline resumes.

Output from cucumber report is:

[CucumberReport] Preparing Cucumber Reports
[CucumberReport] JSON report directory is ""
[CucumberReport] Copied 0 json files from workspace "/jenkins/workspace/..." to reports directory "/jenkins/workspace/..."
[CucumberReport] Processing 0 json files:
[CucumberReport] Missing report result - report was not successfully completed
[CucumberReport] Build status is changed to NATURAL

'Build status is changed to NATURAL' seems odd.

I suspect the issue is here:
https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java#L55
```
private String buildStatus = SortingMethod.NATURAL.name();
...
if (buildStatus != null) {
                log(listener, "Build status is changed to " + buildStatus.toString());
                build.setResult(Result.fromString(buildStatus));
            } else {
                log(listener, "Build status is left unchanged");
            }
```

unknown status will get set as  FAILURE in jenkins
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Result.java#L150-L155
```
public static @Nonnull Result fromString(@Nonnull String s) {
        for (Result r : all)
            if (s.equalsIgnoreCase(r.name))
                return r;
        return FAILURE;
    }
```

I suspect this change
https://github.com/jenkinsci/cucumber-reports-plugin/commit/715d2c22512f9abee28a6f4fdecaa09ae49cf90b
for this issue
https://github.com/jenkinsci/cucumber-reports-plugin/issues/141
had meant to set the 'sortingMethod' to 'SortingMethod.NATURAL.name()', not the build status.

**Comment by aedwards-act** [comment]
Noticed in version 3.10.1

**Comment by damianszczepanik** [comment]
Indeed! Can you prepare fix in single commit and resolve conflict?

**Comment by aedwards-act** [comment]
@damianszczepanik I've altered https://github.com/jenkinsci/cucumber-reports-plugin/pull/179 to be a single commit. The CI build is failing due to missing JAVA_HOME variable.

https://travis-ci.org/jenkinsci/cucumber-reports-plugin/jobs/273208931

**Comment by damianszczepanik** [comment]
Released
