### ISSUE TITLE
Plugin does not seems to be working

### ISSUE THREAD

**Issue by iam404** [jenkinsci/cucumber-reports-plugin#181]
Jenkin Version:- 2.63
Cucumber reports:- 3.10.2
Reports generated does not seems to be valid. I am getting below html page:-

<img width="1214" alt="screen shot 2017-09-11 at 5 06 46 pm" src="https://user-images.githubusercontent.com/11330522/30272906-4bf261d0-9714-11e7-8490-d7e1a8448562.png">

Although I have another jenkins setup with Jenkins version 2.25 and plugin version 3.1.0. And plugin seems to be working fine there.

**Comment by damianszczepanik** [comment]
Provide build logs and JSON file with the report. The most recent version should work fine
