### ISSUE TITLE
Improvement: include plugin version in console output

### ISSUE THREAD

**Issue by msymons** [jenkinsci/cucumber-reports-plugin#183]
It would be helpful if the cucumber-reports-plugin version were included in the console output.  Thus, one might navigate from "build x console output" to "build x+ 1 console output" and confirm, for instance, that build status has changed from FAIL to SUCCESS - with a change in plugin version reflected in the output.

**Comment by damianszczepanik** [comment]
You can prepare PR for this. I will accept it.

**Comment by msymons** [comment]
@damianszczepanik, this improvement has now been successfully implemented.  Thanks!

I am guessing this was done by #243.

From v3.19.1 console:
```
[CucumberReport] Preparing Cucumber Reports
```
From v3.20.0:
```
[CucumberReport] Preparing Cucumber Reports: 3.20.0
```
