### ISSUE TITLE
Improvement: Additional Logging for File Processing

### ISSUE THREAD

**Issue by msymons** [jenkinsci/cucumber-reports-plugin#186]
Console output for Cucumber Reports plugin v3.10.3 looks like:

```
[CucumberReport] Preparing Cucumber Reports
[CucumberReport] JSON report directory is ""
[CucumberReport] Copied 12 json files from workspace "/var/jenkins/workspace/xxxx" to reports directory "/var/lib/jenkins/jobs/xxxx/branches/master/builds/59/cucumber-html-reports/.cache"
[CucumberReport] Processing 1 json files:
[CucumberReport] /var/lib/jenkins/jobs/xxxx/branches/master/builds/59/cucumber-html-reports/.cache/xxxx-integration/target/cucumber_client.json
```
A couple of improvements that would help with problem diagnosis:
1) List the individual json files that are copied (including path info).  This would help one diagnose (say) that the report directory is incorrect when none of the copied json files resemble the cucumber report filenames that you are expecting.
2) Include the "file include pattern" in the "Processing x json files" line.  This would allow an easy comparison between the list of files copied (see above) and the pattern so that one could spot that (say) cucumber-client.json does not match the pattern "**/cucumber.json"

I am not a developer so I am afraid that I am not able to submit a pull request myself.

**Comment by damianszczepanik** [comment]
Last line is the answer for you first request and for the second is what you can check in job configuration so there is no need to repeat it.

**Comment by msymons** [comment]
To explain a bit further....

* Having list of files visible on same output as a reminder of the patttern that the files are being matched against makes it easier to perform a comparison and thus spot why things went wrong.
* It is common (at least in our environment) to to have permissions to view console output but **not** have permission to view (edit) configuration...whilst the person viewing the console output is still expected to be able to correctly diagnose the problem so that they know who to tell to fix it.
* The configuration might not be visible at all within Jenkins when Cucumber is being used in a pipeline.... thus making it quite important in the console log.

**Comment by damianszczepanik** [comment]
Having multiple logs about same is redundant for me. I prefer to have one good log. If you can't modify job configuration then log is useless for you as even you see the problem you won't be able to fix it.

Recommend this https://wiki.jenkins.io/display/JENKINS/Read-only+configurations+plugin

**Comment by nsidhaye** [comment]
@msymons : Probably you are using maven project. Try to use freestyle project.

@damianszczepanik : This problem is persisting...
