### ISSUE TITLE
Publish Cucumber test results report

### ISSUE THREAD

**Issue by YugandharBandari** [jenkinsci/cucumber-reports-plugin#194]
Hi Team,

I'm not getting any charts, statistics as mentioned in below link and also not getting any Cucumber JVM reports link in Post Build Actions section when I used cucumber reports plugin in Jenkins. can you please help me.

I selected 'Publish Cucumber test results report' option from Post Build section, then seeing cucumber test results but want charts and statistics for more clarity

https://wiki.jenkins.io/display/JENKINS/Cucumber+Reports+Plugin

I'm using below mentioned softwares to generate Cucumber reports

Jenkins 2.86
Cucumner reports plugin 3.11
JUnit 4.12
Note :; using cucumber.json file to generate reports.

Thanks,
Yugi

**Comment by damianszczepanik** [comment]
Provide logs from the plugin so I can take a look.

Look for such message prefix https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java#L88

**Comment by YugandharBandari** [comment]
After I re-installed the Jenkins. it was working fine. Thanks
