### ISSUE TITLE
[CucumberReport] Missing report result - report was not successfully completed

### ISSUE THREAD

**Issue by shubhamj-cuelogic** [jenkinsci/cucumber-reports-plugin#195]
I have created a Java-Selenium-Cucumber-Maven based project everything is working fine except the advance reporting.

Below is my TestRunner Code:

import org.junit.runner.RunWith;

import automationframework.AppDriver;
import automationframework.AutomationLog;
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
import net.masterthought.cucumber.ReportParser;
import net.masterthought.cucumber.Reportable;
import pageobjects.Page;
 
//@RunWith(Cucumber.class)
@ExtendedCucumberOptions(
		jsonReport = "target/cucumber.json",
		retryCount = 3,
		detailedReport = true,
		detailedAggregatedReport = true,
		overviewReport = true,
		toPDF = true,
		outputFolder = "target"
		)
@CucumberOptions(
		features = "Feature"
		,glue={"stepDefinition"}
		,plugin = { "pretty", "html:target/site/cucumber-pretty", "json:target/cucumber.json","junit:target/cucumber.xml"}
//		,monochrome = false
//		,dryRun = true
		)
 
@RunWith(ExtendedCucumberRunner.class)
public class TestRunner {
    @BeforeSuite
    public static void setUp() {
    	AutomationLog.info("In Before Suite");
    }
    @AfterSuite
    public static void tearDown() {
        System.out.println("In After Suite");
        AppDriver.clearBrowserContext(Page.driver);
        AutomationLog.info("Quiting Webdriver Instances");
        
        
/*        CucumberUsageReporting report = new CucumberUsageReporting();
        report.setOutputDirectory("target");
        report.setJsonUsageFile("./src/test/resources/cucumber-usage.json");
        report.executeReport();*/
        
        File reportOutputDirectory = new File("reports");
        List<String> jsonFiles = new ArrayList<>();
        jsonFiles.add("cucumber-report-1.json");
        jsonFiles.add("cucumber-report-2.json");

        String buildNumber = "1";
        String projectName = "MavenJenkins";
        boolean runWithJenkins = false;
        boolean parallelTesting = false;

        Configuration configuration = new Configuration(reportOutputDirectory, projectName);
        // optional configuration
        //configuration.setParallelTesting(parallelTesting);
        configuration.setRunWithJenkins(runWithJenkins);
        configuration.setBuildNumber(buildNumber);
        // addidtional metadata presented on main page
        configuration.addClassifications("Platform", "Windows");
        configuration.addClassifications("Browser", "Firefox");
        configuration.addClassifications("Branch", "release/1.0");

        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
        Reportable result = reportBuilder.generateReports();
        // and here validate 'result' to decide what to do
        // if report has failed features, undefined steps etc
    }
}

In Jenkins in configure I have mentioned two details

Report Path -> reports
File Include Pattern -> target/cucumber.json

Getting error in Jenkins

> [CucumberReport] Preparing Cucumber Reports
> [CucumberReport] JSON report directory is "reports"
> [CucumberReport] Copied 0 json files from workspace "D:\Jenkins\Workspace\workspace\MavenJenkinsCI\reports" to reports directory "D:\Jenkins\Workspace\jobs\MavenJenkinsCI\builds\32\cucumber-html-reports\.cache"
> [CucumberReport] Processing 0 json files:
> [CucumberReport] Missing report result - report was not successfully completed

Getting This error on report

> Error
> Something went wrong with project MavenJenkinsCI, build 32
> 
> net.masterthought.cucumber.ValidationException: None report file was added!
> 	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:52)
> 	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:87)
> 	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:284)
> 	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:219)
> 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
> 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
> 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
> 	at hudson.model.Run.execute(Run.java:1764)
> 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
> 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 	at hudson.model.Executor.run(Executor.java:419)
> Trying to generate report from following files. Make sure they are valid cucumber report files:

If I am missing anything or you need any more specific information regarding same please let me know

**Comment by damianszczepanik** [comment]
If you are sure JSONs with report are present in workspace then I believe you provided wrong or to restrictive pattern for file and then it could not match any file

**Comment by shubhamj-cuelogic** [comment]
I have used maven plugin with cucumber dependencies and it is now working without any code

**Comment by senf-f** [comment]
I also had this issue - "[Missing report result](https://stackoverflow.com/questions/56024457/missing-report-result-report-was-not-successfully-completed-with-cucumberrepor)". 

The next day, after restarting the computer, the problem is gone and I'm unable to reproduce the problem.

**Comment by karikalanbalachandran** [comment]
> I have used maven plugin with cucumber dependencies and it is now working without any code

Can u help me on this Error. I am Facing Same Error but I am Using TestNG not Junit Runner
