### ISSUE TITLE
Feature file names, Tags, Steps are not displaying in order

### ISSUE THREAD

**Issue by YugandharBandari** [jenkinsci/cucumber-reports-plugin#198]
Looks like currently Feature file names, Tags, Steps are displaying in alphabetical order in cumber reports. is it possible to display Feature file names, Tags ans Steps how its in JSON file.

**Comment by damianszczepanik** [comment]
Upgrade the plugin and check settings

**Comment by YugandharBandari** [comment]
Damianszczepanik - Thanks for your suggestion. After upgrade the Plugin, Feature files are displaying as per test execution order but inside steps are displaying in alphabetical order. could you please help me how to fix this issue.
