### ISSUE TITLE
How to set Over all Cucumber Status as Passed when it has Pending Status

### ISSUE THREAD

**Issue by kalyankp** [jenkinsci/cucumber-reports-plugin#199]
My report has combination of Pending Status and Passed Status. I want over all Status to be Passed.
I am using JenkinFile to configure CucumberReportPublisher and I am using Multi Branch pipeline type. I am trying to pass parameter as pendingFails: false, but still my over all status is failed. Please kindly help.

Note : - I know the fact that it can be configured from the Jenkin Configure -> Post build Actions, but I want to pass it as a parameter from the Jenkins file.

**Comment by damianszczepanik** [comment]
Same as https://github.com/jenkinsci/cucumber-reports-plugin/issues/129

**Comment by SaikatDEV** [comment]
@damianszczepanik Have you updated this as @pending tag should not cause Build failure? I dont want my Build also fail for @pending scenarios

**Comment by damianszczepanik** [comment]
You can configure what you want. Czech readme
