### ISSUE TITLE
Error: IllegalArgumentException when build got killed by timeout

### ISSUE THREAD

**Issue by huydn234** [jenkinsci/cucumber-reports-plugin#20]
Hi, we are setting 20 minutes as timeout for a TEST job in our jenkins, and we run test in parallel using parallel_tests gem. However, when build got killed by timeout, the Cucumber Report can render a final report as usual due to this error:
![2016-02-02_1654](https://cloud.githubusercontent.com/assets/8285840/12745867/20208b78-c9ce-11e5-9112-c30cefcdb898.png)
I have checked the report json and find that the report4.json is corrupted and got 0K size.
So can we ignore the corrupted files and render reports based on other files?

**Comment by damianszczepanik** [comment]
Attach json file so i can take a look
