### ISSUE TITLE
Unable to generate report from large json file

### ISSUE THREAD

**Issue by aliusmiles** [jenkinsci/cucumber-reports-plugin#202]
Jenkins job hangs at generating cucumber report, at step `[CucumberReport] Processing 1 json files:`. Even after few hours report is still being generated, so job could only be terminated.

File size is 1.1M, 35135 lines. Unfortunately I cannot provide file itself since it contains sensitive info, but please let me know if I could provide any other information. 

Jenkins: 2.73.3
cucumber-reports-plugin: 3.12.1

I've thought about generating separate reports per cucumber tags, but it doesn't seems to be possible in scope of one job? Would be nice to be able to generate one report per pipeline's step, for example.

**Comment by damianszczepanik** [comment]
You can use https://github.com/damianszczepanik/silencio/ to remove sensitive data and then attach report.

**Comment by aliusmiles** [comment]
Here it is.
[cucumber-report.json.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/1532022/cucumber-report.json.zip)

**Comment by damianszczepanik** [comment]
I had no problem with generating the report - check Jenkins configuration (memory?)

**Comment by aliusmiles** [comment]
Thanks a lot! My Jenkins indeed was set to default 256m, after increasing to 1GB report was generated without any issues.
