### ISSUE TITLE
Need a max duration column in the Steps tab 

### ISSUE THREAD

**Issue by loman74** [jenkinsci/cucumber-reports-plugin#203]
Currently, I see Average duration column in the Steps tab of the Cucumber Jenkins report. It would be helpful to have a maximum and minimum duration column as well.  These data points can be very helpful to understand performance of the application under test.
![cucumberjenkinsreportpluginrequest_maxdurationstep](https://user-images.githubusercontent.com/358915/33557530-7de0517c-d8d5-11e7-9eed-0d0ee6b54173.JPG)

**Comment by loman74** [comment]
I started looking for a way to fork and contribute,  but am unable to find the .js and style files under the webapp folder. Please advise.

**Comment by damianszczepanik** [comment]
You need to prepare change for https://github.com/damianszczepanik/cucumber-reporting as this project is only Jenkins plugin wrapper for the standalone report.
