### ISSUE TITLE
[Feature Request] Link to latest result in side panel of pipeline job

### ISSUE THREAD

**Issue by waeller** [jenkinsci/cucumber-reports-plugin#215]
Hi,

When we use the cucumber-reports plugin in free-style jobs, there is always a link to the cucumber results in the side panel on the job's page and on the build's page. However, in pipeline jobs (at least in multibranch pipeline jobs), we get a link to the results only on the build's page. It would be great to have a link to the latest results in the side panel of he job's page, too. Would that be possible?

Best Regards,
Juergen.

**Comment by damianszczepanik** [comment]
Agree, I've spent some time trying to figure out it and found that this problem happens for most plugins. If you can prepare Pr for this a good reference fix I will be happy to accept this change!

**Comment by waeller** [comment]
I will try, but I've no experience in Jenkins plugin programming yet. So I would appreciate any hint about what could be changed to accomplish this ;-)

**Comment by manjunathsoftwares** [comment]
i was looking for cucumber reports in jenkins Job level, but its only visible in Build level not at job level.
I was checking https://jenkins.io/blog/2016/05/25/update-plugin-for-pipeline/
not sure how to get my cucumber reports in Jenkins Job page.
Could you please help.

**Comment by damianszczepanik** [comment]
It's already done as you see
