### ISSUE TITLE
the report does not happened if the build fail.

### ISSUE THREAD

**Issue by mlotfi2005** [jenkinsci/cucumber-reports-plugin#216]
in the configure job, when I run from the Execute Shell :
cucumber features\\brc_viewer_assign_user.feature -f pretty -f json -o cucumber.json

if one step of the scenarios fail

the next line the Execute Shell :
cp cucumber.json C:\\Users\\alotfi2\\.jenkins\\workspace\\BRCtesting

does not work, it is skipped, so there is no cucumber report.

I thought that the report should work for failed and passed steps, but in my case if all pass it will generate the cucumber report, if not it will not, please direct me if I am missing something.
Thanks,

**Comment by damianszczepanik** [comment]
-o means that the json file is the output, this library needs it as the input

**Comment by mlotfi2005** [comment]
Can you please show me what to do? 
Thanks.

**Comment by damianszczepanik** [comment]
Check with the documentation of the tool you use to generate cucumber.json file not the tool which needs this file as the input
