### ISSUE TITLE
How to attach images to the report?

### ISSUE THREAD

**Issue by rahulkulkarniyahoo** [jenkinsci/cucumber-reports-plugin#218]
Can you please provide documentation on how to attach images to the Cucumber Reports on Jenkins ?

Currently I have kept my code to capture screenshot when scenario fails

public void tearDown(Scenario scenario) {

        if (scenario.isFailed()) {
            scenario.embed(driver.getScreenshotAs(OutputType.BYTES), "image/png");
            System.out.println("scenario.getId() = " + scenario.getId());
            System.out.println("scenario.getName() = " + scenario.getName());
            System.out.println("scenario.getSourceTagNames() = " + scenario.getSourceTagNames());
            System.out.println("scenario.getStatus() = " + scenario.getStatus());
        
driver.quit();
}
}

My Runner class:
@RunWith(Cucumber.class)
@CucumberOptions(
        features = "src/test/resources/features/",
        plugin = {
                "pretty", "html:target/cucumber-html-reports",
                "json:target/cucumber.json",
        "rerun:target/rerun.txt"}, //Creates a text file with failed scenarios
   //     format="json:target/cucumber.json",
        tags = "@launch")

public class RunnerTest {

}

**Comment by damianszczepanik** [comment]
Check with the documentation of the cucumber implementation you use, probably cucumber-jvm
