### ISSUE TITLE
Download full report

### ISSUE THREAD

**Issue by kriazhev** [jenkinsci/cucumber-reports-plugin#219]
Hi, can't figure out how to download html report in order to view it online, (We need to store test execution results in specific system). Thank you in advance

**Comment by damianszczepanik** [comment]
It is not supported. You might take a look at https://wiki.jenkins.io/display/JENKINS/HTML+Publisher+Plugin but I'm not sure if this will help. You can prepare PR to zip the report which you can download later.

**Comment by felipecrs** [comment]
@damianszczepanik, wouldn't it be nice (and possible) to add a feature/button that would zip the /var/jenkins-home/jobs/my-job/builds/123/cucumber-reports on the fly and serve to the user?

**Comment by damianszczepanik** [comment]
https://www.jenkins.io/doc/pipeline/steps/pipeline-utility-steps/#zip-create-zip-file

**Comment by felipecrs** [comment]
@damianszczepanik, thank you, but that's not what I was looking for. Let me clarify:

One can `zip` the report in the workspace and `archiveArtifact` it, which can later be downloaded from the Jenkins UI.

However, I'm concerned that this would consume twice the amount (discarding compression) of the disk space in the Jenkins master, considering that the Cucumber reports would also be stored by the Cucumber Reports plugin.

If the Cucumber Reports could provide a button to download the raw report files, we would avoid having this extra `archiveArtifact` step in the pipeline, and most importantly, avoid duplicating the files and thus saving space in the Jenkins master.

**Comment by damianszczepanik** [comment]
I can make some changes to improve archiving process but this plugin won't support compressing reports itself

**Comment by felipecrs** [comment]
What do you have in mind? Exposing the Cucumber files as regular archives in Jenkins?
