### ISSUE TITLE
Cannot locate test scenarios that use tags in scenarios outline examples

### ISSUE THREAD

**Issue by ngwinghing** [jenkinsci/cucumber-reports-plugin#222]
Dear guys,

## Bug Background
I'm trying to tag my scenarios using scenarios outline examples, and each unique test cases will have its own unique id tag, so that when one test case fail, I can use the unique id tag to locate them and run them with the tag again.
For example:
```
@maintest
Scenario Outline: eating 
	Given there are <start> cucumbers 
	When I eat <eat> cucumbers 
	Then I should have <left> cucumbers 
	
	@test1 @lowprioritytest 
	Examples: 
	| start | eat | left |
	|  12   |  5  |  7   |
	
	@test2 @highprioritytest 
	Examples: 
	| start | eat | left |
	|  20   |  5  |  15  |
	
@highprioritytest 
Scenario Outline: drinking 
	Given there are <start> cucumbers 
	When I drink <drink> cucumbers 
	Then I should have <left> cucumbers 
	
	@test3 
	Examples: 
	| start | drink | left |
	|  8    |  5  	|  3   |
```
## Bug Reproduce Steps

1. I run a test with the tags "@highprioritytest"
2. Open the generated report: /cucumber-html-reports/overview-tags.html

## Expected Result
In the jenkins report, I would like to show all tags in that each unique examples and test cases.

- i.e. Show @test3 , @test2, @highprioritytest

## Actual Result
In the jenkins report, it cannot show the test scenarios that use tags in scenarios outline examples
- i.e. Show only @test3, @highprioritytest
missing @test2

Please help to look into that, do I miss anything?
The test  @test2 is ran, but it is not showing in the report only.
you can go to /consoleText , to check actually the console has ran the    
 | start | eat | left |
    |  20   |  5  |  15  |
    |  33   |  4  |  5   |
example.

Thank you guys for helping!! 

Best Regards,
Wing

**Comment by damianszczepanik** [comment]
So the tags are not displayed for scenario outlines? If so attach JSON file so I can check what is going on

**Comment by ngwinghing** [comment]
Hello, could I have your Email and send via email? The file includes company's properties. Thank you very much.

**Comment by ngwinghing** [comment]
Example:
[ngwinghing-report.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/1770363/ngwinghing-report.zip)

**Comment by damianszczepanik** [comment]
There is no difference between JSON and HTML report (this is responsibility of this plugin) so there is no issue. I take JSON as the input not output and HTML is same as JSON.
You probably have problem with cucumber which you use for test, not the plugin which you use for reporting
