### ISSUE TITLE
Reports from son files are not combined properly

### ISSUE THREAD

**Issue by NahidSiddiqui** [jenkinsci/cucumber-reports-plugin#224]
Due to lack of reliability I have to rerun automated tests that have failed on the first run, so after the execution in the Jenkins pipeline I end up with two Json file one will all the scenarios and one with only the scenarios that have been rerun. When the cucumber json reports plugin combine these two the resultant report contains both the failed scenarios and passed scenarios. This is not helpful since in the report you see both the fail and passed scenarios, thus duplicates.

Please refer to the report output below:

![screen shot 2018-02-26 at 11 30 11](https://user-images.githubusercontent.com/16851122/36668221-7e64e9b4-1ae8-11e8-810b-f545d16c04ec.png)

As you can see Cancel item feature run has been repeated the second time, yet the previous failed run is still there.

**Comment by damianszczepanik** [comment]
You should modify or merge JSON reports according to your needs. This won't be a responsible of the plugin that generates report
