### ISSUE TITLE
scenrios executed  in 6 mins but the json report generation is taking 38 mins to generate for tag level execution

### ISSUE THREAD

**Issue by vignesh5225** [jenkinsci/cucumber-reports-plugin#226]
Hi,

The cucumber reporting plugin for jenkins is taking unsually time of 38 mins to generate the reports , but it takes less than a min  in eclipse local machine, please can some one assist on this issue @damianszczepanik - please help me on this

**Comment by damianszczepanik** [comment]
Which version of the plugin are you using?

**Comment by vishnucr09** [comment]
We are from the same team, :)

Have attached screenshot of cucumber plugins used in Jenkins. 

Kindly assist. 

![capture](https://user-images.githubusercontent.com/22572124/37471341-6d1cd6b8-2861-11e8-8a35-f41fe548161a.PNG)

**Comment by vignesh5225** [comment]
@damianszczepanik , we are using cucumber plugins are mentioned above

**Comment by damianszczepanik** [comment]
Then show me the JSON file. There is probably problem with performance if you have many labels

**Comment by vignesh5225** [comment]
[cucumber.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/1823851/cucumber.zip)
added the JSON file ,please have a look and  assist on this

**Comment by vignesh5225** [comment]
@damianszczepanik,any update on this issue?

**Comment by damianszczepanik** [comment]
It takes 1-3 secs to generate the report so check how much memory or CPU
