### ISSUE TITLE
Cucumber's Background keyword forced the results not to be displayed

### ISSUE THREAD

**Issue by mkelliher3** [jenkinsci/cucumber-reports-plugin#229]
Given I am using Background keyword to keep feature files as short as possible
When I run the tests on Jenkins
Then I see the results of the feature files (without using Background keyword)
But I do not see the results of one feature file that contains Background keyword

Comments: 
I'm using the latest version of cucumber-reports-plugins and I'm blocked from using 'Background' keyword on feature files. I am so eager to show to my colleagues on my work of reducing long feature files into shortest files as possible so this is the main blocker. 

Thanks.

**Comment by damianszczepanik** [comment]
Show me JSON file and the screenshot describing the problem

**Comment by mkelliher3** [comment]
[Tests With and Without Background Keyword.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/1875298/Tests.With.and.Without.Background.Keyword.zip)

I added two sets of screenshot and .json files to compare both with and without using Background keyword. 

You will see that Exchange_5_Contact_Details_I_Have_A_Box_page_check file is missing in the cucumber report when it's using Background keyword. 

I'm looking forward to hear any solution with this issue. 

Thanks.

**Comment by damianszczepanik** [comment]
The file 'with background' has no background or I misunderstood the problem. Provide json that has only one feature and scenario that are problematic

**Comment by mkelliher3** [comment]
Given I am running a feature file that DOESN'T use Background keyword
Then I see the results in Cucumber reports (PASSED)
![a_feature_file_was_not_using_background_keyword_passed](https://user-images.githubusercontent.com/18468205/38383984-dab705fe-3905-11e8-9399-7d9b6f65b72d.PNG)

Given I am running a feature file that use Background keyword
Then I see the error in Cucumber reports (FAILED)
![a_feature_file_was_using_background_keyword_failed](https://user-images.githubusercontent.com/18468205/38383995-e01f25a8-3905-11e8-9024-45cdf65b53fd.PNG)

**Comment by damianszczepanik** [comment]
and JSON file please

**Comment by mkelliher3** [comment]
I ran two feature files, Exchange_4_Activity (this does NOT use Background keyword) and Exchange_5_Contact_Details (this USES Background keyword), to show the difference between them. 

![two_feature_files](https://user-images.githubusercontent.com/18468205/38509796-dca5beba-3c1a-11e8-9b91-c180d9071c33.PNG)

Just Exchange_4_Activity is shown on Cucumber HTML Report and in JSON report. However, Exchange_5_Contact_Details was run but it's not shown in Cucumber HTML Report nor JSON report

![cucumber_reports_showing_just_one_feature_file](https://user-images.githubusercontent.com/18468205/38509915-3605ac86-3c1b-11e8-8b90-73b2c76e3c0b.PNG)

[cucumber-reports.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/1890778/cucumber-reports.zip)

**Comment by mkelliher3** [comment]
Some of my tests were very long, so I use Background keyword to reduce the duplication. So I don't want to read same steps 5 times. It would make my job a lot boring. It would also make maintaining tests a lot easier, e.g. adding/removing a step once, rather than 5-10 times. 

If one Background step failed intermittently, I won't want to see the results showing that all 5 scenarios had failed. I would prefer to have Background steps as a part of test. If I want to set up the environment, I would use just Given keyword. 

Thank you for your help. I'm looking forward to the next version in the near future.

**Comment by damianszczepanik** [comment]
Then make sure that what you want is what JSON has. Report does not modify statuses but rather it takes as it is..

I will consider once more time this request when new major version is published what does not happen in near future.

**Comment by lajayis** [comment]
In reference to mkelliher3 comment, I also observed that, Background steps are being treated as failed tests despite the fact that all the scenario steps passed as can be seen in the attached image below:

<img width="1172" alt="screenshot_jenkins" src="https://user-images.githubusercontent.com/43614501/48014262-30df2900-e11e-11e8-9753-ab1789423445.png">


Could there be a work around or an expected newer version that will address this problem?

**Comment by damianszczepanik** [comment]
Guys, logically if the background which is precondition for the test, is marked as failure then how the test could be marked as passed? Then IMO the background is not the real pre-condition or it the test result does not care about the background thus there is something wrong.

Give me the idea how this makes sense otherwise I don't think you are focusing on the real problem

**Comment by lajayis** [comment]
Sorry Damianszczepa, thank you for getting back, I've just read through your comment. Actually, the background is not seen as failed but, it is being seen as "Undefined" thus, the feature status; as can be seen in my previous post is set as "Failed".

**Comment by lajayis** [comment]
> Guys, logically if the background which is precondition for the test, is marked as failure then how the test could be marked as passed? Then IMO the background is not the real pre-condition or it the test result does not care about the background thus there is something wrong.
> 
> Give me the idea how this makes sense otherwise I don't think you are focusing on the real problem

Sorry Damianszczepa, thank you for getting back, I've just read through your comment. Actually, the background is not seen as failed but, it is being seen as "Undefined" thus, the feature status; as can be seen in my previous post is set as "Failed". With due regards, it appears, the reason the feature status is set to "failed" (please refer to my previous post with the image) is because the background steps (which are okay) are seen as undefined. I will appreciate it, if this can be looked into.
