### ISSUE TITLE
Is possible to disabled the bootstrap style?

### ISSUE THREAD

**Issue by djom20** [jenkinsci/cucumber-reports-plugin#232]
I'm needed print the report with all the colors but currently the bootstraps have print style to disable the styles, so Is there any way to remove or replace them?

![image](https://user-images.githubusercontent.com/1834808/39451433-48f0f02e-4c94-11e8-8f38-f9a0cfbe39cd.png)

Thanks so much.

**Comment by damianszczepanik** [comment]
I don't have plan for that and I did not investigate such request so far. If you can I  will be happy to accept it as PR
