### ISSUE TITLE
Error - @RunWith(ExtendedCucumber.class)

### ISSUE THREAD

**Issue by bangkar** [jenkinsci/cucumber-reports-plugin#233]
Hi,
I have been using Cucumber.Report 1.7 for a while.  Now I am attempting to upgrade to the latest version - 1.3.2.  After update dependency, I am a getting error in the runner class -> @RunWith(ExtendedCucumber.class).  The error states that "import com.github.mkolisnyk.cucumber.runner.ExtendedCucumber;" cannot be resolved.

What is the solution?  Thanks

pom.xml content:
<cucumber.report>1.3.2</cucumber.report>
<dependency>
	<groupId>com.github.mkolisnyk</groupId>
	<artifactId>cucumber-report-generator</artifactId>
	<version>${cucumber.report}</version>
</dependency>

runner class contents:
import org.junit.runner.RunWith;
import com.github.mkolisnyk.cucumber.runner.ExtendedCucumber;
import com.github.mkolisnyk.cucumber.runner.ExtendedCucumberOptions;
import cucumber.api.CucumberOptions;

@RunWith(ExtendedCucumber.class)
@ExtendedCucumberOptions(
	jsonReport = "target/test-reports/Jason/something.jason",
        stuff....
	outputFolder = "target/test-reports/somethig"
)
@CucumberOptions(  
	glue     = { "classpath:abc/cucumber/framework" },
	features = { "src/test/resources/cucumber/somethingTest.feature" }, 
	format   = { "json:target/test-reports/Jason/somethingTestsResult.jason" }, 		
					
	tags     = { "~@ignore" }
)

public class somethingTests_IT {

}

**Comment by damianszczepanik** [comment]
Not related to this project
