### ISSUE TITLE
cucumber report publishing does not support Jenkins job run with concurrent builds

### ISSUE THREAD

**Issue by gwsu2008** [jenkinsci/cucumber-reports-plugin#235]
Hi,

I ran into an issue with cucumber report publishing just waiting for Jenkins job finish running before results are published. This only occurred when Jenkins job run with concurrent builds. For example, I have test job that run some test case and publish cucumber report. Run 1 takes 10 mins to finish and run 2 takes 5 mins to finish. While both jobs are running in parallel and run 2 is finished the cucumber report publish step just hanging in post build waiting for run 1 to finish.  This looks like cucumber reports publish always stay in the order of build execution. 

Thanks

**Comment by damianszczepanik** [comment]
I need more details and steps to reproduce as this seems to be quite complex to confirm and fix

**Comment by gwsu2008** [comment]
Hi,

It's really easy to reproduce. All you need to some existing test result json, put them in on a web server. Then create a jenkins job down them and touch file to update the time stamp and then sleep some second and publish cucumber results. Make sure enabled [Execute concurrent builds if necessary] for the jenkins job.

See attached screen capture. The time stamp on the Run2 clearly show it waited for Run1 to finish. There's no other post build step would cause the wait only the cucumber report publishing 

Thanks

<img width="968" alt="job-config" src="https://user-images.githubusercontent.com/11874389/40251726-06855b36-5a8f-11e8-8608-e34095e7ff19.png">
<img width="961" alt="run2-sleep-5" src="https://user-images.githubusercontent.com/11874389/40251727-069df9a2-5a8f-11e8-834a-e3ca005b66e2.png">
<img width="1030" alt="run1-sleep-90" src="https://user-images.githubusercontent.com/11874389/40251728-06b4bcaa-5a8f-11e8-96a0-5a8961f5636c.png">

**Comment by damianszczepanik** [comment]
Sound like some Jenkins feature which might not be implemented out of the box. Deeper analyze is needed to check what is going on here

**Comment by damianszczepanik** [comment]
OK, there is no support for parallel builds and I don't have plan to support it
