### ISSUE TITLE
Two cucubmer reports from Jenkins pipeline project with parallel testing stage

### ISSUE THREAD

**Issue by daveysa** [jenkinsci/cucumber-reports-plugin#237]
Current I have the pipeline job running the system test  stage and can successfully get the "cucubmer reports" tag show on Jenkins. 

sample code below:
`
      stage ('System Testing'){
                    try {
                        sh './scripts/run-system-tests.sh'
                    } finally {
                        sh './scripts/clean-system-test-env.sh'
                    cucumber([
                                      jsonReportDirectory: './e2e-tests/features/output-files/reports',
                                      fileIncludePattern: 'reports.json',
                                      buildStatus: 'UNSTABLE'
                    ])
                    }
       }
 `

Now I need to test on different environemnt but with the same code, Is there a way to create two reports (e.g. "cucubmer reports Env A" and "cucubemr reports Env B"). I know for publishHTML it can set reportName and report title to pick different html file and generate report on jenkins with differnt tab (code below)
`
                        publishHTML([
                            allowMissing: false,
                            alwaysLinkToLastBuild: false,
                            keepAll: true,
                            reportDir: 'sample/output-files/',
                            reportFiles: 'report.html',
                            reportName: 'Reliability Report',     <---- can change name here
                            reportTitles: 'Reliability Report'     <----- can change name here
                        ])
`

Does cucumber report has the same functionality. My sample code will looks like below

`
      stage ('System Testing'){
         parallel(
              "Env A": {
                    try {
                        sh './scripts/run-system-tests-AAA.sh'
                    } finally {
                        sh './scripts/clean-system-test-env-AAA.sh'
                    cucumber([
                                      jsonReportDirectory: './e2e-tests/features/output-files/reports',
                                      fileIncludePattern: 'reports-AAA.json',
                                      buildStatus: 'UNSTABLE'
                    ])
                    }
             },
             "Env B": {
                    try {
                        sh './scripts/run-system-tests-BBB.sh'
                    } finally {
                        sh './scripts/clean-system-test-env-BBB.sh'
                    cucumber([
                                      jsonReportDirectory: './e2e-tests/features/output-files/reports',
                                      fileIncludePattern: 'reports-BBB.json',
                                      buildStatus: 'UNSTABLE'
                    ])
                    }
             }
       )
       }
 `

**Comment by damianszczepanik** [comment]
Currently not supported and I rather won't add support for this in near future. However if you take a look at publish html report plugin (which AFAIR supports that) I will be happy if you prepare PR for this nice enhancement.

**Comment by HemantaK** [comment]
@damianszczepanik  the same feature #237 is really required for similar use cases I have where I have parallel stage in pipeline job for all browsers (firefox, IE, Safari and Chrome) , need reports for all of them. As per your response, this won't be added in future ?

**Comment by damianszczepanik** [comment]
Same as above: no plan to prepare, happy to accept PR

**Comment by damianszczepanik** [comment]
Follow this discussion damianszczepanik/cucumber-reporting#769
