### ISSUE TITLE
Not seeing Show Cucumber Results link in e-mail

### ISSUE THREAD

**Issue by mrbence** [jenkinsci/cucumber-reports-plugin#240]
I'm not seeing the Show Cucumber Results in the eTAF_Report e-mail from the Jenkins pipeline job. I see it on my local (image attached) and also see the link to the report in the Jenkins logs. 

20:42:01 cucumber_tests=true
20:42:01 cucumber_tests_app_version=1
20:42:01 cucumber_tests_name=app
20:42:01 cucumber_tests_results_image_resize=30
20:42:01 cucumber_user_js_in_report=true
20:42:01 cucumber_report_subfolder=cucumber-html-reports

https://i.imgur.com/npKE0Ww.png

**Comment by mrbence** [comment]
Update, I am now seeing the Show Cucumber Results link in the e-mail when I e-mail the emailable-report.html. However, the link is now correct and just opens Jenkins. Is there a way to configure the link in the e-mail? It looks like the URL in the link is off a few letters and not sure why.

The email report goes to ....eTAF_5fReport. 

Link in the e-mail (doesn't work)
/eTAF_Report/1530891375584/artifacts/CucumberReport/cucumber-html-reports/feature-overview.html

Link of the report (works)
eTAF_5fReport/1530891375584/artifacts/CucumberReport/cucumber-html-reports/feature-overview.html

**Comment by damianszczepanik** [comment]
This plugin does not support emails
