### ISSUE TITLE
Ugly reports in 1.3.0

### ISSUE THREAD

**Issue by emoshaya-cognito** [jenkinsci/cucumber-reports-plugin#25]
I updated from 1.2.0 to 1.3.0 last night and the reports have horizontal scroll bars for each feature step outcome. This is annoying when you have a long report and having to scroll for each step outcome. I much prefer the old format where the step outcomes were just wrapped within the frame its in.

1.2.0:
![before](https://cloud.githubusercontent.com/assets/8818542/12916820/256fd70a-cf2d-11e5-973e-4761a49275b2.png)

1.3.0:
![after](https://cloud.githubusercontent.com/assets/8818542/12916824/2e49b864-cf2d-11e5-9abe-8b6ed0ea118b.png)

**Comment by damianszczepanik** [comment]
IT was intentional change requested in damianszczepanik/cucumber-reporting/issues/278 by @rommy1204 which I believe is better than having many log lines below each step.

I can change it if you have idea how to make both requests satisfied

**Comment by emoshaya-cognito** [comment]
I disagree with you that you feel this is better,, People want to look at logs and see step outcomes at a glance... Now we're having to scroll through every step outcome which will get annoying in a very long log. I've now reverted back to 1.2.0

Thanks

**Comment by damianszczepanik** [comment]
I agree that this is true when you are talking about IT point of view hiwever this plugin is not only for IT and others expect to see overview nor lines of logs. Mind that this is BDD report not unit test

**Comment by rommy1204** [comment]
Hi Damian, it is not exactly what had been requested :)
We wanted to change this:
![2016-02-11_1351](https://cloud.githubusercontent.com/assets/10895964/12973567/bb81fe22-d0c6-11e5-8d14-78abace10e97.png)

but not to get this:
![2016-02-11_1352](https://cloud.githubusercontent.com/assets/10895964/12973583/d4267b92-d0c6-11e5-9a0b-3c5a4220a531.png)

Could you please backout this changeset? We would like just remove extra tabulation and leave everything as it was before

**Comment by damianszczepanik** [comment]
Did you read above comments? They provide reason for this change

**Comment by emoshaya-cognito** [comment]
@damianszczepanik @rommy1204 is the one who raised the pull request... He is stating that the scrollbars was not the supposed to be part of the PR

**Comment by rommy1204** [comment]
I agree that it could be usefull. But it looks very strange for now
For example:
1. if you apply (+) functionality not to the first logs row, but to the step - it would be better
2. remove horizontal scrolls, leave word wrapping if there is no enough space to have it in 1 row
3. It should be expanded by default for failed scenarios to see the steps and reproduce them (it is not convenient to expand them all manually)

With these improvements it will be good! :)

**Comment by damianszczepanik** [comment]
1. Possible
2. No, since there were also request not to wrap logs which I agree with - wrapping lines of logs looks strange for IT guys
3. Sounds good

I will take a look at this later but you can send PR if you like

**Comment by damianszczepanik** [comment]
This has been refactored recently and the UX is much different. If you need further improvements, please file new issue
