### ISSUE TITLE
Merge normal run report and Re run report

### ISSUE THREAD

**Issue by sonu-sdz** [jenkinsci/cucumber-reports-plugin#251]
Hi,
I have two runners in my automation project as follows:

Main runner - Executes all the @ui-test tagged test cases and if a scenario is failed target/rerun.txt will be populated with the scenario location

```
@RunWith(Cucumber.class)
@CucumberOptions(
    features = "classpath:features",
    plugin = {"pretty", "html:target/cucumber-html-report", "json:target/cucumber.json", "rerun:target/rerun.txt"}
)
public class RunCukesTest {
}
```

Secondary runner - Re-executes the scenarios from target/rerun.txt:
```
@RunWith(Cucumber.class)
@CucumberOptions(
    features = "@target/rerun.txt",
    plugin = {"pretty", "html:target/cucumber-html-report-rerun", "json:target/cucumber_rerun.json"}
)
public class ReRunFailedCukesTest {
}
```
When the execution is performed two result json files are created:

cucumber.json
cucumber_rerun.json
Jenkins will collect the results via Cucumber-JVM Reports plugin and will create a combined report.

Is there a way to overwrite cucumber.json with the results from cucumber_rerun.json and to publish only the modified cucumber.json?

**Comment by damianszczepanik** [comment]
Not by this plugin
