### ISSUE TITLE
[FEATURE] Update the wiki to include pipeline usage to configure the advance parameters

### ISSUE THREAD

**Issue by Downright-Development** [jenkinsci/cucumber-reports-plugin#253]
Currently the readme only details how to include the plugin as a post action within Jenkins DSL. The readme should also include how to configure the advance parameters. I

If advance parameters are only able to be configured via the GUI, another issue should be opened to allow full configuration via DSL.

**Comment by Downright-Development** [comment]
I have figured out how to configure this plugin using raw DSL and I'd like to create a PR to include that information on the readme.

I'm typing it as a comment in here for now specifically for archive purposes so that I can fork the project later tonight.

configure { project ->
    project / 'publishersd' << 'net.masterthought.jenkins.CucumberReportPublisher' {
        fileIncludePattern '**/*.json'
        fileExcludePattern '<patternHere>'
        jsonReportDirectory ''
        failedStepsNumber '0'
        skippedStepsNumber '0'
        pendingStepsNumber '0'
        undefinedStepsNumber '0'
        failedScenariosNumber '0'
        failedFeaturesNumber '0'
        buildStatus 'FAILURE' (other options are, "UNCHANGED' and 'UNSTABLE'
        trendsLimit '0'
        parallelTesting 'false' (other option is true)
        'sortingMethod' 'ALPHABETICAL'
 }

There's also "classification" blocks, but I've not implemented those on my end. 

}

**Comment by Downright-Development** [comment]
@damianszczepanik  This work was completed, this issue should be closed.

**Comment by damianszczepanik** [comment]
@Downright-Development  the API has changed, new version has been released so can you update README one more time?
