### ISSUE TITLE
Unable to pass jenkins parmeter to Json Reports Path

### ISSUE THREAD

**Issue by jtflint19** [jenkinsci/cucumber-reports-plugin#256]
Hi,
So I tried to pass a parameter to Json Reports Path: "$BUILD_NUMBER/" as below: 

![image](https://user-images.githubusercontent.com/5701910/46618392-4826f880-cb17-11e8-8127-bb4d76e1e426.png)

And get the following error,
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] Copying all json files from: /srv/Automation/Reports/IST_Test_Sub_Runner_3/$BUILD_NUMBER to reports directory: /u01/app/build/jenkins/jobs/IST_Test_Sub_Runner_3/builds/502/cucumber-html-reports
[CucumberReportPublisher] there were no json results found in: /u01/app/build/jenkins/jobs/IST_Test_Sub_Runner_3/builds/502/cucumber-html-reports

Is it possible to pass a build parameter to the plugin?

**Comment by damianszczepanik** [comment]
Not yet, easy to provide and wroth to support. Would you like to prepare PR about it?

**Comment by damianszczepanik** [comment]
Works for me when using this variable

[CucumberReport] Using Cucumber Reports version 4.1.0-SNAPSHOT
[CucumberReport] JSON report directory is "6"
