### ISSUE TITLE
Name Conflict on Same Named Feature Files

### ISSUE THREAD

**Issue by sturcol** [jenkinsci/cucumber-reports-plugin#261]
This started happening on 4.0.1 (couldn't tell on 4.0.0 due to Issue 259).

I run three browser tests, and each result file has the same name. For example:
Firefox runs My_Feature
Chrome runs My_Feature
Edge runs My_Feature.

On 3.20.0, when clicking the link from the dashboard for each browser, I would go to pages such as:
<job_name>/<run number>/cucumber-html-reports/report-feature_-home-jenkins-workspace-<job_name>-<path>-My_Feature-feature_2.html
<job_name>/<run number>/cucumber-html-reports/report-feature_-home-jenkins-workspace-<job_name>-<path>-My_Feature-feature_10.html
<job_name>/<run number>/cucumber-html-reports/report-feature_-home-jenkins-workspace-<job_name>-<path>-My_Feature-feature_18.html

Now all three browser links resolve to the same link, <job_name>/<run number>/cucumber-html-reports/report-feature_-home-jenkins-workspace-<job_name>-<path>-My_Feature-feature.html

I haven't noticed any pattern for which browser results actually gets shown, but for each run its only one. As in, clicking on that link for Firefox, edge, and chrome all give the Firefox results.

**Comment by sturcol** [comment]
I took a look through the commit history, and noticed a feature was added.

https://github.com/jenkinsci/cucumber-reports-plugin/pull/98

While I didn't notice what would be causing my issue in the code, I did attempt to change my pipeline syntax to use the reducingMethod: 'NONE' param. However, this still didn't fix my issue.

**Comment by damianszczepanik** [comment]
This feature was removed for version 4.0 as the replacement for that was added. Take a look and there is one implantation for reduction strategy. It merges scenarios for same features as I think is your case.

If not let me know what is your case that you have same features in different files so I can understand it and cover this case

**Comment by sturcol** [comment]
Sorry, I think we are on different pages. Let me explain my process a bit more.

I run the same feature three times, once for each browser. The output of the result is My_Feature.json, with the only difference being the path to get to it. Something like
reports/edge/My_Feature.json
reports/chrome/My_feature.json
reports/firefox/My_Feature.json

Then I activate the plugin by doing;
cucumber fileIncludePattern: '**/*.json', jsonReportDirectory: "reports", sortingMethod: 'ALPHABETICAL'

On 3.20.0, I get links looking like:
![image](https://user-images.githubusercontent.com/5579080/46909287-b85dc180-cefd-11e8-8fc1-be1a6820988e.png)

Each link takes me to the correct page results.
![image](https://user-images.githubusercontent.com/5579080/46909293-c9a6ce00-cefd-11e8-8a87-9699f8faff44.png)


On 4.0.1, the first page looks OK and presents three different links, but each link only goes to one browser result (it seems to always be firefox, and I am guessing that is due to the fact it is last alphabetically).
For example, clicking the chrome link in the first image gives firefox results.
![image](https://user-images.githubusercontent.com/5579080/46909309-328e4600-cefe-11e8-9735-4ad5b4c11956.png)

Does this make sense? I believe it has to do with the reduction strategy that was added. Is there some new way to disable that functionality?

**Comment by sturcol** [comment]
I believe the new option you are referring to what I had said I had tried in my first comment.

The following two commands give me the same result. The first is what I use on 3.20.0

cucumber fileIncludePattern: '**/*.json', jsonReportDirectory: "reports", sortingMethod: 'ALPHABETICAL'

cucumber fileIncludePattern: '**/*.json', reducingMethod: 'NONE', jsonReportDirectory: "reports", sortingMethod: 'ALPHABETICAL'

Both of these have the defect described by this issue. Then I tried a third option.

cucumber fileIncludePattern: '**/*.json', reducingMethod: 'MERGE_FEATURES_BY_ID', jsonReportDirectory: "reports", sortingMethod: 'ALPHABETICAL'

This also produced no noticeable change.

BTW: I am on jenkins version 2.121.3.

**Comment by damianszczepanik** [comment]
MERGE_FEATURES_BY_ID should merge scenarios into one feature. If it doesn't then attach all ison files so I can handle this

**Comment by sturcol** [comment]
Sure, I'll get you an example later today.

**Comment by sturcol** [comment]
[reports.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/2479458/reports.zip)

Here is the pipeline code I use:
cucumber fileIncludePattern: '**/*.json', jsonReportDirectory: "reports", sortingMethod: 'ALPHABETICAL'

As a reminder, the issue is that when you use 4.0.1, all three links on the dashboard take you to the same browser, where as that does not happen on 3.20.0. Let me know if you have trouble recreating it.

**Comment by damianszczepanik** [comment]
I will restore implementation for 3.x version as i makes sense to have it. BTW - how did you generate the ID which is different even the tests are same? Which cucumber are you using for testing?

**Comment by damianszczepanik** [comment]
Will be configurable with next release https://github.com/damianszczepanik/cucumber-reporting/pull/766/files#diff-858efbefb85a2d5a42faf0d6a15da70bR16

**Comment by sturcol** [comment]
Thanks so much for looking into it, i'll be on the lookout for the next release.

As for a different ID, I use a custom formatter to append our browser_name_version_platform string (and I add it as a tag as well, so it can be sorted by tagged responses). I override the `feature` and `scenario` methods from JSONFormatter. Here is an excerpt from both.

`Feature myFeature = new Feature(
	feature.getComments(), 
	feature.getTags(), 
	feature.getKeyword(),
	feature.getName() + " " + getBrowserNameString(), 
	feature.getDescription(), 
	feature.getLine(),
	feature.getId() + "-" + getGridIDString());
super.feature(myFeature);`


`Scenario myScenario = new Scenario(
	scenario.getComments(),
	myScenarioTags,
	scenario.getKeyword(),
	scenario.getName() + " " + getBrowserNameString(),
	scenario.getDescription(),
	scenario.getLine(),
	myScenarioID);
super.scenario(myScenario);`

**Comment by sturcol** [comment]
BTW: Do you have a target date for the next release?

**Comment by sturcol** [comment]
Hey @damianszczepanik

I have been trying to get this feature to work, but I can't seem to activate the legacy support on 4.1.0. So far I have tried:
Not changing my pipeline call at all:
	cucumber fileIncludePattern: '**/*.json', jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'

Then I attempted each of the following:
	cucumber fileIncludePattern: '**/*.json', mergeFeaturesById: true, jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'
	cucumber fileIncludePattern: '**/*.json', mergeFeaturesById: false, jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'
	cucumber fileIncludePattern: '**/*.json', reducingMethod: 'FEATURE_FILE_NAME_WITH_NO', jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'

Is there some hidden activator code needed to get the legacy support to work?

**Comment by sturcol** [comment]
Hey @damianszczepanik

I have been trying to get this feature to work, but I can't seem to activate the legacy support on 4.1.0. So far I have tried:
Not changing my pipeline call at all:
	cucumber fileIncludePattern: '**/*.json', jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'

Then I attempted each of the following:
	cucumber fileIncludePattern: '**/*.json', mergeFeaturesById: true, jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'
	cucumber fileIncludePattern: '**/*.json', mergeFeaturesById: false, jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'
	cucumber fileIncludePattern: '**/*.json', reducingMethod: 'FEATURE_FILE_NAME_WITH_NO', jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'

Is there some hidden activator code needed to get the legacy support to work?

**Comment by sturcol** [comment]
I posted my last comment in the middle of the outage, so I am not sure if it went though, I am going to repost again.

Hey @damianszczepanik

I have been trying to get this feature to work, but I can't seem to activate the legacy support on 4.1.0. So far I have tried:
Not changing my pipeline call at all:
	cucumber fileIncludePattern: '**/*.json', jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'

Then I attempted each of the following:
	cucumber fileIncludePattern: '**/*.json', mergeFeaturesById: true, jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'
	cucumber fileIncludePattern: '**/*.json', mergeFeaturesById: false, jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'
	cucumber fileIncludePattern: '**/*.json', reducingMethod: 'FEATURE_FILE_NAME_WITH_NO', jsonReportDirectory: "${reportsDir}", sortingMethod: 'ALPHABETICAL'

Is there some hidden activator code needed to get the legacy support to work?

**Comment by damianszczepanik** [comment]
I've decided to change the API even there were not major version. I'm allowing to have more than one reduicngMethod so each one has own flag. Take a look at https://github.com/jenkinsci/cucumber-reports-plugin/commit/65170762116a6148041c97bc8503f93d16fa5c05#diff-848f2235483f983acf53416159f60a9dR62

**Comment by sturcol** [comment]
@damianszczepanik

OK, it looks like you now only support mergeFeaturesById. Leaving it blank or setting it to true or false still doesn't fix this issue. Can you confirm that the files I gave you actually link to the correct output on 4.1.0? If so, what pipeline code do you use? 
If you can't get the correct link to link to the right file, I think this needs to be reopened and filed against 4.1.0 as well.

**Comment by damianszczepanik** [comment]
I think what you need is to https://github.com/damianszczepanik/cucumber-reporting/pull/766 which will be released with next release. Sorry for the problem
