### ISSUE TITLE
Enable configuration of "Cucumber Results" column in the default job list view

### ISSUE THREAD

**Issue by OmkarSrivastava** [jenkinsci/cucumber-reports-plugin#262]
As an administrator of various Jenkins jobs, I would like the ability to configure whether the "Cucumber Results" column is displayed in the default job list view.

I am generating a cucumber json through Radish scripts and then consuming it for feature report generation. It will big help if we can have this feature added into cucumber plugin to add a separate column for accommodating a summary of the result (eg. Passed 15/17 or Failed 2/17 in a new column).

The use case for this is a situation where multiple Audit and QA teams require same to use those results for different quality analysis.

**Comment by damianszczepanik** [comment]
Looks like duplilcate of #49 
I will accept PR if you prepare
