### ISSUE TITLE
clear .cache in report dir

### ISSUE THREAD

**Issue by regentov** [jenkinsci/cucumber-reports-plugin#265]
When "Publish Cucumber test result report" step in Jenkins is done, the directory of the corresponding build contains "cucumber-html-reports" dir, which contains ".cache" subdir. 

As far as I understand it is the source JSON the report is generated from. It is top-sized and is not used to display the generated report.

Either remove the .cache after generation, or give the way to remove it by some checkbox/setting.

**Comment by damianszczepanik** [comment]
it is used for generation process

**Comment by regentov** [comment]
But is it used *after* generation process? It eats disk space (about 30% of jobs directory) and if it is not necessary *after* generation then it should be removed.

Tried to remove the cache in $jenkins/jobs/jobname/builds/$buildnum/cucumber-html-reports/.cache and the report seems to look as usual. Doesn't it?

**Comment by damianszczepanik** [comment]
Could be used but in most cases it does not. Will consider this request.

**Comment by Downright-Development** [comment]
Is the .cache report used for long-running trends? If job 1,2,3 all have individual results, but on the overall page of the jenkins job there is also a report. This includes results from 1,2,3. Would removing the cache break the overall trend of those three jobs?

**Comment by damianszczepanik** [comment]
cucumber-trends.json is used for trends. The idea of .cache was to have some backup of the JSON files so when users report the issue they have access to reprots which were used for the report.
I have published new major version so once I confirm this becomes stable I will drop .cache

**Comment by dmone90** [comment]
We face the same issue with cucumber. We use version 4.2.2
The **.cache** directory is still generated and it occupies around 7GB of disk space.
I've went and deleted all the .cache directories on each build and it didn't affect the cucumber reports.

**Comment by damianszczepanik** [comment]
Will be delivered with next release
