### ISSUE TITLE
How to include browser, platform, and branch info in Feature Overview?

### ISSUE THREAD

**Issue by kapoorlakshya** [jenkinsci/cucumber-reports-plugin#267]
Hi! I couldn't find any documentation for this. I am using Cucumber ruby and this plugin on Jenkins. I am wondering how do I provide the Browser, Platform, and Branch info to the JSON file? Is this something I do through Cucumber or are there any parameters in the plugin for these? I am using Pipeline by the way.

```
stage('Execute Test(s)') {
      steps {
        ansiColor('xterm') {
          dir(path: 'cucumber-watir') {
            bat 'set NLS_LANG=US7ASCII'
            bat(script: 'bundle exec cucumber -t %tags% -f json -o cucumber.json -f pretty --color --expand')
          } // dir
        } // ansiColor
      } // steps
    } // stage('Execute Test(s)')
```

Sorry, not really an issue. Please point me in the right direction and feel free to close this.

**Comment by jdamasceno** [comment]
Hi, i am really interested in this feature too
I am using Cucumber java and Jenkins.

**Comment by damianszczepanik** [comment]
use classifications

**Comment by kapoorlakshya** [comment]
> use classifications

I did see that here (https://github.com/damianszczepanik/cucumber-reporting), but how do I do it if I am not using Java? Is there a reason the plugin doesn't expose that API?

**Comment by damianszczepanik** [comment]
I see that https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/README.md must be updated but anyway you can use https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java#L96

**Comment by kapoorlakshya** [comment]
Thanks for that link! Looks like there is no way for me to add the classifications if I am not using Java. I guess I'll have to switch to the `report-builder` gem and then use the HTML Publisher plugin instead.

**Comment by damianszczepanik** [comment]
Pipeline is supported https://github.com/jenkinsci/cucumber-reports-plugin#pipeline-usage

**Comment by kapoorlakshya** [comment]
Are you saying the classifications are supported in pipeline? If yes, how do I add it? If you can guide me here, I am willing to document the instructions in the README.

**Comment by damianszczepanik** [comment]
Documentation has been updated - thanks
