### ISSUE TITLE
Trends graph shows only failed scenarios

### ISSUE THREAD

**Issue by jamesbonica** [jenkinsci/cucumber-reports-plugin#272]

**Comment by jamesbonica** [comment]
In the Trends section of the reports, the table labeled Scenarios only represents failed Scenarios and not Passing ones. Please see screenshot.
![passing_sceanrios_not_represented](https://user-images.githubusercontent.com/43998629/48307129-8ba8c400-e514-11e8-95ff-44a2d57d6b74.PNG)

**Comment by damianszczepanik** [comment]
New version has been just released - check with this as trends has been fixed recently

**Comment by jamesbonica** [comment]
Hi Damian,
That was with version 4.2.0 which I think is the latest build

**Comment by damianszczepanik** [comment]
Check the report again against results as BEFORE trends did not chow results properly. If you still believe there is error, attach JSON file for reference.

Check https://github.com/damianszczepanik/cucumber-reporting/pull/765

**Comment by jamesbonica** [comment]
Hi Damian,

I'm still not seeing the passing scenarios rendered in the trends view. In my latest test run all scenarios are passing. I've attached the the json generated by the two features files in my sample test project. Where am I going wrong? Everything else looks great, btw!!
[1002_User_Authentication_Second.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/2592385/1002_User_Authentication_Second.txt)
[1001_User_Authentication.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/2592386/1001_User_Authentication.txt)

**Comment by damianszczepanik** [comment]
Recent version https://github.com/jenkinsci/cucumber-reports-plugin/releases fixes this problem

**Comment by jamesbonica** [comment]
Just downloaded, compiled and ran it. It looks awesome!!!!! Thank you so much. This is an amazing tool.
