### ISSUE TITLE
@AfterStep methods are not shown in generated report

### ISSUE THREAD

**Issue by aostrcontinuum** [jenkinsci/cucumber-reports-plugin#276]
Given I have an @AfterStep hook method like this:

```
@AfterStep()
    public void after(Scenario scenario) {
        scenario.embed("TEST".getBytes(StandardCharsets.UTF_8), "text/plain");
    }
```

Then I **expect** to see the following in my generated Cucumber report:
![2018-11-15_1442](https://user-images.githubusercontent.com/43646069/48553642-ce87e480-e8e4-11e8-9e3f-d7bf1b644893.png)
(and I do see it in report generated from code via maven plugin)

But **actual result** in cucumber report generated by Jenkins plugin is:
![2018-11-15_1438](https://user-images.githubusercontent.com/43646069/48553696-ea8b8600-e8e4-11e8-9095-ecf4edcfd44d.png)

Meanwhile, embedding provided by @AfterStep method is present in cucumber.json which is used by Jenkins plugin for generation:
![2018-11-15_1443](https://user-images.githubusercontent.com/43646069/48553725-0131dd00-e8e5-11e8-9d86-8139543ee35b.png)

**Comment by damianszczepanik** [comment]
embeddings are supported https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/sample.json#L360 so upgrade the plugin or provide JSON file
