### ISSUE TITLE
Cucumber reports main page which wrong links since 4.0.0

### ISSUE THREAD

**Issue by ppinto2016** [jenkinsci/cucumber-reports-plugin#277]
Given we have 3 reports of the same scenario from different devices run in parallel like:

@Launch
Scenario Outline: Launch

Given I Launch the device '\<device\>'
  
@LaunchA
    Examples:
      | device       |
      | Android A |

  @LaunchA
    Examples:
      | device       |
      | Android B |

  @LaunchiOS
    Examples:
      | device |
      | iOS      |

And you have 3 different files 1.json, 2.json. 3.json

The cucumber report will display in the main page 3 entries for the same link Launch.json, although when you choose the tag @Launch the three tests are displayed.

This issue was introduced in version 4.0.0 since before this version the main page has 3 different links for the 3 different devices: 

- Launch.json
- Launch_1.json
- Launch_2.json

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/reducers/ReducingMethod.java#L14 should help

**Comment by damianszczepanik** [comment]
I cannot reproduce with the most recent jenkins plugin
