### ISSUE TITLE
Use in Jenkins Pipeline plugin (known as Workflow)

### ISSUE THREAD

**Issue by jgsqware** [jenkinsci/cucumber-reports-plugin#28]
Hello, I would like to know if it's planned to adapt your plugin for the Pipeline plugin of Jenkins, taht will be in the core of Jenkins 2.0.

Thanks

**Comment by damianszczepanik** [comment]
Tell me more about it

**Comment by jgsqware** [comment]
Regarding this plugin https://github.com/jenkinsci/workflow-plugin (now called Pipeline), if I want to use your plugin as a step, some adaptation is needed (https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md#plugin-developer-guide) to be compatible.

This plugin will be the root of Jenis 2.0, and I've started to use it and I would like to know if you can adapt yours for pipeline?

thanks

**Comment by damianszczepanik** [comment]
This looks like interesting feature so I will take a look at this but I can't tell you when since now I'm developing UI improvments

**Comment by jgsqware** [comment]
OK great I could have a look also but I'm a little lost with the interface
changing and I don't want to break anything ;)!

Le mer. 24 févr. 2016 20:37, Damian Szczepanik <notifications@github.com> a
écrit :

**Comment by damianszczepanik** [comment]
You're welcome. Plugin is not huge and all you need is probably to modify CucumberReportPublisher.java class

**Comment by jphhoeks** [comment]
See pull request #35

**Comment by jgsqware** [comment]
Will test it today!

**Comment by sevensoft** [comment]
Where does the reports link show up when used in a pipeline type of project?
I've installed 2.1.0 and have a pipeline and I can't find the reports link.

Also, I have 2 parallel tasks in the pipeline that are each executing cucumber-jvm tests. Will I have 2 report links each at the point where the parallel task starts?

**Comment by jphhoeks** [comment]
The link shows up in the sidemenu of the builds.

I don't know if 2 links will show up in your situation. I also run the Cucumber tests in parallel, but I let every run create a seperate Cucumber JSON report. After the parallel step is finished, I run the step for creating the Cucumber reports. This way I get only one report with the results of all tests.

**Comment by sevensoft** [comment]
I meant to come back in and update. I see the link.. I had to add the
cucumber report from the 'general step' option.

Looks great.

**Comment by dzonekl** [comment]
Hi, I am struggling to get the Cucumber-jvm link on the job sidemenu. 
The pipeline configuration, doesn't have the configuration options, as for a non-pipeline job. 
I guess I could archive the report and publish it elsewhere, but it seems from @sevensoft he managed to get the direct link in the side menu. 
Can someone expand on how to configure this? 
Thanks! 
Christophe

**Comment by dzonekl** [comment]
Answering my own question... this did the trick in the groovy script for pipelines: 

step([$class: 'CucumberReportPublisher', jsonReportDirectory: 'target/cucumber', fileIncludePattern: 'cucumber.json'])

**Comment by damianszczepanik** [comment]
This has been already released as linked above.

**Comment by dzonekl** [comment]
I don't understand what you mean by already released?

**Comment by dzonekl** [comment]
You mean the compatibility link? Ok, it's released, but it doesn't tell you how to use it...

**Comment by sevensoft** [comment]
I was able to get the link on the left by doing the following.

Click Snippet Generator
Choose: "step: General Build Step" for the Sample Step
Choose: "Cucumber-jvm reports" for the Build Step

I let most of the boxes default because it will scan all dirs for report json files.

This is snippet it gave me back (which I then plugged into my workflow script): 
`step([$class: 'CucumberReportPublisher', fileExcludePattern: '', fileIncludePattern: '', ignoreFailedTests: false, jenkinsBasePath: '', jsonReportDirectory: '', missingFails: false, parallelTesting: false, pendingFails: false, skippedFails: false, undefinedFails: false])`

You may have to refresh the job (page showing the pipeline) after the test and reports are run in order for the link to show up on the left.
