### ISSUE TITLE
JVM report broken

### ISSUE THREAD

**Issue by mchoyal** [jenkinsci/cucumber-reports-plugin#282]
Hi,

Jenkins cucumber JVM report not generating, its giving following errors..

21:59:22 ERROR: Step ‘Cucumber-JVM reports’ aborted due to exception: 
21:59:22 java.lang.NoSuchMethodError: net.masterthought.cucumber.Configuration.setStatusFlags(ZZZZ)V
21:59:22 	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:126)
21:59:22 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
21:59:22 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
21:59:22 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
21:59:22 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
21:59:22 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
21:59:22 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
21:59:22 	at hudson.model.Run.execute(Run.java:1766)
21:59:22 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
21:59:22 	at hudson.model.ResourceController.execute(ResourceController.java:98)
21:59:22 	at hudson.model.Executor.run(Executor.java:410)

**Comment by damianszczepanik** [comment]
Upgrade the plugin to recent version and check again

**Comment by mchoyal** [comment]
Thanks!, its fixed now after updating to latest version.
