### ISSUE TITLE
Build step 'Publish Cucumber test result report' changed build result to UNSTABLE

### ISSUE THREAD

**Issue by mchoyal** [jenkinsci/cucumber-reports-plugin#283]
Hi, Jenkins job gets UNSTABLE status when it have some failed cases. Following is console log when cucumber test result report plugin cause build to unstable.

[Cucumber Tests] Parsing results.
[Cucumber Tests] parsing cucumber.json
Build step 'Publish Cucumber test result report' changed build result to UNSTABLE
[CucumberReport] Using Cucumber Reports version 4.2.2

**Comment by damianszczepanik** [comment]
This is feature which can be configured
