### ISSUE TITLE
net.masterthought.cucumber.ValidationException - Not proper cucumber report

### ISSUE THREAD

**Issue by mpasha** [jenkinsci/cucumber-reports-plugin#289]
Getting the below error, even I am pointing to the right cucumber generated json file.

net.masterthought.cucumber.ValidationException: File 'C:\Users\Mehraj Pasha\Documents\ntuc-income-up\up-automation\target\cucumber.json' is not proper Cucumber report!
        at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:99)
        at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:71)
        at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)
        at com.ntuc.income.up.runner.RunCukeTest.teardown(RunCukeTest.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (InputStreamReader); line: 1, column: 0]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
        at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:93)
        ... 25 more

POM File:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ntuc.income</groupId>
    <artifactId>unified-portal-qa</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.resourceEncoding>UTF-8</project.build.resourceEncoding>
        <maven.compile.encoding>UTF-8</maven.compile.encoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>

        
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>1.2.5</version>
        </dependency>

        
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>1.2.5</version>
        </dependency>

        
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>1.2.4</version>
        </dependency>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>3.14.0</version>
        </dependency>

        <dependency>
            <groupId>com.vimalselvam</groupId>
            <artifactId>cucumber-extentsreport</artifactId>
            <version>3.0.2</version>
        </dependency>

        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>3.1.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-web</artifactId>
            <version>2.8.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.8.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.8.2</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.25</version>
        </dependency>

        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.3.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.16</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.16</version>
        </dependency>

        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>1.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-htmlunit-driver</artifactId>
            <version>2.52.0</version>
        </dependency>

        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>phantomjsdriver</artifactId>
            <version>1.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>2.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.bitbucket.iamkenos</groupId>
            <artifactId>cissnei-rest</artifactId>
            <version>1.0.4</version>
        </dependency>
        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>4.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.8.1</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.6</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.0.2</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.14</version>
                <configuration>
                    <skip>false</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>RunTests</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <includes>
                                <include>**/RunCukeTest.class</include>
                            </includes>
                            <testFailureIgnore>true</testFailureIgnore>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ParallelTests</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <skip>false</skip>
                            <forkCount>2</forkCount>
                            <reuseForks>false</reuseForks>
                            <argLine>-Duser.language=en</argLine>
                            <argLine>-Xmx1024m</argLine>
                            <argLine>-XX:MaxPermSize=256m</argLine>
                            <argLine>-Dfile.encoding=UTF-8</argLine>
                            <useFile>false</useFile>
                            <includes>
                                <include>**/*Test.class</include>
                            </includes>
                            <testFailureIgnore>true</testFailureIgnore>
                        </configuration>

                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

RunCukesTest.java

package com.ntuc.income.up.runner;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

@RunWith(Cucumber.class)
@CucumberOptions(features = "src/test/resources/features",
glue = "com/ntuc/income/up/steps",
tags = { "@PU-2" },
dryRun = false,
strict = true,
monochrome = false,
format = {"json:target/cucumber.json"}
)
public class RunCukeTest {

	@AfterClass
	public static void teardown() {

        Collection<File> jsonFiles = org.apache.commons.io.FileUtils.listFiles(new File("target/"), new String[]{"json"}, true);
        List<String> jsonPaths = new ArrayList(jsonFiles.size());
        jsonFiles.forEach(file -> jsonPaths.add(file.getAbsolutePath()));
        Configuration config = new Configuration(new File("target/"), "up");
        ReportBuilder reportBuilder = new ReportBuilder(jsonPaths, config);
        reportBuilder.generateReports();

	}

	@BeforeClass
	public static void setup() {

//		ExtentProperties extentProperties = ExtentProperties.INSTANCE;
//		extentProperties.setReportPath("output/myreport.html");
	}
}

Kindly help me with the issue.

**Comment by mpasha** [comment]
My JSON file:

[
  {
    "line": 1,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 17659736400,
              "status": "passed"
            },
            "match": {
              "location": "Hook.setup()"
            }
          }
        ],
        "line": 13,
        "name": "Register a PH user",
        "description": "",
        "id": "register-for-an-up-account-(ph);register-a-ph-user;;2",
        "after": [
          {
            "result": {
              "duration": 202600,
              "status": "passed"
            },
            "match": {
              "location": "Hook.afterScenario(Scenario)"
            }
          },
          {
            "result": {
              "duration": 855902200,
              "status": "passed"
            },
            "match": {
              "location": "Hook.tearDown()"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 3492356700,
              "status": "passed"
            },
            "line": 5,
            "name": "user launches the unified portal with \"Register\" and \"RegisterPHUser_TC1\"",
            "match": {
              "arguments": [
                {
                  "val": "Register",
                  "offset": 39
                },
                {
                  "val": "RegisterPHUser_TC1",
                  "offset": 54
                }
              ],
              "location": "StpRegister.user_launches_the_unified_portal_with_and(String,String)"
            },
            "matchedColumns": [
              0,
              1
            ],
            "keyword": "Given "
          },
          {
            "result": {
              "duration": 4058616500,
              "status": "passed"
            },
            "line": 6,
            "name": "user fills up the registration form and clicks on next",
            "match": {
              "location": "StpRegister.user_fills_up_the_registration_form_and_clicks_on_next()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 4442223100,
              "status": "passed"
            },
            "line": 7,
            "name": "user enters the otp successfully",
            "match": {
              "location": "StpRegister.user_enters_the_otp_successfully()"
            },
            "keyword": "And "
          },
          {
            "result": {
              "duration": 5987384700,
              "status": "passed"
            },
            "line": 8,
            "name": "user fills up and submits the register verification form",
            "match": {
              "location": "StpRegister.user_fills_up_and_submits_the_register_verification_form()"
            },
            "keyword": "And "
          },
          {
            "result": {
              "duration": 5172583300,
              "status": "passed"
            },
            "line": 9,
            "name": "email verification link is sent to the user",
            "match": {
              "location": "StpRegister.email_verification_link_is_sent_to_the_user()"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "line": 3,
            "name": "@PU-2"
          }
        ]
      }
    ],
    "name": "Register for an UP account (PH)",
    "description": "",
    "id": "register-for-an-up-account-(ph)",
    "keyword": "Feature",
    "uri": "Register.feature"
  }
]

**Comment by mpasha** [comment]
If you see my error : 'C:\Users\Mehraj Pasha\Documents\ntuc-income-up\up-automation\target\cucumber.json' is not proper Cucumber report!

it is pointing to the same file path what I mentioned in the RunCukesTest to generate the json file as (format = {"json:target/cucumber.json"})

In the whole framework I have only 1 json file that is the one generated from cucumber

**Comment by mpasha** [comment]
Please help me in resolving this issue

**Comment by damianszczepanik** [comment]
Sorry but the file content is not even proper JSON file so how would you like to be special cucumber JSON file...

**Comment by mpasha** [comment]
but this file is generated automatically generated by cucumber, is info.cukes is generating the wrong json file?

**Comment by ssharmaexp** [comment]
Even I'm facing same issue. I get this very same error when running my test via Cucumber runner, but
strange part is that when I use same json file [auto generated by last run] and run ReportGenerator class  alone it generates report as expected.

**Comment by mpasha** [comment]
@ssharmaexp The json file that is generated with info cukes is incompatible for masterthought. This issue got resolved when I user cucumber.io dependency instead of info.cukes.

**Comment by myusoof-xinja** [comment]
You are trying to use the json for report generation even before the test execution completed. The report generation shouldn't be part of AfterClass

**Comment by kishore-marramreddy** [comment]
@myusoof-xinja @damianszczepanik  Could you please let us know, when should we use the report generation, if not @AfterClass.

**Comment by PulsatingStar** [comment]
@kishore-marramreddy I was having the same issue and resolved with below step. 
Please use move the method for generating report to @AfterSuite annotation method and point json file "target/cucumber/cucumber.json".

**Comment by shankar4a1** [comment]
@kishore-marramreddy , I tried by mentioning generateReports() in @AfterSuite but it didnot work.Please help if this issue is resolved for you

**Comment by kapildaksh** [comment]
Still seems unsolved issues, strange for me too, automatically cucumber.json from io.cucumber doesn't work in after, after suit, after class annotation it always says invalid Json but this Json is damn correct,   if I run this report gen method in separate class with same josn works perfectly.

**Comment by kaushi90** [comment]
> @kishore-marramreddy I was having the same issue and resolved with below step. Please use move the method for generating report to @AfterSuite annotation method and point json file "target/cucumber/cucumber.json".

Greate. It resolved for me too. Thanks

**Comment by Balamu2806** [comment]
Hi how did you fix the issue please help on the same. Im also facing same issue
