### ISSUE TITLE
 How can I add info to the cucumber report jenkins?

### ISSUE THREAD

**Issue by Alebqto** [jenkinsci/cucumber-reports-plugin#294]
I need to add the curl or json request to the report, I use java and the library rest assure
in this scenario

  @Create
  Scenario: Check when i send an list of valid params, with wrong credentials the response retrieve error message and code error and check with Json schema
    Given a invalid user and invalid key from  platform
    When users want to create project with the values
      | key           | value                      |
      | name        | @@namerandom  |
      | visibility     | public                     |
    Then the api should response with code 401
    And Check JSON schema "project/ErrorMessage.json"

coda java:

  @When("^a created project with values with invalid credentials$")
    public void aCreatedProjectWithInvalidCredentials(DataTable dataTable) throws Throwable {
   response.set(rs.get().contentType(ContentType.JSON).body(dataTableToJson(dataTable.asList(BodyElement.class))).put("/project"));

    }

I want to add information to the report for example:

JSON REQUEST:

{
    "name": "@@namerandom",
    "visibility": "public",
}

**Comment by damianszczepanik** [comment]
You can use classification

**Comment by kapoorlakshya** [comment]
Here is how I did it - https://github.com/jenkinsci/cucumber-reports-plugin/issues/267

**Comment by peternelissen** [comment]
How do I add the classification in java?

Where can I find more info about these classifications?

**Comment by damianszczepanik** [comment]
in Java? This is plugin, not standalone/library
