### ISSUE TITLE
Getting $element.getKeyword() $element.getName() when we pass empty element array for scenario

### ISSUE THREAD

**Issue by ajmera25** [jenkinsci/cucumber-reports-plugin#296]
If I retry the failed scenario then generated cucumber json contain details of both[original+retried] run. I have written a custom logic which help me in keeping only details of latest run scenario if it is retried. But the catch is somehow I am not able to remove the empty array. 

Though I am not able to remove empty array object. Still i hope plugin should restrict that and same should not be displayed in the report.  I am attaching sample json for reference. Attached the screenshot of report and also attaching the sample json file[extension with txt as json is not supported].

[cucumber-report.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/2884493/cucumber-report.txt)
![cucumberscenario](https://user-images.githubusercontent.com/25277202/53090033-2bbeb200-3534-11e9-8b5f-be97be9c98f3.PNG)

Could you please have a look please. Thanks

**Comment by ajmera25** [comment]
tried with latest version 4.4.0

**Comment by ajmera25** [comment]
Hi @damianszczepanik :-  I know this is not a bug in first place. But will you be supporting this enhancement. As empty array should not be reflected in the report. Thanks. Awaiting for your reply

**Comment by damianszczepanik** [comment]
Reopening for deeper analyses. 

Which cucumber implementation and version are you using to generate the JSON file?

**Comment by ajmera25** [comment]
cucumber-jvm - 4.2.0
cucumber report plugin - 4.4.0

**Comment by damianszczepanik** [comment]
This is fake JSON, does not look like to valid one. Provide the real one if you want me to start investigating.

**Comment by ajmera25** [comment]
Hi @damianszczepanik :- This is not the fake json. What I am doing is that I am just removing the data of array json for which scenario is retried from the cucumber generated json. so that json contain only the result of latest scenario.

**Comment by damianszczepanik** [comment]
Then this JSON is not valid
