### ISSUE TITLE
Version Information in Page Footer

### ISSUE THREAD

**Issue by msymons** [jenkinsci/cucumber-reports-plugin#30]
As can be seen in this screenshot, plugin version information has been removed from the footers of reports.

![cucumber-jenkins-plugin-footer](https://cloud.githubusercontent.com/assets/4938718/13527553/ae2c1648-e207-11e5-81b2-d0598db0e53c.png)

I would like to see version information displayed in the footer... it provides a quick and easy way of being sure that a particular Jenkins project is using an up-to-date plugin.  Sure,  the footer does display the build date of the plugin - but that is not quite as easy to work with when (especially when github reports that the most recent version v1.4.0 was "13 days ago" - which (at time of writing) is *before* "23-02-2016".

**Comment by damianszczepanik** [comment]
For most users this information is useless because you still need to have admin permission to update the plugin. That's why it was removed. 

Additionally it was hard to maintain because the same version must be updated: in pom and in java file

**Comment by msymons** [comment]
I know that admin permission is needed.  That's actually exactly *why* I logged the issue in the 1st place... so that testers and developers who do NOT have admin permission can tell that the plugin is out of date and then nag the person who *does* have admin permission to do something about it.
