### ISSUE TITLE
how to get cucumber html reports only for failed scenarios

### ISSUE THREAD

**Issue by varunnahata** [jenkinsci/cucumber-reports-plugin#302]
Is it possible to only print the failed scenario in cucumber-html-reports, i.e if i have 10 scenario out of which 2 got failed, then i want a report of those 2 failed scenarios.

**Comment by damianszczepanik** [comment]
No but looks like nice feature

**Comment by boris779** [comment]
I think this feature is already implemented.

If you click on the top right on "Failures" and afterwards on the up arrow you see all failing scenarios
