### ISSUE TITLE
Include Report Date in Report

### ISSUE THREAD

**Issue by msymons** [jenkinsci/cucumber-reports-plugin#31]
The plugin report identifies Build Number and Project Name.

I would also like to see the report include a timestamp for the Build.

Thus, when clicking (say) "Previous Build", it would be immediately apparent that one is looking at a report that was generated an hour ago, last night (daily build), or a long time in the past (build on demand).

**Comment by damianszczepanik** [comment]
Date is added to the footer but in next release it will be a part of summary

**Comment by michalczaplinski** [comment]
Hi, which release is it fixed in? could you reference the PR in the issue here? Thanks.
