### ISSUE TITLE
what is the appended number behind the feature file?

### ISSUE THREAD

**Issue by hendryang** [jenkinsci/cucumber-reports-plugin#311]
Hi guys, this is a question.

What is the appended _1 , _2 , _3 , _n in the feature link?

eq. http://myjenkin.com/job/test/33/cucumber-html-reports/report-feature_-blabla-blab-feature_1.html
what is the _1 in the end? it seems to be marking when the sequence of this feature file get executed ? is there a way in the configuration to get rid of it ?

thanks a lot!
PS. i cannot seem to add label to this as question, sorry guys

**Comment by damianszczepanik** [comment]
This is append when more then one feature file for the same feature is added to the report.

**Comment by hendryang** [comment]
@damianszczepanik thanks for the reply. Is there any case why do we need such feature, other than possibility of duplicated .feature name? 
currently i'm writing a script to get this feature url (from feature uri in JSON). but unable to figure out the full path due to appending sequence number and such number doesn't exist in the JSON result. any possibility to disable this? or maybe find out the number. thanks!

**Comment by damianszczepanik** [comment]
Take a look for some demo http://damianszczepanik.github.io/cucumber-html-reports/overview-features.html which does not have duplicated features so the index is not append to the file

**Comment by hendryang** [comment]
thanks @damianszczepanik , i've upgraded my cucumber plugin. however now it looks completely different as per your link.
.../cucumber-html-reports/report-feature_1_1515379431.html
.../cucumber-html-reports/report-feature_1920820787.html

how do i generate _1_1515379431 and _1920820787 from JSON to match cucumber report generated html? any clue?

previously i just need to append the path and feature name like below
.../cucumber-html-reports/report-feature_-home-u111-src-test-resources-features-test1-mysample-feature.html

thanks lot

**Comment by damianszczepanik** [comment]
It has changed when upgraded to v 4.x.x and will stay unchanged forever hopefully
