### ISSUE TITLE
For parallel execution the aggregate duration of individual scenarios is shown instead of the actual.

### ISSUE THREAD

**Issue by shivamconan** [jenkinsci/cucumber-reports-plugin#316]
So we are running our cucumber tests in parallel using [cucable](https://github.com/trivago/cucable-plugin) plugin. And if we execute scenarios in parallel for a particular feature file, the duration in the HTML reports is equal to the time it would have taken for a sequential run (i.e. sum total of all the individual scenarios). We would like to see the actual time it  took to run considering we are running them in parallel.

**Comment by damianszczepanik** [comment]
How would you like to manage this?

**Comment by shivamconan** [comment]
Hi @damianszczepanik. I assume you are asking what is my expected outcome. I expect the duration time to be equal to the actual time the build took to execute. For example if there are 6 tests running with parallelCount as 3 and each taking 1 minute to execute, the duration should be shown as 2 minutes. Currently it would show 6 minutes.

**Comment by damianszczepanik** [comment]
Nope. I ask how do you want to decide if tests were executed sequentially or parallel
