### ISSUE TITLE
Allow Embedded Links Outside Iframes

### ISSUE THREAD

**Issue by cboves** [jenkinsci/cucumber-reports-plugin#319]
I was hoping for an embedding mimeType to allow writing out text that was sanitized of html except for links and displayed outside of an iframe..

**Use Case**
The use case is when we generate reports, we would like the option to have links on failed steps that are generated in @After or @AfterStep that link off to third party systems like Kibana which don't load well inside of an iframe sandbox. We just want to be able to click a generated link and have it open in a new tab outside of Jenkins.

There is already a PolicyFactory setup for allowing this, just not hooked up to embeddings in any way that I can see. 

I would be willing to do a PR, currently I've just added another reference conditional in EscapeHTMLReference that looks for $embedding.getDecodedDataSantized which is a method I call for this one MimeType in embeddings.

Would you prefer this is done a different way? Looking for thoughts feedback on this idea.

The mimeType could be called "sanitized/text" or "url/text", whatever people think is a good naming convention. 

Thanks

**Comment by damianszczepanik** [comment]
I'm not sure what you are trying to have so maybe you can try prepare PR to show your expectations

**Comment by cboves** [comment]
Hey @damianszczepanik thanks for the quick reply, I will create a PR here shortly. Just to clarify what I want to do.

I want to call something like scenario.embed(url.getBytes(), "text/url"); during the cucumber test. 

Then when the report is generated, I will pick up that mime type and output a message similar to something like scenario.write except outside of an iframe and with usable href tags. 

Does that make more sense?

I just wanted to get your feedback first before doing a PR, in case you wanted a different implementation.

**Comment by damianszczepanik** [comment]
AFAIR that topic has been already discussed and was not accepted due to security reason.
