### ISSUE TITLE
Sorting of Duration and Average Columns

### ISSUE THREAD

**Issue by msymons** [jenkinsci/cucumber-reports-plugin#32]
The usability of the plugin's reports has been much improved by the introduction of sortable columns in tables.

However, the Duration column (all reports) and Average column (Steps report only) have a "broken" sort.  For instance, sorting Duration for one of my Feature reports:

15m 17s 527ms
18s 939ms 
19s 671ms
1m 04s 430ms
1m 11s 669ms
28m 39s 304ms

This sort is out of order.

Is it possible for sort to be performed using consistent units (such as milliseconds) whilst still displaying in minutes, seconds, etc?

**Comment by damianszczepanik** [comment]
Already improved damianszczepanik/cucumber-reporting/issues/401
