### ISSUE TITLE
Incorrect Timezone on the Reports

### ISSUE THREAD

**Issue by p2105** [jenkinsci/cucumber-reports-plugin#327]
Steps to reproduce:
1) Change the time zone using the Groovy Script System.setProperty('org.apache.commons.jelly.tags.fmt.timeZone', 'Europe/Brussels')
2) Generate the Reports and it will contain the old Time Zone and not the new one.

Regards,
Prashant G

**Comment by damianszczepanik** [comment]
I believe this property has nothing in common with implementation that generates date https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/ReportResult.java#L184

**Comment by p2105** [comment]
How do we set it then?

**Comment by damianszczepanik** [comment]
It gets the date from the machine the report is generated

**Comment by nkshschdv** [comment]
Is there a way to change the timezone other than changing system timezone ?

**Comment by damianszczepanik** [comment]
I don't know any
