### ISSUE TITLE
Failing After Step / Hook will not fail the scenario

### ISSUE THREAD

**Issue by boris779** [jenkinsci/cucumber-reports-plugin#330]
If on the last step the \@AferStep fails the whole scenario is not marked as failing.
e.g. the cucumber-Runner in IntelliJ will mark the scenario as failed.

![cucumber_report](https://user-images.githubusercontent.com/10259016/66839109-2fd98d00-ef66-11e9-9308-a73309672ad0.png)

![cucumber_report_intelliJ](https://user-images.githubusercontent.com/10259016/66839118-349e4100-ef66-11e9-9437-eebf1eb34b16.png)

In my opinion, it should fail the whole scenario

**Comment by damianszczepanik** [comment]
Can you refer to this example and provide details about your expectation ?
http://damianszczepanik.github.io/cucumber-html-reports/report-feature_1_1515379431.html
