### ISSUE TITLE
Lambda implemented steps are not mapped correctly in the Steps analysis page

### ISSUE THREAD

**Issue by romansmat** [jenkinsci/cucumber-reports-plugin#332]
We have implemented our steps through lambda expressions e.g.:
`import cucumber.api.java8.En;

public class StepDefinitions extends CucumberStepDefinitions implements En {

	public TestStepDefinitions() {
		Given("I implement a step" -> {
			//My code here
		});
}`

When the test is ran, we are not able to properly identify the steps in the steps analysis page since the actual step name is replaced by the step line (in this case line:19).
E.g. :
![image](https://user-images.githubusercontent.com/11835789/67288131-15169380-f4e5-11e9-9988-3c00af7964c9.png)

**Comment by damianszczepanik** [comment]
Share JSON file

**Comment by romansmat** [comment]
Hm... this is an excerpt from the file:

> {
> "line": 2,
> "elements": [
> {
> "line": 4,
> "name": "",
> "description": "",
> "type": "background",
> "keyword": "Background",
> "steps": [
> {
> "result": {
> "duration": 433543394,
> "status": "passed"
> },
> "line": 5,
> "name": "blah blah ",
> "match": {
> "arguments": [
> {
> "val": "200",
> "offset": 34
> }
> ],
> "location": "AccountStepDefinitions.java:19"
> },
> "keyword": "Given "
> },
> {
> "result": {
> "duration": 213512094,
> "status": "passed"
> },
> "line": 6,
> "name": "blah",
> "match": {
> "location": "AccountStepDefinitions.java:31"
> },
> "keyword": "And "
> }
> ]
> }

I am guessing you are reading this part: "location": "AccountStepDefinitions.java:19" . If so, the problem seems to be located in how the json is produced?

**Comment by damianszczepanik** [comment]
Yes, and this is a feature

**Comment by romansmat** [comment]
This is withdrawn - No bug here.
