### ISSUE TITLE
Embedded files not shown correctly after upgrading to 4.11.0

### ISSUE THREAD

**Issue by JKlintholm** [jenkinsci/cucumber-reports-plugin#333]
After upgrading plusing to 4.11 from 4.10, correctly encoded embeddings do not show correctly in Jenkins Cucumber Report view. Downgrading to 4.10 lets embedded images show correctly again.

Report generated by 4.10 is correctly shown when 4.11 is installed. 
Report generated by 4.11 cannot be correctly shown regardless of version installed.

Incorrect view:
![bild](https://user-images.githubusercontent.com/44022917/67874871-e24c4b00-fb35-11e9-9a93-8501feb1a0a5.png)

Correct View:
![bild](https://user-images.githubusercontent.com/44022917/67875105-2e978b00-fb36-11e9-9f2f-3055f0ffdffb.png)

Actual json report file contains sensitive data, which is why I have not appended it to the issue report, but problem should be quite easily reproducible.

**Comment by damianszczepanik** [comment]
Looks like regression after https://github.com/damianszczepanik/cucumber-reporting/pull/822
@FloKaemmerer can you help with this?

**Comment by FloKaemmerer** [comment]
Its hard to say what the issue is without the source Data.
@JKlintholm can you craft a example without sensitive data that leads to the broken Imgae in the Report?

Or could you test what happens when you pass the content of the data field in the embedding to the following method
`Base64.getDecoder().decode(data);`
does it successfully decode or does it run into an exception?

**Comment by JKlintholm** [comment]
I have crafted an example where I included json file, source image and log file that was embedded, consoleText and screenshot of two consecutive post-build-only job runs with 4.10.0 and 4.11.0 respectively. 

[CucumberDemo.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/3803204/CucumberDemo.zip)

Please let me know if there is anything more I can provide you with.

**Comment by FloKaemmerer** [comment]
It looks like the Source Data is not considered a legal Base64 String.

By looking at the source you provided I see a lot of `\n` within the value of the data field, which cause the java.util.Base64.Decoder to throw a IllegalArgumentException.

how to you produce the source Json? What cucumber Version? Java? JavaScript?

I think hte Cucumber Framework provides a broken base64 String which causes the Problem.

**Comment by JKlintholm** [comment]
It is created in VBScript, using "Msxml2.DOMDocument.3.0" on Windows.
I.e. I'm rolling my own json file.
Strange though that the previous version accepts the exact same base64 sequence...

**Comment by JKlintholm** [comment]
I'm going to test with a later version of the Microsoft library. Will post back when done.

**Comment by JKlintholm** [comment]
Base64 checked to be OK. When I use my own JSON decoder and take the output base64 text and run it through any online base64 to image converter, I get the correct image displayed.

Microsoft encoder does output a lot of newlines, and those are escaped in the JSON encoder as per spec ("JSON strings cannot contain newlines or tabs") into "\n".

My obvious workaround is to remove all newlines before encoding the string into JSON but the question remains:
What was changed between 4.10.0 and 4.11.0 to not interpret escaped characters?

**Comment by FloKaemmerer** [comment]
In Version 4.10.0 `org.codehaus.plexus.util.Base64` was used. in 4.11.0 `java.util.Base64.Decoder` is used.
The latter seems to be more strict regarding legal/illegal characters...

**Comment by JKlintholm** [comment]
Then how are those \n in JSON encoded into the base64 string? Is there a classic CrLf vs. LfCr problem?

**Comment by JKlintholm** [comment]
If left in the string, then obviously there will be a problem as \n is not legal base64. It must be in the interpretation from the string in the JSON file that \n should be translated into "NewLine", or omitted.

**Comment by FloKaemmerer** [comment]
I would suggest that you omitt the newlines in the Base64 Encoded image. They shouldn't be there in the first place.
I assume that it was just coinsidence that the old Base64 decoder was ignoring them.

**Comment by JKlintholm** [comment]
Many, maybe most, perhaps even all, base64 decoders rightfully ignore whitespace. This is the reason why many, Microsoft versions included, base64 encoders output newlines to format large outputs of base64-text. 

The problem here is that the JSON string reader used in the plugin does not correctly decode the correctly escaped newline sequence "\n" into a newline that is native to the system (i.e. Java) which will then be ignored as whitespace by the base64 decoder.

It is perhaps a coincidence that the old base64 decoder ignored "\n" but I bet that both of them correctly ignore newlines and other whitespace characters.

Unless you treat data strings differently from all other JSON encoded strings, you might be in bigger trouble when escaped special characters are turning up in the cucumber report files. Both Gson and Jackson libraries escape newlines, and should be able to unescape them as well.

**Comment by JKlintholm** [comment]
The newline emission is due to the MIME encoding standard for which the Microsoft libraries are intended. 
https://www.ietf.org/rfc/rfc2045.txt

Arguably newlines should not be escaped in this particular instance, but then again JSON string reader should cope with escaped characters.

**Comment by FloKaemmerer** [comment]
So the Problem is not how we treat the content of the data field when processing the Embeddings, but in the configuration(?) of the Reader when initially reading the source JSON.

**Comment by JKlintholm** [comment]
That is what I suggest.

**Comment by JKlintholm** [comment]
Or, more to the point, the configuration of the JSON library reading the individual strings.
(Not the file reader)

**Comment by JKlintholm** [comment]
{
    "escaped": "alpha\nbravo" 
}

should translate the content of "escaped" to:
alpha
bravo

**Comment by JKlintholm** [comment]
Note: For now I will remove the newlines from the output of the Microsoft base64 encoder to make things work with the 4.11.0 plugin.

**Comment by thiagotrentin** [comment]
> ote: For now I will in my code remove the newlines output from the Microsoft base64 encoder to make things work with the 4.11.0 plugin.

I'm facing the same problem on 5.0.1

@JKlintholm can you explain how to make this workaround while this problem is occuring?

Thanks

**Comment by damianszczepanik** [comment]
@JKlintholm I suggest to report the issue to velocity project

**Comment by JKlintholm** [comment]
> I'm facing the same problem on 5.0.1
> 
> @JKlintholm could you explain how to make this workaround while this problem is occuring?

Basically, base64 output "should" already be fine for JSON strings, The newlines that MIME formatting adds is the only problem in this particular case, and MIME encoding is intended for cases where whitespace is filtered away. So the workaround in this case would be to "filter away" whitespace from the output of the MIME encoding. 

Most languages have a string replacement function that can be used for this purpose. In VB it is simply called "Replace", in Java you should be fine with using String.replace. The fundamental thing is that you would have to do the replacement before storing the string in JSON. This would not be a workaround in the plugin itself.

So, this would only be a workaround for the case of embedded files. The more generic problem of strings containing escaped characters must/should be handled in the plugin.

**Comment by thiagotrentin** [comment]
> > I'm facing the same problem on 5.0.1
> > @JKlintholm could you explain how to make this workaround while this problem is occuring?
> 
> @thiagotrentin
> 
> Basically, base64 output "should" already be fine for JSON strings, The newlines that MIME formatting adds is the only problem in this particular case, and MIME encoding is intended for cases where whitespace is filtered away. So the workaround in this case would be to "filter away" whitespace from the output of the MIME encoding.
> 
> Most languages have a string replacement function that can be used for this purpose. In VB it is simply called "Replace", in Java you should be fine with using String.replace. The fundamental thing is that you would have to do the replacement before storing the string in JSON. This would not be a workaround in the plugin itself.
> 
> So, this would only be a workaround for the case of embedded files. The more generic problem of strings containing escaped characters must/should be handled in the plugin.

I'll try it, my problem looks like the same as the [first scenario](http://damianszczepanik.github.io/cucumber-html-reports/report-feature_1920820787.html) of [cucumber-reporting](https://github.com/damianszczepanik/cucumber-reporting)'s live demo

Thanks!
