### ISSUE TITLE
java.lang.NoSuchMethodError: cucumber.api.CucumberOptions.format()[Ljava/lang/String

### ISSUE THREAD

**Issue by maazahmedks** [jenkinsci/cucumber-reports-plugin#334]
This is the Error i am getting when i execute test runner class: 
![error](https://user-images.githubusercontent.com/50337588/68647261-45c77700-053f-11ea-8c16-2e552879041e.png)

**My POM.XML**

<dependencies>
    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>4.6.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>info.cukes</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>1.2.5</version>
    </dependency>

    <dependency>
        <groupId>info.cukes</groupId>
        <artifactId>cucumber-testng</artifactId>
        <version>1.2.5</version>
    </dependency>

    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>gherkin</artifactId>
        <version>6.0.17</version>
    </dependency>

    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>3.141.5</version>
    </dependency>

    <dependency>
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>6.14.3</version>
        <scope>test</scope>
    </dependency>

</dependencies>

**My TestRunner Class:**
![TestRunner](https://user-images.githubusercontent.com/50337588/68647131-e1a4b300-053e-11ea-8584-7a2bfa494bc5.png)

**My Feature File:**
![TestRunner](https://user-images.githubusercontent.com/50337588/68647189-11ec5180-053f-11ea-9bbb-47582a27ad37.png)

**Comment by damianszczepanik** [comment]
This project is about https://github.com/damianszczepanik/cucumber-reporting/blob/master/pom.xml#L3-L4 which I don't see in your pom configuration
