### ISSUE TITLE
No link to report from Blue Ocean interface

### ISSUE THREAD

**Issue by pauloneves** [jenkinsci/cucumber-reports-plugin#338]
I have integrated Jenkins to GitLab, and from GitLab I can see if a commit passed the tests. The commit has a link to my Jenkins Pipeline. It opens the BlueOcean interface and displays the executed pipeline. 

The problem is that I can't have a link from the BO interface to my Cucumber Reports. I must leave it to the classic interface and them click in the Cucumber reports link in the left column. 

My end user is editing the tests and I'd like to spare them to understanding Jenkins different interfaces. 

I'd like to have a link to the cucumber report from the Blue Ocean User interface. The Tests tab would be a nice place for it.

**Comment by pauloneves** [comment]
Issue #270 talks about a problem with Cucumber Reports and Blue Ocean, but I didn't see how they integrate. I always have to go to the classic interface. 

This [Jenkins CI issue](https://issues.jenkins-ci.org/browse/JENKINS-45761) also report that Blue Ocean does not displays the Cucumber Reports plugin.

**Comment by damianszczepanik** [comment]
I had nothing to support it as I supposed it is working out of the box. Looks like there is gap about it

**Comment by pauloneves** [comment]
Would you please show me a screenshot of where I should click in the blue
ocean interface to see cucumber reports report?

Do you have configured it in a pipeline? If so, maybe you can show me your
configuration.

Thanks in advance

Paulo Eduardo Neves

Em ter, 17 de dez de 2019 19:00, Damian Szczepanik <notifications@github.com>
escreveu:

**Comment by damianszczepanik** [comment]
As I wrote: plugin does not support it because I don't use Blue Ocean plugin.

Can you point to plugin which provides such option for blue ocean so I can take a look?
