### ISSUE TITLE
How to knwo what it the file name of report per tags

### ISSUE THREAD

**Issue by fabytta** [jenkinsci/cucumber-reports-plugin#339]
I want to publish  as test execution evidence dynamicly after an execution (in our test managment tool)  the link to html report of the specific scenario
but the report link is different from the tag string
for example to open report for tags AX-5  the link is : http://127.0.0.1:8080/job/Execution/15/cucumber-html-reports/report-tag_2208611422.html
is there any encoding that change the name and i can us it ?

**Comment by damianszczepanik** [comment]
Tag length has no limit thus using this as the path is risky

https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/json/Tag.java#L20
