### ISSUE TITLE
Can not disable percentage rules

### ISSUE THREAD

**Issue by amadridlar** [jenkinsci/cucumber-reports-plugin#341]
I am triying to configure cucumber report to set the build as failed only if scenarios fail. This is the cucumber report configuration that I have in jenkinsfile:
```
cucumber buildStatus: 'FAILED'
        failedFeaturesNumber: -1,
        failedStepsNumber: -1,
        failedScenariosNumber: 3,        
        failedFeaturesPercentage: -1,
        failedScenariosPercentage: -1,
        failedStepsPercentage: -1,
```
I forced the execution to one scenario fails, so the build would be set as success because the number of failed scenarios is less than the number I have configured.
But after the execution, the build is set as failed. This is the cucumber report logs:
```
[CucumberReport] Using Cucumber Reports version 4.11.0
[CucumberReport] JSON report directory is "test/reports/cucumber"
[CucumberReport] Copied 3 json files from workspace "/home/jenkins/workspace/rock-paper-scissors/test/reports/cucumber" to reports directory "C:\Program Files (x86)\Jenkins\jobs\rock-paper-scissors\builds\117\cucumber-html-reports\.cache"
[CucumberReport] Copied 0 properties files from workspace "/home/jenkins/workspace/rock-paper-scissors/test/reports/cucumber" to reports directory "C:\Program Files (x86)\Jenkins\jobs\rock-paper-scissors\builds\117\cucumber-html-reports\.cache"
[CucumberReport] Processing 3 json files:
[CucumberReport] C:\Program Files (x86)\Jenkins\jobs\rock-paper-scissors\builds\117\cucumber-html-reports\.cache\end-of-game.cucumber.json
[CucumberReport] C:\Program Files (x86)\Jenkins\jobs\rock-paper-scissors\builds\117\cucumber-html-reports\.cache\new-game.cucumber.json
[CucumberReport] C:\Program Files (x86)\Jenkins\jobs\rock-paper-scissors\builds\117\cucumber-html-reports\.cache\select-options.cucumber.json
[CucumberReport] Found 2.040816 failed steps, while expected not more than -1.000000 percent
[CucumberReport] Build status is changed to FAILED
```

### Issue
I configured percentage thresholds as -1 so the rule should be disabled, but instead it takes the -1 value as the percentage of steps

**Comment by damianszczepanik** [comment]
I don't think using -1 for percentage is a good idea
https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java#L527

**Comment by amadridlar** [comment]
So, how can I disable that rule?

**Comment by damianszczepanik** [comment]
There is clear information in logs what you have and what you expected to have. Also as I said: I don't know what are you going to expect giving -1 as the percentage.

**Comment by amadridlar** [comment]
I would like to mark the build as failed if three or more scenarios fail, no mather how many steps fail. So I would disable the ```failedStepsNumber``` and ```failedStepsPercentage``` rules, between others.
If I set ```failedStepsNumber``` with -1, this rule is disabled. So I would like to do the same with the ```failedStepsPercentage``` configuration
