### ISSUE TITLE
Publish multiple reports from the same job

### ISSUE THREAD

**Issue by shchukax** [jenkinsci/cucumber-reports-plugin#345]
This issue originates from issues #81 and #84 - both requesting ability to publish multiple reports from the same job.  I submitted a PR for this change, but as both those issues are closed, I am opening this new one and attaching the PR to it.

**Comment by vkovalenk0** [comment]
Hello @shchukax 
As I can see you implemented feature that I really need. 
Can you please have a look at your PR? It seems like it can not be built.

![image](https://user-images.githubusercontent.com/24483726/78007799-715cc980-7347-11ea-9f6f-646f20b8b3c3.png)

**Comment by shchukax** [comment]
Hi!

To get this feature working correctly, a change is needed in a project/library that this one depends on. I'm in a process of getting a PR through for that. As soon as it's done, I'll be coming back to this one.
-Aleks
