### ISSUE TITLE
Separate test results by tables

### ISSUE THREAD

**Issue by mikhalkaivan** [jenkinsci/cucumber-reports-plugin#346]
Hi, all.
I have Jenkinsfile, that runs tests on 'Test' stage, and rerun only failed scenarios on 'Rerun' stage. Final report presented as one table with one header for both. Its ever possible separate result for run and rerun? Somewhere i saw this page, and want the same:
![1](https://user-images.githubusercontent.com/41171178/73728444-62d9a380-4744-11ea-8045-cbe88182f7a2.png)

**Comment by damianszczepanik** [comment]
The only thing I can imagine is #344

**Comment by mikhalkaivan** [comment]
Thanks

**Comment by damianszczepanik** [comment]
Supported by #344
