### ISSUE TITLE
Generate cucumber-html-reports in 'workspace' folder in slave

### ISSUE THREAD

**Issue by varaprasad-pakalapati** [jenkinsci/cucumber-reports-plugin#348]
Hi,

Thanks for this wonderful plugin. 

I am trying to attach the cucumber html report to the email body after successful execution. But the reports are generated in master "../builds/${BUILD_ID}" directory where as my pipeline is executing from $WORKSPACE folder in jenkins slave. I am unable to copy the html file from master to slave to attach it to the body of the email. 

Can you please also generate the reports in $WORKSPACE folder in the slave?

**Comment by damianszczepanik** [comment]
If you can't get access to master (I believe it must be some nice way) then try to copy the report yourself and then attach

**Comment by rafaborrego** [comment]
@damianszczepanik hi, I have a similar issue, trying to upload the report to a server on the next step of the pipeline. How can we copy the generated report in the pipeline if the secondary pod only has access to $WORKSPACE ?
Thanks in advance

**Comment by rafaborrego** [comment]
We can access the files in the pipeline by changing to the master Jenkins node and send the files from there:

node('master') {
  dir("../../jobs/app-name/branches/develop/builds/${BUILD_NUMBER}/") {
    .... // commands to use the files
  }
}
