### ISSUE TITLE
Skipped scenarios are marked as 'Failed'

### ISSUE THREAD

**Issue by amerrit2** [jenkinsci/cucumber-reports-plugin#350]
Skipping a scenario in a 'Before' hook.  The scenario then contains only 'Passed' and 'Skipped' steps, but the scenario is marked as 'Failed' on the report. This shouldn't be the case.

**Comment by damianszczepanik** [comment]
Did you configure plugin not to do that?

**Comment by amerrit2** [comment]
Here's the configuration:
[image: image.png]

There's no option for "Mark skipped steps 'passed'"

The build itself isn't failing, I just want those scenarios to not be
marked 'Failed'

**Comment by amerrit2** [comment]
Thought that image uploaded..

Anyway yeah there's no option to tell the plugin not to mark scenarios with skipped steps as failed

![image](https://user-images.githubusercontent.com/10480649/76563556-0aea3700-647e-11ea-826b-82fbb244a120.png)

3 passed steps, 0 failed steps, 13 skipped steps - Scenario is marked 'Failed'

**Comment by damianszczepanik** [comment]
Use advanced options for that
