### ISSUE TITLE
Re-open: Skipped scenarios are marked as 'Failed'

### ISSUE THREAD

**Issue by amerrit2** [jenkinsci/cucumber-reports-plugin#351]
Re-opening https://github.com/jenkinsci/cucumber-reports-plugin/issues/350

I really appreciate the responses but I think I might not be communicating this right.  

I see in advanced options that I can change if the **build** is marked as failed or succeeded based on a percentage of failed scenarios.  

What I want is for a **Scenario** to be marked "Passed" if it only has skipped and passed steps.

![image](https://user-images.githubusercontent.com/10480649/76580017-bc9c5e80-64a4-11ea-8984-bf647201696a.png)

The above scenario is marked "Failed" (as evidenced by the red color) even though it should be marked "Skipped"

My advance options look like this:

![image](https://user-images.githubusercontent.com/10480649/76632650-e80d6080-6519-11ea-9fdd-308af24e90a9.png)

I don't think I'm missing an option.. am I looking at an older version?  Any help would be appreciated. Thanks.

**Comment by damianszczepanik** [comment]
OK, I got it. You can decide about final build status but scenario is marked as passed when only only when all steps are passed.

And honestly it won't be easy to change this rule as right it stands as https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/json/support/StatusCounter.java#L58
