### ISSUE TITLE
Cucumber report overwrites the report for features that have similar names

### ISSUE THREAD

**Issue by Ira-dovgyalo** [jenkinsci/cucumber-reports-plugin#352]
Hi,
I have two runners in my automation project as follows:

Main runner - Executes all the @GoldenPath tagged test cases.

And I have 2 features with the following names:
1) Feature: Global part description searching
2) Feature: Part description searching

When I run tests the report has results only for feature 'Global part description searching'. 
It completely overwrites the feature with name 'Part description searching'.
But, if I add in the feature 'Part description searching' some word, e.g. 'Non global Part description searching', I will see report for 2 features.
Is it issue of Cucumber?

**Comment by damianszczepanik** [comment]
It gets uri to determine name of the report file. Check that value in your JSON files.

https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/json/Feature.java#L209

**Comment by damianszczepanik** [comment]
This also may help #344
