### ISSUE TITLE
Skipped Scenario is showing as failure. 

### ISSUE THREAD

**Issue by GokhanAtes** [jenkinsci/cucumber-reports-plugin#353]
Cucumber report plugin is treating a skipped scenario as failure. In previous cucumber plugin a skipped scenario would not be treated as failure and it would show as skipped. We have cucumber reports plugin 5.0.2. 
![Screenshot 2020-04-22 at 10 25 16](https://user-images.githubusercontent.com/12426607/79965148-95fa1c00-8483-11ea-8bc8-6c487f3d99c4.png)

We also have an old version of Jenkins with cucumber reports plugin 0.6.0 and as you can see in the scenario section we have skipped column for scenarios. However on 5.0.2. this has been removed and it is treating the skipped scenario as failure.
![Screenshot 2020-04-22 at 10 20 29](https://user-images.githubusercontent.com/12426607/79964805-22f0a580-8483-11ea-82c1-65e80cd76cff.png)

The reason why we would need skipped scenarios, we check if a certain flag is OFF so we can skip our tests. 

Can this be fixed in new version as I dont believe it is consistent where we have skipped column for Steps but not for scenarios.

**Comment by damianszczepanik** [comment]
I believe you can manage this by using new features available in configuration

**Comment by GokhanAtes** [comment]
Hi Damian, I am unable to see the new features available in the configuration to fix my above issue.

**Comment by damianszczepanik** [comment]
.README page contains screenshots with advanced configuration

**Comment by GokhanAtes** [comment]
Hi Damian, i had a look at the .README page and the advanced configuration. The build does not fail when the advanced configuration has ben configured correctly. However when reviewing the cucumber report, it is no consistent as its treating a skipped scenario as failure.

In previous cucumber report plugin, it would not treat a skipped scenario as failure as attached in the images above. 

There should be an option in the advanced configuration to allow skipped tests not being shown as failed.

**Comment by damianszczepanik** [comment]
scenario cannot be skipped, steps can and that is why it works that way
