### ISSUE TITLE
weird HTML files names of cucumber reports

### ISSUE THREAD

**Issue by escap89** [jenkinsci/cucumber-reports-plugin#354]
Since we upgraded some plugins on Jenkins our cucumber reports URLs has been changed (html file part). In meanwhile also our gradle was upgrade to 6.0.

Before upgrade:
http://JENKINSURL/job/TRUNK-nightly/lastCompletedBuild/cucumber-html-reports/report-feature_src-main-java-com-fineos-adminsuite-selenium-cucumber-features-MemberBillBreakdown-feature_1.html
 
Correct version:-
http://JENKINSURL/job/TRUNK-nightly/lastCompletedBuild/cucumber-html-reports/report-feature_45_200197618.html

**Comment by damianszczepanik** [comment]
Incomplete report. Those links won't work

**Comment by escap89** [comment]
Why you closed that topic?
I am asking what could change that:
"report-feature_src-main-java-com-fineos-adminsuite-selenium-cucumber-features-MemberBillBreakdown-feature_1.html"
to:
"report-feature_45_200197618.html"
for us?

Only some plugin versions in Jenkins were changed

**Comment by damianszczepanik** [comment]
Because links you have provided are not valid.
The change you are asking for is a feature which was introduced by the plugin upgrade.

**Comment by escap89** [comment]
Thanks for answer, good to know that it was intentional change.

We are having a tool which is generating hyperlinks based on URI from cucumber.json file which previously was full path to feature.

For now with the new pattern (random numbers) we are not able to generate a valid hyperlink.

Is there a way to restore previous behaviour or could you tell me which version of cucumber reports I have to restore to get previous URLs?

Thanks :)

**Comment by damianszczepanik** [comment]
Downgrade is not supported by this software

**Comment by escap89** [comment]
Can i calculate this new html name format by myself? If not then could you add posibility to generate the name base on cucumber.json parameters (URI or smth else?).
these names are important for us to smoothly move between triage report and cucumber reports for each feature.

It will be grateful if you could help us with that.

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/util/Util.java#L82

**Comment by escap89** [comment]
I've tried calculating names based on toValidFileName(String fileName) 
as a fileName i used old name of the html  but calculated numbers wasn't same as yours..

But anyway i noticed that for the new pattern it will be quite hard to "know" what html will look like:
cucumber-html-reports/report-feature_1_2944501463.html
"report-feature" - hardcoded - it was also there before the change
"_1_" - number of feature, starting from empty "" and then "_1_"  - I won't be able to get this part...
"2944501463" - I believe this part is generated by toValidFileName(String fileName) 


The introduced change doesn't help at all so in my opinion it is a issue, can't find a single reason standing behind the change...

Would be great if you consider allowing us to use old html names as we would like to use newest version of the plugin which is very helpful. For now we will have to download old version of the plugin (have to find out which version introduced that change).

**Comment by damianszczepanik** [comment]
File length on Windows OS has limit so the old strategy has changed

**Comment by escap89** [comment]
Ok I've downgraded our cucumber reports version to 4.0.1 to get previous reports names.
Hopefully you will consider adding possibility of creating html reports as it was back in 4.0.1.

If there was some limit on Windows OS you could cut the name or only for these use the new approach/

I am waiting for new feature with supporting multiple raports for single job as we have retry stage in our pipeline and for now we have to use separated job to not override cucumber reports (pull/344)
But if reports names will still be a hashcoded then I won't be able to upgrade our version.
