### ISSUE TITLE
The format of the Cucumber report when it comes in the Email is not good

### ISSUE THREAD

**Issue by shahmit** [jenkinsci/cucumber-reports-plugin#356]
Hi Team,
Please if you can help here- i am using- maven-cucumber-reporting version 5.0.0. In Jenkins i have the Email-ext plugin. I am using the Content-type as Html, and have provided the path to the overview-feature.html file in the target/cucumber-html-reports folder. However the format of the report which comes in the Email is not good, please see attached for the report format which comes in the email.
Please advice how to fix this?

**Comment by shahmit** [comment]
Cucumber Report

[overview-features.html]Features
[overview-tags.html]Tags
[overview-steps.html]Steps
[overview-failures.html]Failures
Project	Number	Date
DigitalTestAutomation	1	09 May 2020, 22:10
Feature Report
Steps	Scenarios	Features
Feature	Passed	Failed	Skipped	Pending	Undefined	Total	Passed	Failed	Total	Duration	Status
Health Check for Different Portals	4	0	0	0	0	4	1	0	1	21.864	Passed
Tags: [report-tag_2149461210.html]@GUI [report-tag_4175717323.html]@healthCheck [report-tag_4089311534.html]@smoke
Feature Health Check for Different Portals
Tags: [report-tag_2149461210.html]@GUI [report-tag_4175717323.html]@healthCheck [report-tag_4089311534.html]@smoke [report-tag_4074376391.html]@check
21.864
Scenario Outline Member Login to HAP Portal for Agent- Userid- "Jadams"
Steps

**Comment by damianszczepanik** [comment]
Report is dedicated for web browser and I don't have plan to extend support for email.
It uses Bootstrap library so you can take a look and prepare PR if you like on your own.

**Comment by Prashasti07** [comment]
Hi ,
i am facing same issue, while emailing the html report has missing css, and report is not looking good.
has anyone found any solution for this?

**Comment by damianszczepanik** [comment]
Do not sent/attach only html page but also include resoruces

**Comment by Prashasti07** [comment]
hi @damianszczepanik , which all resources so we need to add, Can you please list down the details?

**Comment by damianszczepanik** [comment]
Whole directory where report is stored.
Check https://github.com/damianszczepanik/cucumber-reporting/issues/1086

**Comment by FantaAI** [comment]
@damianszczepanik  @Prashasti07  Do you have work around for this issue, I face the same issue.
I try to use email extension https://plugins.jenkins.io/email-ext/  in Jenkins pipeline.
            emailext mimeType: 'text/html',
            body: '${FILE, path="test-output/emailable-report.html"}',
            subject: currentBuild.currentResult + " : " + env.JOB_NAME,
            to: 'xxx'
            
But the format of the report in email is not good
