### ISSUE TITLE
How can I send Cucumber HTML reports in a email

### ISSUE THREAD

**Issue by donepudi369** [jenkinsci/cucumber-reports-plugin#357]
Hello,

I am using Cucumber reports plugin in Jenkins which provides a HTML reports. How can I send these reports in an email (Email Extension)?

Thanks

**Comment by damianszczepanik** [comment]
There is no direct support for that plugin

**Comment by donepudi369** [comment]
@damianszczepanik  - Thanks for your response. Is there any other option to send the reports through email ? ( maybe using a different plugin or procedure)

I have searched in google but couldn't find any article or information regarding it.

Appreciate your help

**Comment by rafaborrego** [comment]
@donepudi369 
You can change to the master Jenkins node, zip the files and then send them by email:

node('master') {
  dir("../../jobs/app-name/branches/develop/builds/${BUILD_NUMBER}/") {
     zip zipFile: "BDD-reports.zip", dir: "cucumber-html-reports"
    .... // commands to send by email
  }
}
