### ISSUE TITLE
Error cucumber report specific tag

### ISSUE THREAD

**Issue by pauloantunes001** [jenkinsci/cucumber-reports-plugin#358]
Hello,
We’re having some problems with the cucumber reports. When I open the generated html report and enter in a specific tag, there are some scenarios appearing that don’t have the selected tag.

I think it’s a bug, because the filter by tag should leave only the scenarios that have the selected tag.

I am attaching some images to help you understand.
Could you help me with it?

<img width="793" alt="2020-05-25 19_58_49-" src="https://user-images.githubusercontent.com/51340217/82926583-cf77e880-9f55-11ea-8faa-c1e6462e1dc9.png">

<img width="807" alt="2020-05-25 20_01_32-" src="https://user-images.githubusercontent.com/51340217/82926673-eddde400-9f55-11ea-84f1-39dd2ee17300.png">

**Comment by damianszczepanik** [comment]
Attach JSON report

**Comment by pauloantunes001** [comment]
Hello,

The functionality contained repeated names, it generated a problem when counting scenarios by tag

This was the problem.

Thank you.
