### ISSUE TITLE
Skipped step results in failed scenario & feature

### ISSUE THREAD

**Issue by Iluvatari** [jenkinsci/cucumber-reports-plugin#360]
A scenario containing solely passes and skips results in a failed scenario. While it doesn't seem to be directly acknowledged in the plugin's documentation, it seems that other applications of cucumber result in a pass in this case (https://github.com/trivago/cluecumber-report-plugin/issues/70).

I acknowledge that I can handle the build status to be passing either way (using advanced plugin parameter thresholds) but I would like/expect the scenario & feature to be marked pass in this case. 

Running on jenkins version 2.190.1, Cucumber verision 5.0.2
![image](https://user-images.githubusercontent.com/6277304/83817842-6ac23980-a68b-11ea-8fa2-7cd86e447d25.png)

If this change is unacceptable performance, I might suggest this behavior be configurable (strict mode) similar to how cluecumber seems to have handled it in their issue.
If you can point me to where in the code this takes place, I'd be happy to make the change.

**Comment by GokhanAtes** [comment]
Hi, I had the same issue https://github.com/jenkinsci/cucumber-reports-plugin/issues/353.

It would be good for there to be a setting in cucumber report config where you can set the select a button to pass skipped scenarios.

**Comment by damianszczepanik** [comment]
You can configure this by using plugin advanced options as presented on the README file.
If not, you need to clarify better your needs

**Comment by Iluvatari** [comment]
@damianszczepanik  I'm sorry if I was unclear, can you please let me know what wasn't clear?

I'll restate. 

To my understanding, the advanced options (shown below, and hilighted) only allow for a *build result* to pass with X (number or percent) skipped builds. This does nothing to address whether the *scenario* or *feature* are marked as failed. 

If I am wrong, please point me to where in the advanced options addresses this. Perhaps you added an option in the code and didn't push the change?

Again, I'd be more than happy to make the change myself if you point me to where this issue would be addressed.
![Inkedadvanced_options_LI](https://user-images.githubusercontent.com/6277304/84437792-2e4a8c80-abfb-11ea-9e38-6433db2b3928.jpg)

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/Configuration.java#L305 does it look like what you need ?

**Comment by gdombchik** [comment]
I came across the same issue today and appreciate an update and/or approach. Thank you.

**Comment by AyushRawat1** [comment]
I came across the same issue but it was closed 4 days ago and the version went to 3.0 does the version consists of the solution to this query?? because i updated the version and still facing the same issue all test cases are skipped still the report shows failed  status
