### ISSUE TITLE
Questions: In case of test failure how to have meaningful message for the failed step along with the technical error in the jenkins cucumber report

### ISSUE THREAD

**Issue by RahulSharma19021996** [jenkinsci/cucumber-reports-plugin#362]
Suppose a test case got failed and when i open the report and check the failed step to understand the reason behind failure, I would be able to understand the technical error but how i can add some meaning full text as the failure information so any non technical person like PO open the report and will understand the reason behind failure.

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/sample.json#L611
