### ISSUE TITLE
Set setNotFailingStatuses as Skipped but still results in failed scenario 

### ISSUE THREAD

**Issue by AyushRawat1** [jenkinsci/cucumber-reports-plugin#364]
I am setting setNotFailingStatuses as suggested by you on an issue(https://github.com/jenkinsci/cucumber-reports-plugin/issues/360) to SKIPPED and when i see the reports the scenarios is still failing. 

In java code setting:
Configuration configuration = new Configuration(reportOutputDirectory, projectName);
configuration.setNotFailingStatuses(Collections.singleton(Status.SKIPPED));

![rsz_screenshot_from_2020-07-13_12-19-30](https://user-images.githubusercontent.com/32659308/87279136-2173ce00-c504-11ea-8d5e-246d984e2a16.png)

**Comment by AyushRawat1** [comment]
@Iluvatari

**Comment by damianszczepanik** [comment]
Attach JSON file so I can review

**Comment by AyushRawat1** [comment]
[skippedTestsStillFails.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/5026173/skippedTestsStillFails.zip)

**Comment by AyushRawat1** [comment]
@damianszczepanik i have attached the json

**Comment by damianszczepanik** [comment]
It says that the file is not proper cucumber report

**Comment by AyushRawat1** [comment]
[first_run_and_rerun.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/5057179/first_run_and_rerun.zip)

@damianszczepanik so these are the first run and rerun jsons the whole jsons

**Comment by damianszczepanik** [comment]
Fixed, will be released soon
