### ISSUE TITLE
After each build, one item will be added into classification automatically

### ISSUE THREAD

**Issue by zhidongnick** [jenkinsci/cucumber-reports-plugin#365]
Cucumber Report -> Presentation -> Classification, after each build, one item will be added here automatically.
![1](https://user-images.githubusercontent.com/30037176/87380274-bccc7800-c5c4-11ea-9241-938847b9daa8.png)
![2](https://user-images.githubusercontent.com/30037176/87380281-bf2ed200-c5c4-11ea-8e2d-50ecafdb48ee.png)

**Comment by fslev** [comment]
Same here 👍

**Comment by fslev** [comment]
One quick fix would be to use a 'classifications' inside a Set, instead of List (CucumberReportPublisher.class).

I think the problem comes from the 'CucumberReportPublisher.perform'  method where the reportTitle is added inside the classifications list.

**Comment by fslev** [comment]
I could provide a PR, if this approach is feasible.

**Comment by zhidongnick** [comment]
> I could provide a PR, if this approach is feasible.

I see your PR. But I think you can change only one line to fix this bug. Please check attached image.
![2020-07-29_8-19-31](https://user-images.githubusercontent.com/30037176/88742428-c9300380-d174-11ea-98b1-f6ec58b6de44.jpg)

**Comment by zhidongnick** [comment]
src\main\java\net\masterthought\jenkins\CucumberReportPublisher.java
line 458
**if (CollectionUtils.isEmpty(classifications)) {**

**Comment by fslev** [comment]
This is strange:
If the classification list is empty -> then add it to the build report.
That doesn't make sense. If the classification list in not empty (User defines some new classifications inside Jenkins), then do not add it to the report ?

**Comment by zhidongnick** [comment]
> This is strange:
> If the classification list is empty -> then add it to the build report.
> That doesn't make sense. If the classification list is not empty (User defines some new classifications inside Jenkins), then do not add it to the report ?

You are correct. Thanks for your reply.

**Comment by damianszczepanik** [comment]
Fixed in #371 please review and test before releasing
