### ISSUE TITLE
How can i get reports if it run's no dynamic slaves?

### ISSUE THREAD

**Issue by romankydybets** [jenkinsci/cucumber-reports-plugin#366]
HI,

i am running builds on dynamic slaves in jenkins that shutdown and deleted after the build?
how can i get report data?

**Comment by damianszczepanik** [comment]
Good question. Does the report is stored on Jenkins or its agents?

**Comment by Kydybets** [comment]
@damianszczepanik i test it out,
It will store on the master node, because i use only automatic slaves with will be destroyed after the build is done.
So i am able to se the previous builds also

**Comment by damianszczepanik** [comment]
I don't feel like an expert in that area, no idea how to support you

**Comment by Kydybets** [comment]
@damianszczepanik this is not need to support.
i think should be enough to add this into the documentation
