### ISSUE TITLE
Use report title as is in the link to the reports

### ISSUE THREAD

**Issue by sachinsonu** [jenkinsci/cucumber-reports-plugin#372]
When the report title is specified, cucumber-reports-plugin is attaching a random ID to the URL (example- cucumber-html-reports_e75f9acb-16bb-35c0-b92e-3251f7665ba3/overview-features.html) causing issue while trying to predict the reports URL and share the link

Please use the report title as is in the URL to open the reports instead of a random number

**Comment by damianszczepanik** [comment]
Due to some title limitation it was designed as it is time ago
