### ISSUE TITLE
Cucumber.options can not resolve method format

### ISSUE THREAD

**Issue by camohub** [jenkinsci/cucumber-reports-plugin#389]
I need to add json report 
to the Cucumber.options in Cucumber runner class. It looks like

```
package runners;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;


@RunWith(Cucumber.class)
@CucumberOptions(
    features = "src/test/features/",
    glue = {"steps", "hooks"},
    tags = "@admin or @homepage",
    format = {"json:target/cucumber-reports/fast-runner.json"}
)
public class FastRunner
{

}
```
But format keyword is red and IDEA says can not resolve method format like on the picture. What is wrong with that? Thanks for any help.
![Screenshot (343)](https://user-images.githubusercontent.com/8393426/110819379-6c5e0500-828e-11eb-80cf-fa3a4632d8b2.png)

**Comment by damianszczepanik** [comment]
This is about the report, not cucumber - wrong project
