### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by camohub** [jenkinsci/cucumber-reports-plugin#390]
### Feature Request

It would be great if people can add the file with custom CSS or may be a little Javascript to the plugin. I thing it could be possible without much pain. 

1. Store the file. 
2. Join the file when generating the html. 
3. Have a nice custom corporate result. :)

Thank you.

**Comment by damianszczepanik** [comment]
I don't have plan to support it but you can consider to prepare PR about 1 and 2 but rather won't accept 3
