### ISSUE TITLE
Support message formatter

### ISSUE THREAD

**Issue by valentinabojan** [jenkinsci/cucumber-reports-plugin#392]
Hello,

Please correct me if I'm wrong, but I noticed that this report plugin is based on the Cucumber json built-in formatter. However, on the official documentation (https://cucumber.io/docs/cucumber/reporting/) it says that: **_The built-in JSON formatter is deprecated and will be removed in a future release._** The recommended formatter to be used is now **message-formatter**.

Are there any plans to support this formatter as well in your plugin? I'm asking because some keywords are currently not available in the json report, which makes them unavailable in your report as well. Such example is the 'Rule' keyword.

Thanks a lot!

**Comment by damianszczepanik** [comment]
No but may not be needed https://github.com/cucumber/common/tree/main/json-formatter
