### ISSUE TITLE
Unable to see reports when I run tests against a jenkins remote agent

### ISSUE THREAD

**Issue by fabioformosa** [jenkinsci/cucumber-reports-plugin#393]
### Version report

Jenkins and plugins versions report:

```
Jenkins 2.277.3
plugin 5.5.0
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Ubuntu 20.04.1 LTS
```

### Reproduction steps

- I created a jenkins remote agent, as described here https://www.jenkins.io/doc/book/using/using-agents/
- I run cucumber test in that remote agent

### Results

Expected result:

I would like to see cucumber reports event if I run tests in the jenkins agent, instead of master node.

Actual result:

No reports available.
![image](https://user-images.githubusercontent.com/4976513/121867340-28045a00-cd00-11eb-881e-5ed2f58e0994.png)

It seems the plugin looks for reports in the jenkins-master's workspace, not in the jenkins-agent's workspace.
When there's a remote jenkins agent, there are multiple workspaces.

![image](https://user-images.githubusercontent.com/4976513/121867827-a4973880-cd00-11eb-9dee-49a3d9777b16.png)

Is it possibile to browse reports stored into the jenkins agent?

**Comment by damianszczepanik** [comment]
I believe the path to the report is incorrect. I need more details to reproduce and fix the problem. Check the real location of the JSON file and logs

**Comment by fabioformosa** [comment]
The path is specified in my jenkinsfile:
```
post {
    always {
      cucumber fileIncludePattern: 'build/reports/*.json', sortingMethod: 'ALPHABETICAL'
      archiveArtifacts artifacts: 'build/reports/e2eTests.html', allowEmptyArchive: true
    }
```
I point out that I have 2 jenkinsfiles (one for DEV env and another one for QA env). The path is the same in both, but only QA env uses the remote jenkins agent.
So, summarizing, the same path works in DEV, not in QA. 

Have you ever tried to collect report with the plugin when the tests are run against a remote jenkins agent as described here 
https://www.jenkins.io/doc/book/using/using-agents/ ?

**Comment by brunomendola** [comment]
Hi! I solved the problem by moving the global post block with the cucumber step to a post block on the stage running on the remote agent.

**Comment by fabioformosa** [comment]
Awesome @brunomendola.
I close this issue.
