### ISSUE TITLE
How to access the cucumber raw data report on Jenkins

### ISSUE THREAD

**Issue by lgjsherond** [jenkinsci/cucumber-reports-plugin#396]
### Feature Request

For accessing the merged JSON file (after processed several JSON files) for further report generation (PDF)
Send as email body by embedding the feature overview page

**Comment by damianszczepanik** [comment]
What kind of data are you interesting in?

**Comment by lgjsherond** [comment]
Damian,

I prepare the results with separate results collating job. The job prepare the report with several parallel and different jobs. Get the raw/process data help me to prepare HTML email body and PDF report.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by damianszczepanik** [comment]
https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java#L373-L374

This is the place where report is stored
