### ISSUE TITLE
Skipped scenarios are marked as failure instead of Skipped status

### ISSUE THREAD

**Issue by sujithmathew93** [jenkinsci/cucumber-reports-plugin#411]
### Describe your use-case which is not covered by existing documentation.

Incase there are some scenarios that are skipped in the cucumber hooks and all the steps are skipped, the Jenkins Cucumber Report generated using the plugin marks these test cases as failed instead of skipped. Is there any configuration or alternate way to make these tests as pending/skipped instead of fail, something similar to setting 'setSkippedAsNotFailing' as true in POM configuration.

Please provide suggestions or solutions to overcome this type of scenario where user expects to see skipped status for test cases whose steps are not executed and exited at the hooks step instead of viewing it under Failed category.

**Comment by cmsoconsistent** [comment]
Hi @sujithmathew93 - I have the same concerns. I found that there is a fork of the cucumber-reporting (not the cucumber-reports-plugin) project which addresses this concern. I'm uncertain if somehow these updates can be applied to the Jenkins plugin. Take a look:
https://github.com/Datical/cucumber-reporting

I believe it was this discussion that led me there:
https://github.com/jenkinsci/cucumber-reports-plugin/issues/360

I'm following, hoping to get the same answer as you. This plugin would be hugely helpful to us but we intentionally skip multiple tests and them displaying as failed doesn't work for us.

**Comment by damianszczepanik** [comment]
Attach JSON file

**Comment by cmsoconsistent** [comment]
Here is one of ours
[cucumber.json.notareal.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/8633833/cucumber.json.notareal.txt)

**Comment by cmsoconsistent** [comment]
Looks like this in Jenkins
![image](https://user-images.githubusercontent.com/82892494/167001747-86af802e-a124-4c34-9d7e-4afc45637645.png)

**Comment by sujithmathew93** [comment]
[cucumber.json.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/8661430/cucumber.json.txt)
Attached JSON for reference, please provide some solution or update to overcome these kind of scenarios where there is an option to mark intentional skipped tests as pass in Jenkins cucumber-reports-plugin, like we have('setSkippedAsNotFailing') in maven-cucumber-reporting plugin.

**Comment by sujithmathew93** [comment]
Hey @cmsoconsistent , if you notice there is an option to handle skip scenarios as not to be failed while using it with the POM configuration i.e. the maven-cucumber-plugin using 'setSkippedAsNotFailing' as true, it makes work so easy, using that I was able to mark skip tests as pass in the report that gets generated in the Target folder. 
However, similar configuration/option is unavailable in the jenkins-cucumber-plugin, probably Damian can look on similar lines to work and provide an updated version to handle this because probably major coding might be already handy.

**Comment by damianszczepanik** [comment]
Will be released with #413
