### ISSUE TITLE
Skipped Scenario is showing as failure in Jenkins

### ISSUE THREAD

**Issue by AbhiAuto** [jenkinsci/cucumber-reports-plugin#424]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

Cucumber - 5.7.0 version
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

Configured the Jenkins build job with the below configuration to make the build pass if there are skipped steps available 

1. Tick if you want Skipped steps to cause the build to fail - see further down for more info on this

2. The first setting is Skipped steps fail the build - so if you tick this any steps that are skipped during executions will be marked as failed and will cause the build to fail:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/26138640/200028098-7f0f10f8-64ce-4c21-ad95-729776e70cb6.png)

### Expected Results

Should get execution passed report even the steps are skipped 

### Actual Results

Getting failed report even after the configuration has provided as -1 to skip the rule for "Number of Skipped steps " 

<img width="838" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/26138640/200028008-8de43252-7a06-4c1e-a68b-f986ce828e30.png">

**Comment by damianszczepanik** [comment]
Configuration you are using is about build result - as visible on screenshot you have attached. This is not about how the report is visible but how the Jenkins build is set

https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java#L568-L569
