### ISSUE TITLE
"net.masterthought.cucumber.ValidationException: File '{fileName}' is not proper Cucumber report!" when trying to parse json with docString argument

### ISSUE THREAD

**Issue by romanegorov1016** [jenkinsci/cucumber-reports-plugin#425]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  cucumber-report version: 5.7.0
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

  Windows 10 Version 21H2 x64-based systems

### Reproduction steps

Generate report with the next json file:
[
    {
        "keyword": "Feature",
        "type": "feature",
        "description": "",
        "line": null,
        "name": "Screenshots",
        "uri": "Can not be determined",
        "tags": [
            {
                "location": {
                    "line": 1,
                    "column": 1
                },
                "name": "@smoke",
                "id": "3"
            }
        ],
        "elements": [
            {
                "keyword": "Scenario",
                "type": "scenario",
                "description": "",
                "name": "Verify POST request with Body passed as Doc String",
                "tags": [
                    {
                        "name": "@smoke",
                        "astNodeId": "3"
                    }
                ],
                "id": "screenshots;verify-post-request-with-body-passed-as-doc-string",
                "steps": [
                    {
                        "arguments": [],
                        "keyword": "Before",
                        "name": "",
                        "result": {
                            "status": "passed",
                            "duration": 2000000
                        },
                        "line": 190,
                        "match": {
                            "location": "can not be determined with webdriver.io"
                        }
                    },
                    {
                        "arguments": [],
                        "keyword": "Before",
                        "name": "",
                        "result": {
                            "status": "passed",
                            "duration": 1000000
                        },
                        "line": 191,
                        "match": {
                            "location": "can not be determined with webdriver.io"
                        }
                    },
                    {
                        "arguments": [],
                        "keyword": "Before",
                        "name": "",
                        "result": {
                            "status": "passed",
                            "duration": 19000000
                        },
                        "line": 192,
                        "match": {
                            "location": "can not be determined with webdriver.io"
                        }
                    },
                    {
                        "arguments": [],
                        "keyword": "Before",
                        "name": "",
                        "result": {
                            "status": "passed",
                            "duration": 1000000
                        },
                        "line": 193,
                        "match": {
                            "location": "can not be determined with webdriver.io"
                        }
                    },
                    {
                        "arguments": [
                            "{\n  \"title\": \"Test Post Request with Body passed as string\"\n}"
                        ],
                        "keyword": "When",
                        "name": "User sends \"POST\" request to \"https://postman-echo.com/post\" with Body:",
                        "result": {
                            "status": "passed",
                            "duration": 3231000000
                        },
                        "line": "",
                        "match": {
                            "location": "can not be determined with webdriver.io"
                        },
                        "embeddings": [
                            {
                                "data": {
                                    "request": {
                                        "method": "POST",
                                        "serviceUri": "https://postman-echo.com/post",
                                        "body": {
                                            "title": "Test Post Request with Body passed as string"
                                        }
                                    }
                                },
                                "mime_type": "application/json"
                            },
                            {
                                "data": {
                                    "response": {
                                        "statusCode": 200,
                                        "body": {
                                            "args": {},
                                            "data": {
                                                "title": "Test Post Request with Body passed as string"
                                            },
                                            "files": {},
                                            "form": {},
                                            "headers": {
                                                "x-forwarded-proto": "https",
                                                "x-forwarded-port": "443",
                                                "host": "postman-echo.com",
                                                "x-amzn-trace-id": "Root=1-636d0a20-1ae9d23d47cbc70f51b3f3b9",
                                                "content-length": "56",
                                                "accept": "application/json, text/plain, */*",
                                                "content-type": "application/json",
                                                "user-agent": "axios/0.24.0"
                                            },
                                            "json": {
                                                "title": "Test Post Request with Body passed as string"
                                            },
                                            "url": "https://postman-echo.com/post"
                                        },
                                        "headers": {
                                            "date": "Thu, 10 Nov 2022 14:26:40 GMT",
                                            "content-type": "application/json; charset=utf-8",
                                            "content-length": "479",
                                            "connection": "keep-alive",
                                            "etag": "W/\"1df-1hLREZ/P4+Uc6UwBdUsHRWrC4RU\"",
                                            "vary": "Accept-Encoding",
                                            "set-cookie": [
                                                "sails.sid=s%3AIG7Z9___4iF5Ig1LbJetC5swpM7mXjjl.lTN3LbEQG9Ksa0qkA2ADgodv4%2FPIElEF%2BVwjC2kXfHQ; Path=/; HttpOnly"
                                            ]
                                        }
                                    }
                                },
                                "mime_type": "application/json"
                            }
                        ]
                    },
                    {
                        "arguments": [],
                        "keyword": "Then",
                        "name": "Status Code is \"200\"",
                        "result": {
                            "status": "passed",
                            "duration": 2000000
                        },
                        "line": "",
                        "match": {
                            "location": "can not be determined with webdriver.io"
                        }
                    },
                    {
                        "arguments": [],
                        "keyword": "After",
                        "name": "",
                        "result": {
                            "status": "passed",
                            "duration": 144000000
                        },
                        "line": 196,
                        "match": {
                            "location": "can not be determined with webdriver.io"
                        }
                    },
                    {
                        "arguments": [],
                        "keyword": "After",
                        "name": "",
                        "result": {
                            "status": "passed",
                            "duration": 1000000
                        },
                        "line": 197,
                        "match": {
                            "location": "can not be determined with webdriver.io"
                        }
                    },
                    {
                        "arguments": [],
                        "keyword": "After",
                        "name": "",
                        "result": {
                            "status": "passed",
                            "duration": 9152000000
                        },
                        "line": 198,
                        "match": {
                            "location": "can not be determined with webdriver.io"
                        }
                    }
                ]
            }
        ],
        "id": "screenshots",
        "metadata": {
            "browser": {
                "name": "chrome",
                "version": "107.0.5304.107"
            },
            "device": "Device name not known",
            "platform": {
                "name": "windows",
                "version": "Version not known"
            }
        }
    }
]

NOTE: Pay attention on "arguments" parameter:
"arguments": [
                            "{\n  \"title\": \"Test Post Request with Body passed as string\"\n}"
                        ]

### Expected Results

Report was generated

### Actual Results

net.masterthought.cucumber.ValidationException: File '/data/devops-jenkins_home/jobs/mercer-mercer-com-main-ta_smoke-ui_QA/builds/40/cucumber-html-reports/.cache/reports/screenshots_16680758932549849.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:104)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:72)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:97)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:518)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:391)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

### Anything else?

Scenario example:
Scenario: Verify POST request with Body passed as Doc String
    When User sends "POST" request to "https://postman-echo.com/post" with Body:
      """
      {
        "title": "Test Post Request with Body passed as string"
      }
      """
    Then Status Code is "200"

**Comment by damianszczepanik** [comment]
Plugin says that passed file is not proper cucumber report. It is not even proper JSON file because of `arguments` section which you have mention
