### ISSUE TITLE
Storing cucumber HTML report in Jenkins workspace

### ISSUE THREAD

**Issue by Enigmaderockz** [jenkinsci/cucumber-reports-plugin#428]
### What feature do you want to see added?

Currently we see main cucumber HTML report on the main page but it would be good if Cucumber HTML report can be stored in Jenkins workspace or we can fetch reports from Jenkins location so that we can access it anywhere on our machine also

**Comment by damianszczepanik** [comment]
It is stored on Jenkins storage with the build
