### ISSUE TITLE
Missing xml tags in feature file inputs

### ISSUE THREAD

**Issue by allanffg** [jenkinsci/cucumber-reports-plugin#43]
This is what the feature file looks like
![feature-file](https://cloud.githubusercontent.com/assets/10512853/14314507/7ec34d5c-fbef-11e5-860f-2e8f73235762.PNG)

This is what the generated json looks like
` "cells": [
                  "<instrument><instrumentId>TEST1</instrumentId><version>1</version></instrument>"
                ], `

This is what the jenkins plugin produces. Notice the xml tags are missing and it just leave the body.
![jnkins](https://cloud.githubusercontent.com/assets/10512853/14314818/8257a934-fbf1-11e5-8e82-338713ead5b7.PNG)

**Comment by damianszczepanik** [comment]
Why do you expect browser it will display xml format as plain text?
