### ISSUE TITLE
Duration is not displayed correctly

### ISSUE THREAD

**Issue by T00595** [jenkinsci/cucumber-reports-plugin#431]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
 def publishCucumberReport(platform, reportTitle, releaseIdFromJob, bitriseIdFromJob) {
  def reportName = "features_report_${platform}.json"
  def reportAbsolutePath = "reports/${reportName}"
  if (fileExists(reportAbsolutePath)) {
    archiveArtifacts allowEmptyArchive: true, artifacts: "reports/**/*"
    cucumber(fileIncludePattern: reportName,
      jsonReportDirectory: "reports",
      buildStatus: 'UNSTABLE',
      sortingMethod: 'ALPHABETICAL',
      mergeFeaturesById: true,
      failedFeaturesNumber: -1,
      failedScenariosNumber: -1,
      failedStepsNumber: -1,
      pendingStepsNumber: -1,
      skippedStepsNumber: -1,
      undefinedStepsNumber: -1,
      trendsLimit: 1000,
      failedFeaturesPercentage: 100.0,
      failedScenariosPercentage: 10,
      failedStepsPercentage: 100.0,
      pendingStepsPercentage: 100.0,
      skippedStepsPercentage: 100.0,
      undefinedStepsPercentage: 100.0,
      reportTitle: reportTitle,
      classifications: [
        [key: 'Branch', value: "${branch}"],
        [key: 'Platform', value: "${platform}"],
        [key: 'Devices', value: "${device}"],
        [key: 'Release ID', value: "${releaseIdFromJob}"],
        [key: 'Bitrise ID', value: "${bitriseIdFromJob}"],
        [key: 'Execution Type', value: "${execType}"],
        [key: 'Distribuition Group', value: "${distributionGroup}"],
        [key: 'Tags', value: "${tags}"]
      ])
  } else {
    println("Não foram gerados os relatórios do cucumber!")
  }
}
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins, Ruby, Cucumber 5.7.3

### Reproduction steps

`def publishCucumberReport(platform, reportTitle, releaseIdFromJob, bitriseIdFromJob) {
  def reportName = "features_report_${platform}.json"
  def reportAbsolutePath = "reports/${reportName}"
  if (fileExists(reportAbsolutePath)) {
    archiveArtifacts allowEmptyArchive: true, artifacts: "reports/**/*"
    cucumber(fileIncludePattern: reportName,
      jsonReportDirectory: "reports",
      buildStatus: 'UNSTABLE',
      sortingMethod: 'ALPHABETICAL',
      mergeFeaturesById: true,
      failedFeaturesNumber: -1,
      failedScenariosNumber: -1,
      failedStepsNumber: -1,
      pendingStepsNumber: -1,
      skippedStepsNumber: -1,
      undefinedStepsNumber: -1,
      trendsLimit: 1000,
      failedFeaturesPercentage: 100.0,
      failedScenariosPercentage: 10,
      failedStepsPercentage: 100.0,
      pendingStepsPercentage: 100.0,
      skippedStepsPercentage: 100.0,
      undefinedStepsPercentage: 100.0,
      reportTitle: reportTitle,
      classifications: [
        [key: 'Branch', value: "${branch}"],
        [key: 'Platform', value: "${platform}"],
        [key: 'Devices', value: "${device}"],
        [key: 'Release ID', value: "${releaseIdFromJob}"],
        [key: 'Bitrise ID', value: "${bitriseIdFromJob}"],
        [key: 'Execution Type', value: "${execType}"],
        [key: 'Distribuition Group', value: "${distributionGroup}"],
        [key: 'Tags', value: "${tags}"]
      ])
  } else {
    println("Não foram gerados os relatórios do cucumber!")
  }
}`

### Expected Results

the duration appears without the hh:mm:ss:nn separator
today it appears 000:000.00 I would like it to appear 00H:00M00:ss

### Actual Results

duration appears with correct separation and values in mm:ss:nn

### Anything else?

![image](https://user-images.githubusercontent.com/86666227/225299307-fe76e15b-097f-4e53-8040-2974e872b0ba.png)

**Comment by damianszczepanik** [comment]
Attach JSON file

**Comment by T00595** [comment]
> Attach JSON file
[features_report.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/10990107/features_report.zip)

**Comment by damianszczepanik** [comment]
Metrics are not present as they are rather obvious based on the number format http://damianszczepanik.github.io/cucumber-html-reports/overview-features.html
