### ISSUE TITLE
uninstallation pending from long time

### ISSUE THREAD

**Issue by Eshwar1193** [jenkinsci/cucumber-reports-plugin#434]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Any agent

### Reproduction steps

Manage plugin --> plugin manager --> Installed plugin --> search for cucumber report plugin --> click uninstall

### Expected Results

i would like to reinstall cucucmber report plugin. so i have uninstalled the plugin but it is still in "uninstallation pending" from long time.

### Actual Results

Actual issue is with uninstalling the cucumber-report-plugin. uninstallation is in process from long time

### Anything else?

nothing

**Comment by damianszczepanik** [comment]
Rather Jenkins responsibility, then the plugin
