### ISSUE TITLE
net.masterthought.cucumber.ValidationException: File '/target/test-classes/test.json' is not proper Cucumber report!

### ISSUE THREAD

**Issue by Shawnfoto** [jenkinsci/cucumber-reports-plugin#439]
### Jenkins and plugins versions report

My runner is:
```java
@SpringBootApplication
@RunWith(Cucumber.class)
@CucumberOptions(features = "src/test/resources/features",
    glue = { "testSvc/cucumber"},
    plugin = {"summary", "pretty", "json:target/cucumber-reports/cucumber-reports.json",
        "html:target/cucumber-reports/index.html",
        "junit:target/cucumber-reports/feature-overview.html"})
public class TestOpsTestRunner {
}
```

src
  └── test
      └── resources
          ├── features
          │   └── myFeature.feature
          └── test.json

I'd like to test my json file from resources to cucumber test step definition.
My json file in stored in resources dir
Has anyone encountered this issue before?

### What Operating System are you using (both controller, and any agents involved in the problem)?

MacOS Monterey 12.3
 <artifactId>maven-cucumber-reporting</artifactId>
            <version>5.6.2</version>

### Reproduction steps

One of steps import file form resources:
File testReqJsonFile = ResourceUtils.getFile("classpath:test.json");
testRequest = objectMapper.readValue(testReqJsonFile, TestRequest.class);

### Expected Results

I can see the 
report-feature_245631.html, 
overview.tags.html
overview-steps.html
overview-features.html
overview-failures.html

### Actual Results

only see report-feature.html, and it content shows:
net.masterthought.cucumber.ValidationException: File '/target/test-classes/test.json' is not proper Cucumber report!

**Comment by damianszczepanik** [comment]
Attach JSON file

**Comment by Shawnfoto** [comment]
`
{
  "data": {
    "consumerDirected": false,
    "user": {
      "identityKey": "111111111",
      "dateOfBirth": "19801110",
      "emailAddresses": [
        {
          "email": "testi@test.com",
          "tenure": "20180916"
        }
      ],
      "mobileNumbers": [
        {
          "tenure": "20010101",
          "number": "1111111111"
        }
      ]
    },
    "card": {
      "pan": "4111112002111112",
      "expiry": "0328",
      "type": "consumer-credit",
      "network": "VISA",
      "name": {
        "first": "Hello",
        "last": "World"
      },
      "embossedName": "Hello World",
      "address": {
        "line1": "333 st",
        "city": "test",
        "region": "CA",
        "postalCode": "94444",
        "countryCode": 840,
        "tenure": "20170817"
      }
    }
  }
}
`

**Comment by damianszczepanik** [comment]
Does not look like proper cucumber report
