### ISSUE TITLE
Colour scheme in HTML reports are not proper

### ISSUE THREAD

**Issue by mnttnm** [jenkinsci/cucumber-reports-plugin#44]
We are using cucumber JVM plugin on Jenkins with version 2.1.0.

The HTML reports which this plugin publishes have improper colour schemes. Colours are too bright and contrast is not perfectly balanced. In some cases, it is even difficult to read the step at which test failed (Black on dark Red).
<img width="1190" alt="screen shot 2016-04-07 at 8 27 28 am" src="https://cloud.githubusercontent.com/assets/8184277/14339383/c0d8a1a4-fc9b-11e5-9563-3d43fbe2cc89.png">

It will be good if we can improve colour schemes of the HTML reports to make them look more pleasant.

**Comment by damianszczepanik** [comment]
Colors have been recently updated so if you still don't like them, add comments here damianszczepanik/cucumber-reporting/issues/383
