### ISSUE TITLE
Security Violations and Operational Risks

### ISSUE THREAD

**Issue by dietmarpradler** [jenkinsci/cucumber-reports-plugin#441]
Hello,
we are using the Jenkins plugin cucumber-reports provided by you in version 5.7.5. 
Through a security scan with JFrog-XRAY we have encountered security vulnerabilities and operational risks.
The current security policy of our company prohibits the use of plugins with vulnerabilities.
I ask to fix the vulnerabilities and operational risks in this plugin.
Thank you very much for your support.

Best regards 
Dietmar Pradler 

[Maven_net.masterthought.jenkins_cucumber-reports_version-5.7.5_v001113_2023-07-26.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/12170032/Maven_net.masterthought.jenkins_cucumber-reports_version-5.7.5_v001113_2023-07-26.zip)
[Jenkins Environment.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/12170043/Jenkins.Environment.txt)

**Comment by damianszczepanik** [comment]
For the security issues follow https://www.jenkins.io/security/
