### ISSUE TITLE
Can't generate reports for rerun and 1st attempt

### ISSUE THREAD

**Issue by JasonSmiley208** [jenkinsci/cucumber-reports-plugin#45]
so cucumber generates a rerun report which allows developers to run all the tests which failed.

In my case, I run all my tests, compile all tests which failed into rerun.txt which I then use to rerun all the failed tests. If all the failed tests then pass the 2nd time around, I want Jenkins to mark the job as a success instead of failure.

Right now, there is no way to do this and generate both reports. If I could add the plugin twice, and make one optional, I believe my problem would be solved (In Theory, 1st generation of the report causes the build to fail. The 2nd generation of the report marks the build from failed to passing. In the case where I do not need a 2nd run, then by saying the 2nd report is optional, the build would still be marked as passing)

**Comment by JasonSmiley208** [comment]
I figured out a good way to do this actually. I have a shell script which kicks off my tests and returns an exit code of 0 or "1" based on the end state.

I checked the "ignore failures" checkbox to give me an "Unstable"state. This works very well for me.

**Comment by PopescuMarius** [comment]
hi, do you have more info on this ?

I just migrated from 1.1.5 to 1.2.5 and now I can generate the file with failed tests. 
Should I create a separate runner only for the failed tests ? How can I mark the build to fail only if a feature failed twice ?

Tks

**Comment by damianszczepanik** [comment]
This version is not supported

**Comment by PopescuMarius** [comment]
Can you add more info ? What versiob is not supported ?
