### ISSUE TITLE
environment variables as parameter

### ISSUE THREAD

**Issue by AvihayTsayeg** [jenkinsci/cucumber-reports-plugin#46]
when trying to set the relative path using build environment parameter getting error

![image](https://cloud.githubusercontent.com/assets/702139/14497324/3c9ed206-019f-11e6-854b-ebdb5e4b1f4f.png)

![image](https://cloud.githubusercontent.com/assets/702139/14497368/6853df04-019f-11e6-8335-68e260baaea4.png)

**Comment by damianszczepanik** [comment]
I need more details for this request

**Comment by AvihayTsayeg** [comment]
Hi thx for the reply,

If you fill in the "Json Report Path" a build environment parameter it is treated as a string.
e.g. if I fill in ${the_path_to_the_report} it fails with no report found for 
[workspace path]/${the_path_to_the_report}

[it is similar to other issue which was classified as "Enhancement" in the old repo](https://github.com/damianszczepanik/cucumber-reporting-jenkins/issues/116)

**Comment by damianszczepanik** [comment]
Variables are not supported by plugin configuration and there is no plan to make it work in near future

**Comment by damianszczepanik** [comment]
Try with newest release, there were made some improvements so I believe paths are not needed any more

**Comment by AvihayTsayeg** [comment]
Thx, I will check it
