### ISSUE TITLE
Feature file named in Korean directs to wrong feature report page

### ISSUE THREAD

**Issue by ryejoon** [jenkinsci/cucumber-reports-plugin#47]
Hi. 

My feature file is named in Korean. The initial Feature Statistics page displays my features correctly, but when I click the feature to view the 'Feature Report Page', it directs to a wrong html page. 

The URL goes like below. I think the plugin replaces Korean characters into dash(-), which leads to same feature report for same length (but different) of Korean feature file names. 

.../cucumber-html-reports/feature-calendar------_outline-feature.html

**Comment by damianszczepanik** [comment]
Attach json file
