### ISSUE TITLE
VelocityException in CucumberReport

### ISSUE THREAD

**Issue by PeterDobos** [jenkinsci/cucumber-reports-plugin#470]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins 2.426.1
 CucumberReport 5.8.0
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins server is on Linux, Jenkins agent is on a Windows server or in a Linux container.

### Reproduction steps

Cannot reproduce consistently. Builds randomly started failing.

### Expected Results

No VelocityException

### Actual Results

11:05:55 [CucumberReport] Using Cucumber Reports version 5.8.0
11:05:55 [CucumberReport] JSON report directory is ""
11:05:55 [CucumberReport] Copied 1 properties files from workspace "W:\jenkins-docker\workspace\BUD_79_INT_IBP_RTI_UI_INTEGRATION_PROFILES_PAT_CUC_J2@25" to reports directory "/var/jenkins_home/jobs/BUD_79_INT_IBP_RTI_UI_INTEGRATION_PROFILES_PAT_CUC_J2/builds/57/cucumber-html-reports/.cache"
11:05:55 [CucumberReport] Copied 1 files from workspace "W:\jenkins-docker\workspace\BUD_79_INT_IBP_RTI_UI_INTEGRATION_PROFILES_PAT_CUC_J2@25" to reports directory "/var/jenkins_home/jobs/BUD_79_INT_IBP_RTI_UI_INTEGRATION_PROFILES_PAT_CUC_J2/builds/57/cucumber-html-reports/.cache"
11:05:55 [CucumberReport] Processing 1 json files:
11:05:55 [CucumberReport] /var/jenkins_home/jobs/BUD_79_INT_IBP_RTI_UI_INTEGRATION_PROFILES_PAT_CUC_J2/builds/57/cucumber-html-reports/.cache/target/cucumber-json-report.json
11:05:55 ERROR: Build step failed with exception
11:05:55 org.apache.velocity.exception.VelocityException: The specified class for ResourceManager (org.apache.velocity.runtime.resource.ResourceManagerImpl) does not implement org.apache.velocity.runtime.resource.ResourceManager; Velocity is not initialized correctly.
11:05:55 	at org.apache.velocity.runtime.RuntimeInstance.initializeResourceManager(RuntimeInstance.java:824)
11:05:55 	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:282)
11:05:55 	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:749)
11:05:55 	at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:122)
11:05:55 	at net.masterthought.cucumber.generators.AbstractPage.<init>(AbstractPage.java:61)
11:05:55 	at net.masterthought.cucumber.generators.ErrorPage.<init>(ErrorPage.java:18)
11:05:55 	at net.masterthought.cucumber.ReportBuilder.generateErrorPage(ReportBuilder.java:262)
11:05:55 	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:113)
11:05:55 	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:563)
11:05:55 	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:434)
11:05:55 	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
11:05:55 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
11:05:55 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
11:05:55 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
11:05:55 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
11:05:55 	at hudson.model.Build$BuildExecution.post2(Build.java:179)
11:05:55 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
11:05:55 	at hudson.model.Run.execute(Run.java:1918)
11:05:55 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
11:05:55 	at hudson.model.ResourceController.execute(ResourceController.java:101)
11:05:55 	at hudson.model.Executor.run(Executor.java:442)
11:05:55 Build step 'Cucumber reports' marked build as failure

### Anything else?

Hello, 
I don't think that this is a real failure in the CucumberReport plugin. My guess is that something is wrong in our local environment settings. Any idea what can be the root cause of this issue? Perhaps another older Velocity jar is on the class path?
Best regards
Peter Dobos

**Comment by damianszczepanik** [comment]
First try to upgrade the Jenkins and the plugin. I use recent Jenkins LTS version for testing

**Comment by PeterDobos** [comment]
Hello, Thanks for your answer. It seems, that after the (container based) Jenkins restart these strange VelocityExceptions disappeared.
