### ISSUE TITLE
Is it possible to add 2 new runner files in jenkins file

### ISSUE THREAD

**Issue by hunterabhi212223** [jenkinsci/cucumber-reports-plugin#475]
As we know when any feature file failed we are storing in a text file. To run that failed.txt file we are using 2nd runner file. If we run second runner file it is executing the failed one only.
Is there any config set up in jenkins file way after completion of first runner it will trigger second runner file to run failed one
Below is my 2 runner files

// Runner1.java
https://github.com/RunWith(Cucumber.class)
@CucumberOptions(
features = "src/test/resources/features",
glue = "stepDefinitions",
tags = "https://github.com/Firstset",
plugin = {"pretty", "html:target/cucumber-reports", "rerun:target/rerun1.txt"}
)
public class Runner1 {
}

// RerunFailedTests1.java
https://github.com/RunWith(Cucumber.class)
@CucumberOptions(
features = "@target/rerun1.txt",
glue = "stepDefinitions",
plugin = {"pretty", "html:target/cucumber-reports-rerun"}
)
public class RerunFailedTests1 {
}

**Comment by damianszczepanik** [comment]
This is a question to cucumber project. This one is about reporting
