### ISSUE TITLE
5.8.4-test published as latest plugin version

### ISSUE THREAD

**Issue by kutzi** [jenkinsci/cucumber-reports-plugin#494]
### Jenkins and plugins versions report

When I check via jenkins-plugin-cli or in the Jenkins Manage/Plugins page, 5.8.4-test is announced as the latest version.
I assume that this is an error? I don't want to install sth. on my production Jenkins which is labeled as 'test'

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Check for plugin updates

### Expected Results

5.8.4

### Actual Results

5.8.4-test

**Comment by damianszczepanik** [comment]
This version should not be available as recent, 5.8.5 has been just released

Thank you for this report
