### ISSUE TITLE
NullPointerException whilst generating reports

### ISSUE THREAD

**Issue by ojbMMXV** [jenkinsci/cucumber-reports-plugin#5]
Relates to [#120](https://github.com/damianszczepanik/cucumber-reporting-jenkins/issues/120) on the obsolete fork.

Getting very similar looking results on version 1.0.0. Has only occurred since upgrading from 0.0.19. Project is being built on the master node. 
The issue seems to resolved when a file include pattern `**/cucumber-report.json` is manually specified. If the include pattern is left blank, then `**/*.json` should be the default according to the field info, however I'm unable to confirm this. Our file exclude pattern is also left blank.

Build snippet:

    [CucumberReportPublisher] Found 6 json files.
    ...
    [CucumberReportPublisher] Generating HTML reports
    [CucumberReportPublisher] there was an error generating the reports: java.lang.NullPointerException
    net.masterthought.cucumber.ReportBuilder.getBuildStatus(ReportBuilder.java:136)
    net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:139)
    hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:772)
    hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:736)
    hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1030)
    hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:685)
    hudson.model.Run.execute(Run.java:1757)
    hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:519)
    hudson.model.ResourceController.execute(ResourceController.java:88)
    hudson.model.Executor.run(Executor.java:234)
    Build step 'Publish cucumber results as a report' changed build result to FAILURE

**Comment by damianszczepanik** [comment]
Plugin found 6 json files and I expect that some of them are not valid and that's why it crashes. Check what is going on with this.

**Comment by ojbMMXV** [comment]
Okay thanks. Yeah this was the case, as some of our JUnit tests that run alongside our Cucumber/Selenium tests were referencing some JSON files in the generated resources. 

It would be nice to have it output something a bit more verbose, though. If this NPE could be caught and logged in greater detail, that would be nice. I'd be willing to create a pull request for this.
