### ISSUE TITLE
Can you include JSON file name as one extra column in the report ?

### ISSUE THREAD

**Issue by yulinqi** [jenkinsci/cucumber-reports-plugin#50]
Hi, 

I love the plugin and thank you for the work. I have a situation that I use cucumber rake to run same feature and scenario for many different configs or clients. The only place I can tell which report is for which config/client is from the file name of the JSON report.

Example:

report_config_a.json ( with login scenario/feature)
report_config_b.json ( with login scenario/feature)
report_config_c.json ( with login scenario/feature)
...

Without including the file name in the report table, I can't tell which report line is for which config/client, and the feature being run is exactly same.

thanks
Yulin
yulin_qi@yahoo.com
![cucumber_report](https://cloud.githubusercontent.com/assets/19176719/14999717/010f291a-1159-11e6-90ed-c72cae7d7018.png)

**Comment by damianszczepanik** [comment]
There is no full and good support for such case. Have you tried to set ``Configuration.setParallelTesting(true)`` to get what you need?

**Comment by yulinqi** [comment]
Hi, Damian 

Indeed it worked out pretty well. Another device column is added, and I can use that to represent clients.

Thank you so much !
-yulin
