### ISSUE TITLE
Cannot view embedded images

### ISSUE THREAD

**Issue by Blackbaud-KimberlyHammer** [jenkinsci/cucumber-reports-plugin#51]
It sounds like we're experiencing a similar issue as [Embedded images #29](https://github.com/jenkinsci/cucumber-reports-plugin/issues/29), but I don't see an actually solution.

"Rather than link to the file it's including the actual file output. In Ruby in order to embed the image I had to encode it as base64. Could that be the issue?"

What does this mean? How do we fix the issue?

**Comment by damianszczepanik** [comment]
Updated comments i #39
