### ISSUE TITLE
Feature request - Include original feature file content with link to unrolled example

### ISSUE THREAD

**Issue by tombarber** [jenkinsci/cucumber-reports-plugin#53]
Hi, firstly apologies if this is not the right place for this as I know this isn't an "issue" as such, but rather a request for a feature I think would be very useful.

I would LOVE it if it were possible to include the original unrolled ScenarioOutline + examples tables at the top of the cucumber report, with example rows highlighted based on whether they passed or failed with links to follow on each row which would take you to the full unrolled test if you wanted to see it.

The reason I think this would be so great is that I would like to use these reports to share with non developers what the specification for the system is and the unrolled test examples from a ScenarioOutline make it difficult to quickly get an understanding compared to the original feature file.

I'd be more than happy to help out in developing this if given a few pointers to get started.

Thanks

Tom

**Comment by damianszczepanik** [comment]
Not sure what you expect. Provide screenshot with new details

**Comment by tombarber** [comment]
Hi Damian,

So, if I have a feature file with a ScenarioOutline with a large number of examples it's still quick to see all the acceptance criteria at a glance:
![image](https://cloud.githubusercontent.com/assets/1730631/15835666/e3ab14b6-2c28-11e6-8d63-dff6d5c6d74c.png)

Currently, when viewing the cucumber report for the same it unrolls each example:
![image](https://cloud.githubusercontent.com/assets/1730631/15835724/2e00db04-2c29-11e6-8f36-a1ea65915302.png)

This means that it's hard to appreciate the overall picture of what the system does as you have to scroll through each example, especially when there is a "Background" as this is repeated for each test also.

For me personally, I think it would be great if the cucumber report could have the individual tests minimised, but at the top of the report show the original feature with each example row coloured according to the test result. Clicking on a row (or link added to each) could then take the user to the unrolled test case below.

**Comment by damianszczepanik** [comment]
Cucumber report does not have reference to the original feature file so your request cannot be possible to implement. What I can suggest is to pass feature file as the error message (that would be strange but works) or pass as the embedding (internal or external resource)
