### ISSUE TITLE
Remove before and after hooks called

### ISSUE THREAD

**Issue by gustavoriveray** [jenkinsci/cucumber-reports-plugin#54]
How can I stop printing in the report the before and after hooks being called on each scenario?

**Comment by damianszczepanik** [comment]
Stop calling it for each scenario :)

**Comment by gustavoriveray** [comment]
I can't just stop calling hooks, they are there for a reason.

What im saying is, for a test that looks like

![Image of terminal](https://photos-1.dropbox.com/t/2/AAA03ogrN8TM4gpX7mg0jEQAInhmeMODskMIIlXos0ClCA/12/223198572/png/32x32/3/1464375600/0/2/Screen%20Shot%202016-05-27%20at%209.48.09%20AM.png/EN_Z1KcBGOMcIAcoBw/JuJ5J1xNMQxdabaWih2QQmg0c43Eeqpl1aaQcFVZDMU?size_mode=3&size=1280x960) 

in the terminal or like this

![Image of html cucumber report](https://photos-5.dropbox.com/t/2/AAAlLAhy1U3vA8xj8gwMJQ3d-FQUBt40ig9DtjNm6LXBNw/12/223198572/png/32x32/3/1464375600/0/2/Screen%20Shot%202016-05-27%20at%209.50.08%20AM.png/EN_Z1KcBGOMcIAcoBw/5t0XokiabW-CSSpb0b0Y9NlL7d48KlkaCde2WCrz7_4?size_mode=3&size=1280x960) 

In the regular Cucumber's HTML report

It looks like this on this plug-in's report

![Image of plugin report](https://photos-4.dropbox.com/t/2/AAARWrmQU24PCc9031WX631mfZ5MT_jDfWdyLoe41CtNMw/12/223198572/png/32x32/3/1464375600/0/2/Screen%20Shot%202016-05-27%20at%209.55.51%20AM.png/EN_Z1KcBGOMcIAcoBw/NYpvL7AWKDjWaSgVYs4uV1wX_DaNs9-Q45g7owhFaZI?size_mode=5&size=32x32)

I just want to make those extra lines to don't show

**Comment by damianszczepanik** [comment]
Upgrade the plugin. Never version should make you happier
