### ISSUE TITLE
cucumber ruby support

### ISSUE THREAD

**Issue by cartoloupe** [jenkinsci/cucumber-reports-plugin#56]
I noticed these two issues are closed: 
- https://github.com/jenkinsci/cucumber-reports-plugin/issues/41
- https://github.com/damianszczepanik/cucumber-reporting/pull/316

From what I can tell, they are duplicates, and address JSON parsing for cucumber-ruby based JSON files. I am currently running into what seems like the same error trace. The issues are closed, but, I can't tell if the problem has been resolved. 

I am running cucumber-jvm-reports plugin v2.3.0, and am seeing an error like this:
```
net.masterthought.cucumber.ValidationException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 340 path $[0].elements[0].before[0].match.location
	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:41)
```

Is 2.3.0 expected to parse cucumber results from ruby? If so, might I be observing a new error?

**Comment by damianszczepanik** [comment]
Check with new version that has been already released and if still not working, attach JSON file

**Comment by damianszczepanik** [comment]
Looks like the problem is solved
