### ISSUE TITLE
Passed Scenarios are showing as Red in Pie Chart

### ISSUE THREAD

**Issue by emoshaya-cognito** [jenkinsci/cucumber-reports-plugin#6]
Any reason why we're seeing red in the report pie chart even though we have passing scenarios? shouldn't this show as green?

![cucumber_report_screenshot](https://cloud.githubusercontent.com/assets/8818542/11715853/55caa666-9f3d-11e5-995c-fce34ed53695.jpg)

**Comment by damianszczepanik** [comment]
Attach json file

**Comment by emoshaya-cognito** [comment]
[cucumber_json.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/58100/cucumber_json.txt)

**Comment by emoshaya-cognito** [comment]
any update on this @damianszczepanik ?

thanks

**Comment by damianszczepanik** [comment]
Could not reproduce with current snapshot so check with the most recent release or next one
