### ISSUE TITLE
CSP settings in versions 2.4 and 2.5

### ISSUE THREAD

**Issue by wp-davisona** [jenkinsci/cucumber-reports-plugin#60]
In version 2.4 the CSP settings have been changed to:
System.setProperty("hudson.model.DirectoryBrowserSupport.CSP",
                "sandbox; script-src 'self' 'unsafe-inline'; default-src 'self'; img-src 'self'; style-src 'self';");
https://github.com/jenkinsci/cucumber-reports-plugin/blob/cucumber-reports-2.5.0/src/main/java/net/masterthought/jenkins/CucumberReportBaseAction.java#L38

This causes the reports to fail to display and various warnings in the browser console:

`Blocked script execution in <snip>...feature-overview.html because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`
`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-j/f2UKtjBQylWfAd5G37rBG4+XD7tRKxQodoTIMdjF4='), or a nonce ('nonce-...') is required to enable inline execution`
...etc...

However, the CSP settings should not be changed at all by this plugin. These are end-user settings. If I try to correct the incorrect settings myself (either through Jenkins startup options or via the script console) and then use this plugin, this code changes the setting back, undoing my correction.

This can also cause conflicts with other plugins that may need different CSP settings and/or may change a user's deliberate CSP configurations.

I would advise removing this setProperty line altogether and have a note in the Readme to tell users to configure their Jenkins accordingly.

**Comment by arran-huxtable** [comment]
+1, this is the responsibility of Jenkins (as mentioned in their own help pages like https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy)

**Comment by damianszczepanik** [comment]
Duplicate of damianszczepanik/cucumber-reporting/issues/472
