### ISSUE TITLE
Cannot see the pie in the html report, cannot access the attachments from the report generated by the Cucumber jvm plugin

### ISSUE THREAD

**Issue by pgandarillas** [jenkinsci/cucumber-reports-plugin#61]
I have some scripts to automate UI test cases, I'm using ruby and cucumber. A job was created in jenkins to execute these scripts and is set up to generate cucumber reports as a post build actions. I can see the results but the pie at the top of the report is not displayed at all (see image). Also, my scripts are set to take screenshots when failing, the attachment is displayed as a link in the report but the link is broken, and the screenshots were not save.
Any suggestion/advice please?
![image](https://cloud.githubusercontent.com/assets/9287729/16228178/6ee85bf0-3783-11e6-8847-cd259201beb9.png)

![image](https://cloud.githubusercontent.com/assets/9287729/16228252/ebc704fa-3783-11e6-9fb1-f119b6b5aef5.png)

**Comment by richardhunt** [comment]
I'm having the same issues, took a look at my console in Chrome and found the following:
```
jenkins.xxx.com/:1 Blocked script execution in 'http://jenkins.xxx.com/job/Staging%20-%20Full%20Regression%20Suite/cucumber-html-reports/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
jenkins.xxx.com/:1 Blocked script execution in 'http://jenkins.xxx.com/job/Staging%20-%20Full%20Regression%20Suite/cucumber-html-reports/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

**Comment by richardhunt** [comment]
@pgandarillas Potentially a duplicate report? https://github.com/damianszczepanik/cucumber-reporting/issues/472

**Comment by pgandarillas** [comment]
@richardhunt could be, but how about the attachments links being broken? Is that related to?
BTW Im using Jenkins 2.9 and cucumber-reports:2.5.0

**Comment by richardhunt** [comment]
Appears to be.  I'm using Jenkins 2.10 and cucumber-reports 2.5.0, and still having the same issues.

**Comment by pgandarillas** [comment]
is there any version in which this was working?

**Comment by damianszczepanik** [comment]
New version has been published, please upgrade
