### ISSUE TITLE
Jenkins Folder Plugin support

### ISSUE THREAD

**Issue by dbut023** [jenkinsci/cucumber-reports-plugin#62]
Support for jenkins folders is a bit erratic. The reports generally work however the links "Jenkins", "Previous results" and "Last results" have incorrect URLs
e.g. For the job TEST_V3 in the folder TEST
The job url is:
/job/TEST/job/TEST_V3/

The url to the reports is:
http://jenkins:8080/job/TEST/job/TEST_V3/259/cucumber-html-reports/

however the links in the navbar are:
```
      <ul class="nav navbar-nav navbar-right">
                  <li role="presentation"><a href="/job/TEST_V3/259">Jenkins</a></li>
                      <li role="presentation"><a href="/job/TEST_V3/258/cucumber-html-reports/features-dummy-feature.html">Previous results</a></li>
                    <li role="presentation"><a href="/job/TEST_V3/cucumber-html-reports/features-dummy-feature.html">Last results</a></li>
                <li role="presentation" ><a href="feature-overview.html">Features</a></li>
        <li role="presentation" ><a href="tag-overview.html">Tags</a></li>
        <li role="presentation" ><a href="step-overview.html">Steps</a></li>
        <li role="presentation" ><a href="failures-overview.html">Failures</a></li>
      </ul>
```
instead of /job/TEST_V3/xxx

**Comment by damianszczepanik** [comment]
Link ``/job/TEST/job/TEST_V3/`` is quite strange. How did you created such url?

**Comment by dbut023** [comment]
Using the Folders plugin (https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Folders+Plugin) I created a folder called "TEST" and then created the job "TEST_V3" within the folder.

As well as manually created folder like the above, any user of the Multibranch plugin (and a couple of others) will also find themselves using job folders.

**Comment by damianszczepanik** [comment]
Looks like the support should be added - will try to use relative links instead of the one that starts from /

**Comment by damianszczepanik** [comment]
Have you tried to configure path via https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.groovy#L17 ?

**Comment by dbut023** [comment]
I've had a toy with that but that would just mean I'd have to determine in each project what the fake basePath that includes the folder would be.

I'm just testing a modification which gets Jenkins to generate all the project URLs needed which means that the only URL manipulation inside the plugin is adding "cucumber-html-reports/" etc.

All working I'll tidy it up tonight and send over a pull request .

**Comment by damianszczepanik** [comment]
@dbut023 damianszczepanik/cucumber-reporting/pull/501 should fix this problem - let me know when you test next release
