### ISSUE TITLE
Scenarios with failed Background are counted as Passed Scenarios

### ISSUE THREAD

**Issue by npgarcia** [jenkinsci/cucumber-reports-plugin#65]
I noticed that when I have a scenario with a failed Background, in the summary table the scenario is counted as Passed and the status of the feature is Failed (which is expected). I was wondering if is it possible to count a scenario with a failed Background as Failed and not Passed so it matches the feature status?

**Comment by damianszczepanik** [comment]
Similar problem to damianszczepanik/cucumber-reporting/issues/497

Why do you want to count passed scenario as failed? If the background is failed then the scenario should fail as well

**Comment by stevejensen22** [comment]
> Why do you want to count passed scenario as failed? If the background is failed then the scenario should fail as well

I think that is what he is saying. He just wants the report to show the failure on the scenario's `FAILED` column if the background for that scenario fails.

I agree with this logic.

**Comment by damianszczepanik** [comment]
So what is the status of scenario for which the background has failed? As you see, columns are about scenarios, not backgrounds.

Imagine the situation where you have 2 scenarios with two backgrounds. All pass. Would you expect to have in summary 4 or 2 passing scenarios?

**Comment by npgarcia** [comment]
Lets think of scenario as a set of steps (background + scenario). If the background fails to be completed, then the scenario cannot be considered as passed because the scenario did not completely run; it failed to start. So why counting it as a passed scenario and not failed or undefined?

**Comment by damianszczepanik** [comment]
It's easy to say but considering json format it is not. I recommend to generate proper report by tests: If you want fail test, mark the scenario as failed. When you have failed background and passed scenario you should not expect to have scenario failed

**Comment by npgarcia** [comment]
I am having trouble to think of a passing scenario with a failing background. Can you please elaborate?

**Comment by stevejensen22** [comment]
I would agree with @npgarcia. `Background` steps are nothing more than setup steps that are shared between `Scenarios`. Therefore if the `Background` (setup) fails for a `Scenario` then the entire `Scenario` must fail.  Cucumber won't even let the scenario run if the `Background` fails so it could never truly `Pass`.

**Comment by damianszczepanik** [comment]
If so then the report should not have situation when background fails a and scenario passes. So there's nothing to do with report.  You need to properly generate results stored in json

**Comment by stevejensen22** [comment]
>If so then the report should not have situation when background fails a and scenario passes

This is the exact reason this issue was created.

See below: The `Steps` and `Status` show `Failed` but the `Scenario`'s `Passed` count still shows `1` 👇 

![steps_fail_scenario_passes](https://cloud.githubusercontent.com/assets/10365264/17252874/8e2bcce4-556b-11e6-8bc0-8893d4ab3078.png)

**Comment by damianszczepanik** [comment]
Don't waste more time. Show me json report.

**Comment by npgarcia** [comment]
This is a json example with a failed background and the scenario counted as passed.
https://gist.github.com/npgarcia/dfd97f0888f74f9880893e4006eed85f

**Comment by damianszczepanik** [comment]
There was added some improvement for this https://github.com/damianszczepanik/cucumber-reporting/commit/1b10c5af114652cf6eef797c5ad29189bb202a07 and there will be some update in next releases but I believe you can make it possible even now by setting all flags in configuration to true so any status except PASSED will fail the scenario and feature as well
