### ISSUE TITLE
cannot display the cucumber reports 

### ISSUE THREAD

**Issue by rlagoue** [jenkinsci/cucumber-reports-plugin#68]
Hello,

after upgrading to version 2.6.2 the link to the cucumber reports html file no more works. It redirects me to build page. I tried 2.6.3 without success. Now I am look how to downgrade to 2.5.1

cheers

**Comment by rlagoue** [comment]
I just ran the build again, and the reports (with version 2.6.3) of the last build are displayed. But the reports of the builds executex before are not

**Comment by damianszczepanik** [comment]
Duplicate of damianszczepanik/cucumber-reporting-jenkins/issues/162
