### ISSUE TITLE
Duplicate Features in Report

### ISSUE THREAD

**Issue by emoshaya-cognito** [jenkinsci/cucumber-reports-plugin#69]
Every single report shows two of the same feature even though there's only one...

![image](https://cloud.githubusercontent.com/assets/8818542/17157522/d8adc7ee-5387-11e6-8913-919a73d7cb53.png)

![image](https://cloud.githubusercontent.com/assets/8818542/17157531/eb89d60a-5387-11e6-8e62-f1a066710d3e.png)

**Comment by emoshaya-cognito** [comment]
@damianszczepanik any ideas why the features are duplicated in the reports?

**Comment by damianszczepanik** [comment]
Check Jenkins job logs. I'm sure that report is generated from two reports even you think it is not
