### ISSUE TITLE
Plugin failed build if report-directory/cucumber-json-files doesn't exist

### ISSUE THREAD

**Issue by mplushnikov** [jenkinsci/cucumber-reports-plugin#70]
Hello,
our builds are failing if the plugin doesn't find report directory. I think this is happend if we don't have any cucumber tests in the current execution. (We have configured some generic builds to be executed as part of a build-pipeiline). Plugin tries to find it to copy-> nothing is found-> no directory is created -> failure.

Can you make it more tolerant in such case? I think just doing nothing if there are no cucumber json files is ok.

```
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: /var/lib/jenkins/jobs/PCP-Pipeline/jobs/local-AT/builds/5288/cucumber-html-reports listing returned null
	at net.masterthought.jenkins.SafeArchiveServingAction.processDirectory(SafeArchiveServingAction.java:111)
	at net.masterthought.jenkins.SafeArchiveServingAction.processDirectory(SafeArchiveServingAction.java:138)
	at net.masterthought.jenkins.SafeArchiveServingRunAction.onAttached(SafeArchiveServingRunAction.java:25)
	at hudson.model.Run.addAction(Run.java:393)
	at hudson.model.AbstractBuild.addAction(AbstractBuild.java:972)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:74)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1047)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Cucumber-JVM reports' marked build as failure
```

**Comment by tomdev** [comment]
Yes, running into the same issue here.

**Comment by damianszczepanik** [comment]
Looks like ``mkdir`` was removed because I thought it was not needed

**Comment by damianszczepanik** [comment]
Ok so I need

**Comment by marcusphi** [comment]
Can one have a release with this fix

**Comment by damianszczepanik** [comment]
Yes. Very soon

**Comment by exabrial** [comment]
Has this been fixed? Running into the same issue, or I'm curious if there's a workaround, or if I can be of assistance reproducing the problem

**Comment by damianszczepanik** [comment]
Was fixed. If happens again add stacktrace.

**Comment by sensesnet** [comment]
I have problems with report generation with 3.13.0 version.
For example, i have multi modules maven project. In each of module i have (own pom(with plugin) and runnerTests.class). Each module generate own json in parent target directory after test.  
Built failed if for one of the modules there is no json in parent target.

In version 2.0.0 everything work and report generate only for modules if their json has found in parent target.

**Comment by damianszczepanik** [comment]
provide logs and/or stacktrace

**Comment by sensesnet** [comment]
[INFO] --- maven-cucumber-reporting:3.13.0:generate (execution) @ uitests ---
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.

log4j2 configuration work well. i use 
<dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.8.2</version>
            <scope>provided</scope>
        </dependency>
<dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.8.2</version>
            <scope>provided</scope>
        </dependency>
for configuration i use log4j2.xml but mistake no go away.
i find your issue: https://github.com/damianszczepanik/cucumber-reporting/issues/675
Could you please show configuration parameters for log4j2-test.properties  what did you use?

**Comment by damianszczepanik** [comment]
This error is not a problem for the plugin should be fixed in https://github.com/damianszczepanik/cucumber-reporting/pull/693 and can be fixed locally by providing own log configuration

**Comment by sensesnet** [comment]
"providing own log configuration" 
Could you show how i can do that? i agree it is not plugin problems, but log4j2 normaly working in my project.
I have error only when i try to generate report. 
may be you can show log4j2-test.properties what did you use?

**Comment by tushartone** [comment]
Hello,

[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ CukeDemo ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO]
[INFO] --- maven-cucumber-reporting:2.8.0:generate (execution) @ CukeDemo ---
[WARNING] cucumber.json does not exist.


getting error as when generating report.Please help me

**Comment by damianszczepanik** [comment]
[WARNING] cucumber.json does not exist.

**Comment by damianszczepanik** [comment]
[WARNING] cucumber.json does not exist.

**Comment by tushartone** [comment]
But I have write the step to generate the cucumber.json file but not able to generate.
below is my pom.xml file
<plugin>
				<groupId>net.masterthought</groupId>
				<artifactId>maven-cucumber-reporting</artifactId>
				<version>3.15.0</version>
				<executions>
					<execution>
						<id>execution</id>
						<phase>verify</phase>
						<goals>
							<goal>generate</goal>
						</goals>	
					<configuration>
						<projectName>ExecuteAutomation</projectName>
						<outputDirectory>${project.build.directory}/cucumber-JVM-reports</outputDirectory>
						<cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
						<skippedFails>true</skippedFails>
						<enableFlashCharts>true</enableFlashCharts>
					</configuration>
					</execution>
				</executions>
				
			</plugin>

**Comment by damianszczepanik** [comment]
`cucumber.json` is expected to be a input for the plugin, not output which is generated

**Comment by tushartone** [comment]
Yes,There is missing the cucuimber.json file which is input to cucumber-report.  Finally report is generated. 
Thank you so much for the help.

**Comment by Dwaraka8** [comment]
Hi Damianszczepanik,

Unable to generate Cucumber JVM report (Though cucumber.json file has been generated and passed as input Directory). Tried to generate cucumber jvm report using (mvn install/mvn verify/mvn test). None of those commands generate the report. Please find the below details that I've in my project.

TIA,
Dwaraka.
RunnerScript
=========
@RunWith(Cucumber.class)
@CucumberOptions(strict = false,
        plugin = {"pretty","json:target/json/cucumber.json"},
        glue={"stepdefs"},
        features = {"src/test/features"},
        tags = {"@Second"}
)
public class runnerScript {
}

pom.xml
======

<plugin>
                    <groupId>net.masterthought</groupId>
                    <artifactId>maven-cucumber-reporting</artifactId>
                    <version>4.11.2</version>
                    <executions>
                        <execution>
                            <id>execution</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                            <configuration>
                                <projectName>Test_Project</projectName>
                                <outputDirectory>${project.build.directory}</outputDirectory>
                                <inputDirectory>${project.build.directory}/json</inputDirectory>
                                <jsonFiles>
                                    <file>**/*json</file>
                                </jsonFiles>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
