### ISSUE TITLE
Add Option: `Ignore failed tests (mark build as passed)`

### ISSUE THREAD

**Issue by stevejensen22** [jenkinsci/cucumber-reports-plugin#71]
Sorry if the title is confusing. And thank you so much for the work you do!

I am currently using TestNG with Cucumber (for multi-threaded concurrency) and the TestNG plugin for Jenkins supports configurable Pass, Unstable, and Failure thresholds.  So I am wanting to use that to judge whether or not a Build Passed, is Unstable or Failed.

Since the only option for the the `cucumber-reports-plugin` is to `Ignore failed tests (which marks the build as unstable)`, I am proposing an option be added to `Ignore failed tests (mark build as passed)`

Hopefully the screenshot below illustrates what I'm talking about:

![ignore_failed_tests_mark_build_passed](https://cloud.githubusercontent.com/assets/10365264/17183867/a0fd4446-53e6-11e6-9486-1912cadfdefc.png)

**Comment by damianszczepanik** [comment]
Would it be better to change existing checkbox to drop down list. So you can configure state which is set where the report have failed steps. What do you think?

**Comment by stevejensen22** [comment]
Yeah making a dropdown with options to set the build as `UNSTABLE` or `SUCCESS` would be great!

**Comment by damianszczepanik** [comment]
Will you prepare PR for this change? Will be great.

**Comment by damianszczepanik** [comment]
From now you can configure when the build should be failed, when not

**Comment by andreybehalf** [comment]
Hey guys, it seems like the pipeline generator failing to output the right parameter no matter which build status I choose its always sets it to : 
`buildStatus: <object of type hudson.model.Result> `
Which leads to the following error when trying to run a build: 

> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
> WorkflowScript: 127: unexpected token: < @ line 127, column 71.
>    eportPublisher', buildStatus: <object of
>                                  ^
> 
> 1 error
> 
> 	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
> 	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
> 	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)
> 	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)
> 	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:360)
> 	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:145)
> 	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:111)
> 	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:237)
> 	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:167)
> 	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:931)
> 	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
> 	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
> 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
> 	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
> 	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
> 	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
> 	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
> 	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:67)
> 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:429)
> 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:392)
> 	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:220)
> 	at hudson.model.ResourceController.execute(ResourceController.java:98)
> 	at hudson.model.Executor.run(Executor.java:404)
> Finished: FAILURE


Any suggestions? Thanks.
