### ISSUE TITLE
Can you add screenshots support

### ISSUE THREAD

**Issue by shtraker** [jenkinsci/cucumber-reports-plugin#77]
Hi,
Great plugin , I'm using it on our jenkins and I wounder can you add support for screenshots. When the test scenario fails the framework can make a screenshot and when the plugin generate the report it could include it in the html , so the user can see it. 

Br,
Ceco

**Comment by damianszczepanik** [comment]
If you have attached embedding files such as screenshot or image it will be displayed by the report

**Comment by shtraker** [comment]
When I generate json files where I should attached or embed the screenshot ? Can you give more information or an example please ?
