### ISSUE TITLE
Incomplete AssertionErrors in 

### ISSUE THREAD

**Issue by npgarcia** [jenkinsci/cucumber-reports-plugin#78]
I noticed that when using org.junit.Assert.assertEquals, at failure, the expected and actual values are missing.

![assertmessage](https://cloud.githubusercontent.com/assets/7768581/17712923/4e3bcfc6-63c6-11e6-8e48-888b1b5fffcd.png)

This is a screenshot from the console log. I was expecting to see the same message in the report:

![assertlog](https://cloud.githubusercontent.com/assets/7768581/17713126/5097e8b2-63c7-11e6-860f-d7c92fd5a1b8.png)

**Comment by damianszczepanik** [comment]
They are not missing, they are displayed as they are and because you are passing HTML tags, well they are displayed as HTML

**Comment by npgarcia** [comment]
It is not me, is junit assert message.
Is it possible to escape < > characters so message is visible in the report?

**Comment by damianszczepanik** [comment]
We probably should add checkbox since I don't want to change how the data is displayed in report.

I don't have a plan for this in nearly future but you can prepare PR
