### ISSUE TITLE
Report showing twice number of scenario

### ISSUE THREAD

**Issue by parasp443** [jenkinsci/cucumber-reports-plugin#8]
Report showing twice number of scenario, Suppose 22 scenario ran then report will show 44 scenario ran. It is making double scenario for each feature file.

Please find attached screen shot.

![image](https://cloud.githubusercontent.com/assets/16409775/11971420/823946c8-a963-11e5-8537-bcad05df3aed.png)

**Comment by damianszczepanik** [comment]
Attach json file

**Comment by parasp443** [comment]
Hi,

Here is some more details about configuration where cucumber-reports showing twice number of scnearios

cucumber-jvm version = 1.2.2
Junit version = 4.11
Jenkins version = 1.643
Cucumber-Jenkins-plugin-version=1.0.0

It was working fine with older Cucumber-Jenkins-version (don't remember exactly may be 0.7).

Please find attached JSON and new screenshot

![image](https://cloud.githubusercontent.com/assets/16409775/11976390/ea788e30-a99d-11e5-880c-a4079ddae959.png)
---------------------------------------- Json starts------------------------
[
  {
    "id": "demo-test",
    "tags": [
      {
        "name": "@testDemo",
        "line": 1
      }
    ],
    "description": "",
    "name": "Demo test",
    "keyword": "Feature",
    "line": 2,
    "elements": [
      {
        "description": "",
        "name": "",
        "keyword": "Background",
        "line": 4,
        "steps": [
          {
            "result": {
              "duration": 99138876,
              "status": "passed"
            },
            "name": "login page is open",
            "keyword": "Given ",
            "line": 5,
            "match": {
              "location": "DemoTestSteps.login_page_is_open()"
            }
          }
        ],
        "type": "background"
      },
      {
        "id": "demo-test;test-scenario-first-demo",
        "description": "",
        "name": "test scenario first demo",
        "keyword": "Scenario",
        "line": 7,
        "steps": [
          {
            "result": {
              "duration": 485780,
              "status": "passed"
            },
            "name": "user enters username",
            "keyword": "And ",
            "line": 8,
            "match": {
              "location": "DemoTestSteps.user_enters_username()"
            }
          },
          {
            "result": {
              "duration": 75572,
              "status": "passed"
            },
            "name": "user enters email",
            "keyword": "Then ",
            "line": 9,
            "match": {
              "location": "DemoTestSteps.user_enters_email()"
            }
          },
          {
            "result": {
              "duration": 26435,
              "status": "passed"
            },
            "name": "user enters password",
            "keyword": "Then ",
            "line": 10,
            "match": {
              "location": "DemoTestSteps.user_enters_password()"
            }
          },
          {
            "result": {
              "duration": 23325,
              "status": "passed"
            },
            "name": "user clicks on login button",
            "keyword": "And ",
            "line": 11,
            "match": {
              "location": "DemoTestSteps.user_clicks_on_login_button()"
            }
          }
        ],
        "type": "scenario"
      },
      {
        "description": "",
        "name": "",
        "keyword": "Background",
        "line": 4,
        "steps": [
          {
            "result": {
              "duration": 39497,
              "status": "passed"
            },
            "name": "login page is open",
            "keyword": "Given ",
            "line": 5,
            "match": {
              "location": "DemoTestSteps.login_page_is_open()"
            }
          }
        ],
        "type": "background"
      },
      {
        "id": "demo-test;test-scenario-second-demo",
        "description": "",
        "name": "test scenario second demo",
        "keyword": "Scenario",
        "line": 13,
        "steps": [
          {
            "result": {
              "duration": 30167,
              "status": "passed"
            },
            "name": "user enters username",
            "keyword": "And ",
            "line": 14,
            "match": {
              "location": "DemoTestSteps.user_enters_username()"
            }
          },
          {
            "result": {
              "duration": 28923,
              "status": "passed"
            },
            "name": "user enters password",
            "keyword": "Then ",
            "line": 15,
            "match": {
              "location": "DemoTestSteps.user_enters_password()"
            }
          },
          {
            "result": {
              "duration": 36076,
              "status": "passed"
            },
            "name": "user clicks on submit button",
            "keyword": "And ",
            "line": 16,
            "match": {
              "location": "DemoTestSteps.user_clicks_on_submit_button()"
            }
          }
        ],
        "type": "scenario"
      }
    ],
    "uri": "src/test/java/com/demo/Test/new.feature"
  }
]

---------------------------------------- json end ------------------------
Thanks,
Paras

**Comment by damianszczepanik** [comment]
Support for background scenarios was removed in https://github.com/damianszczepanik/cucumber-reporting/pull/251 but looks like it was not good idea. I need to think it over again.

It counts background as scenario.

**Comment by idealivan** [comment]
I added the JVM argument " -Dhudson.model.DirectoryBrowserSupport.CSP=" to Jenkins start script "/etc/init.d/jenkins" and the problem never raised again. Hope this could help.
