### ISSUE TITLE
Didn't show complete step in reports

### ISSUE THREAD

**Issue by javauser05** [jenkinsci/cucumber-reports-plugin#83]
I am using this "Cucumber-jvm reports" plugin(version 2.5.1) with jenkins for reporting test execution of rest api test cases.

In feature file,I am passing json(highlighted in red color) to rest api in step "When createpursuitsteps post request to create pursuit with one level with valid input json as:"
Refer FeatureFileScreenShot.png for feature file.

However,after test execution I can't see the json that I am passing in step.
Refer Report.png for feature file.

![featurefilescreenshot](https://cloud.githubusercontent.com/assets/21197534/17893006/a129701c-6961-11e6-8493-73be581fa80a.png)

![report](https://cloud.githubusercontent.com/assets/21197534/17893018/a8ddc880-6961-11e6-9940-3d439f5fd2e0.png)

Attaching "cucumber.json" that get generated after running test cases for more information.
Please rename cucumber.json.txt to cucumber.json
[cucumber.json.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/432489/cucumber.json.txt)

**Comment by damianszczepanik** [comment]
What language do you use to generate json report?

**Comment by javauser05** [comment]
I am using JAVA language.
I am running my testcases through ANT.

In ANT, I am running my feature file and generating cucumber.json , junit and html reports in below way.

		<java classname="cucumber.api.cli.Main" fork="true" failonerror="false" resultproperty="cucumber.exitstatus">
		    <classpath refid="classpath"/>
			<arg value="--plugin"/>
			
			<arg value="junit:${report.dir}/cucumber-junit-report/allcukes.xml"/>
			<arg value="--plugin"/>
			<arg value="pretty"/>
			<arg value="--plugin"/>
			
			<arg value="html:${report.dir}/cucumber-html-report"/>
			<arg value="--plugin"/>
			
			<arg value="json:${report.dir}/cucumber.json"/>
			<arg value="--glue"/>
			
			<arg value="${stepdefs}"/>
			<arg value="--glue"/>
			
			<arg value="${scenariodata}"/>
			
			<arg value="${featureFileToExecute}"/>
			<arg value="--tags"/>
			<arg value="${tagstorun}"/>		
		</java>


Attaching complete report folder for more information.
[reports.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/432946/reports.zip)

**Comment by damianszczepanik** [comment]
Works fine with the most recent version, so upgrade and try again

**Comment by javauser05** [comment]
My Jenkins server version is 2.7.2.
Current Cucumber Reports Plugin is 2.5.1.

I can't see latest available version for this plugin.

**Comment by damianszczepanik** [comment]
https://github.com/jenkinsci/cucumber-reports-plugin/releases
http://repo.jenkins-ci.org/releases/net/masterthought/jenkins/cucumber-reports/

**Comment by javauser05** [comment]
My bad.My Jenkins server is on Version 1.609.2.
And latest “Cucumber-jvm reports”  plugin require required core dependencies as 1.625.3.

It seems I had to first update my server.Will update my server and check it.
Thanks all for your help.
