### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by udayanem** [jenkinsci/cucumber-reports-plugin#85]
Hi,

This plug-in works very well from Jenkins.

By chance, is there way to have API or code to invoke this report?

When we run automation a test suite, it generate cucumber.json.

Do we have API/methods which converts 'cucumber.json' to Cucumber reports?

API's are great way to help in this regard.

Thanks,
Uday

**Comment by damianszczepanik** [comment]
Yes
https://github.com/damianszczepanik/cucumber-reporting

**Comment by udayanem** [comment]
Hi Damian,

Based on the sample code provided, i refactored my code as

```
	public void generateCucumberReports()
	{
		File reportOutputDirectory = new File("target");
		List<String> jsonFiles = new ArrayList<>();
		jsonFiles.add("E:\\Programming\\Cucumber\\linenhouse_V2\\target\\cucumber.json");

		String jenkinsBasePath = "";
		String buildNumber = "1";
		String projectName = "linenhouse_V2";  //any project name
		Configuration configuration = new Configuration(reportOutputDirectory, projectName);

		ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
		reportBuilder.generateReports();
	}
```
But blank reports are getting generated. Attaching json file and corresponding reports generated.

Can you please help me where i am going wrong?

[cucumber.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/463880/cucumber.txt)

![features](https://cloud.githubusercontent.com/assets/10852370/18386277/87b7115c-76b3-11e6-84ac-c6a48a47275b.png)
![steps](https://cloud.githubusercontent.com/assets/10852370/18386283/95571dc0-76b3-11e6-9e98-bc043c6948cf.png)

**Comment by damianszczepanik** [comment]
I could generate the report so check the path
