### ISSUE TITLE
Report Graph shows "This content requires JavaScript"

### ISSUE THREAD

**Issue by rahullodha85** [jenkinsci/cucumber-reports-plugin#9]
I recently upgraded cucmber reports plugin to version 1.0.0, and now i see "This content requires JavaScript" instead of actual graph.
 
Please help with a fix or a workaround.
Thank You!

Attached here is browser log
[browser log.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/73596/browser.log.txt)

**Comment by djwgit** [comment]
got the same issue, after upgrading to jenkins 1.643 and plugin 1.0.0
downgrade to jenkins 1.638 and plugin 0.1, still same issue with the report.

**Comment by rahullodha85** [comment]
@djwgit I am running jenkins as a service so i had to run System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "") from jenkins script console. but javascript error did not occur after setting this flag to empty string.
Thank you for your help :)

**Comment by damianszczepanik** [comment]
Duplicate of jenkinsci/cucumber-reports-plugin/issues/7

**Comment by enggabhishekshinde** [comment]
Please do following steps to fix it.

Add or modify following parameter in /etc/sysconfig/jenkins file..

JENKINS_JAVA_OPTIONS=" -Djava.awt.headless=true **-Dhudson.model.DirectoryBrowserSupport.CSP=\"\"** "

**Comment by damianszczepanik** [comment]
No need to, recent release fixes this problem

**Comment by TeresaP** [comment]
We just updated Jenkins and our plug-in was severely out of date, so we updated it to 2.5.0. Now, when we view our reports, we see the above error: `This content requires JavaScript`. I have tried editing our jenkins-runner.sh file's javaArgs to ```javaArgs=" -Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"\" "``` without luck. Is this still a recommended workaround?

**Comment by enggabhishekshinde** [comment]
HI TerasaP,

Please let me know which Jenkins version you are using. Also please check java process on jenkins server whether it's contain CSP flag or not.

Regards,
Abhishek.

**Comment by enggabhishekshinde** [comment]
HI TeresaP,

Please let me know which Jenkins version you are using. Also please check java process on jenkins server whether it's contain CSP flag or not.

Regards,
Abhishek.

**Comment by damianszczepanik** [comment]
New version has been published, please upgrade
