### ISSUE TITLE
Embedded text for just download

### ISSUE THREAD

**Issue by dragan-pazin** [jenkinsci/cucumber-reports-plugin#92]
Would be nice to have embedded text which would be similar to the existing one of type "text/plain", but when clicking on the link, text would open in new browser tab - same functionality that is available for "text/plain" when clicking download icon, just without any text embedded in the report itself.
Maybe suitable  Mimetype for such embeddings would be just "file".

In my case I would use it for big xml files, which are not suitable to be displayed within report, but would be still accessible by just one click.

**Comment by damianszczepanik** [comment]
Show me JSON report so I know what type you are talking about

**Comment by dragan-pazin** [comment]
Here is  obsufocated example - I used tex/plain mimetype, but I had to replace < with &lt; in embeddd xmls.
[CucumberReport.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/543930/CucumberReport.zip)

**Comment by dragan-pazin** [comment]
I think all would be needed is just to add something like this in embedding.vm:

    #elseif ($embedding.getMimeType() == "file")
      #includeFileEmbedding($embedding, $foreach.index)
....

#macro(includeFileEmbedding, $embedding, $type, $content, $index)
  #set($index = $index + 1)
    <div data-toggle="collapse" data-target="#embedding_$embedding.getFileId()" class="collapsable-control">
      <a>Attachment $index ($type)</a>
      <a href="embeddings/$embedding.getFileName()" target="_blank"><span class="download-button glyphicon glyphicon-download-alt"></span></a>
    </div>
#end

**Comment by damianszczepanik** [comment]
So just to clarify:
- do you want to have option to download any type of the file, or
- there is some kind of the file with mimetype "file" which should be suported

**Comment by dragan-pazin** [comment]
Any type of file would be ok.

**Comment by damianszczepanik** [comment]
This is OK to me but instead of providing generic download  option I'd rather want to support different types in different way. This is how it works now.

**Comment by dragan-pazin** [comment]
I was not clear.
This is how I would have it: if mimetype is ste to "file", then there would be just link to embedded file available. For other mimetypes it would work sam as before.

**Comment by damianszczepanik** [comment]
"file:" is not correct mime type

**Comment by dragan-pazin** [comment]
Ok. What about two additional mime types:
application/xml - would show just a link to open xml attachement in new browser tab
text/xml - would show xml in expandable way with download icon. Similar as plain/text now - just that for expandable view &lt would be replaced with &lt so that xml si correctly displayed.

**Comment by damianszczepanik** [comment]
Will be supported from incoming release
