### ISSUE TITLE
Duplicate results

### ISSUE THREAD

**Issue by lemrouch** [jenkinsci/cucumber-reports-plugin#97]
Hi,
I have problems described in https://github.com/jenkinsci/cucumber-reports-plugin/issues/69

The root cause is:
1) we use cucumber-reports-plugin and archive artifacts post build steps
2) we want to archive json files stored as artifacts
3) the archive step stores them like
/var/lib/jenkins/jobs/features-tests/builds/3450/archive/test/features/ControlCenterBrandPermissions.feature.json
4) cucumber-reports-plugin stores json files itself as
/var/lib/jenkins/jobs/features-tests/builds/3450/ControlCenterBrandPermissions.feature.json
5) the cucumber-reports-plugin works in job root and finds both files

Workaround might be switching archive step after cucumber-reports step.
Right solution is probably to use plugin specific subdirectory for storing json files in the way archive does.

Pavel

**Comment by damianszczepanik** [comment]
you can configure which jsons should be parsed by using exclude and include patterns

**Comment by lemrouch** [comment]
Sure, we found out and used this fix.
It was not clear if those patterns are applied in workspace on node or job directory on jenkins server from the description at first.
In this case I don't see why the default is **/*.json. It just means that plugin will search for any json files in all other plugins subdirs.

And I see other problem with storing all json files in job root. If there is filename collision in different subdirs on node, your plugin will have and use just one in the end.
I really think you should use plugin specific subdir in job directory and preserve directory tree from node there.

Thanks for you solution anyway.

**Comment by damianszczepanik** [comment]
It works in workspace directory, and I think this is quite clear. You can also refer to build logs and find information from which directory JSON files are copied:
```
[CucumberReport] Copied 3 json files from "X:\dev\Jenkins\.jenkins\jobs\cucumber\workspace" to reports directory "X:\dev\Jenkins\.jenkins\jobs\cucumber\builds\195"
```

So if your case is that jsons are copied from plugin archive directory I expect that this is the problem with plugin that stores data in workspace (which can be cleared any time). If this is not true, let me know the case so I can reproduce the issue.

**Comment by lemrouch** [comment]
Hi,
I don't agree.

Our log from job with duplicate results says:
`
[CucumberReportPublisher] Copying all json files from slave: /home/hudson/at/workspace/features-tests/test/features to master reports directory: /var/lib/jenkins/jobs/features-tests/builds/3446
[CucumberReportPublisher] Found 422 json files.
[CucumberReportPublisher] 1. Found a json file: AdminAccountExpirationCronJob.feature.json
[CucumberReportPublisher] 212. Found a json file: archive/test/features/AdminAccountExpirationCronJob.feature.json
`
The cucumber-reports-plugin is looking into other plugins subdirectories in job directory on Jenkins server.
It was "fixed" by setting File Include Pattern to *.json instead of default **/*.json. Therefore it has to filter json files on Jenkins server and not the in workspace directory on node:
`
[CucumberReportPublisher] Copying all json files from slave: /home/hudson/at/workspace/features-tests/test/features to master reports directory: /var/lib/jenkins/jobs/features-tests/builds/3467<br />
[CucumberReportPublisher] Found 211 json files.<br />
[CucumberReportPublisher] 1. Found a json file: AdminAccountExpirationCronJob.feature.json
`

**Comment by damianszczepanik** [comment]
Problem confirmed, patch prepared but not tested yet
